import {useState} from 'react';
import {useStore} from 'zustand';
import {Link} from '@tanstack/react-router';
import {Button,LoadingState,ErrorState,Mark,DenseList,DenseRow,SegmentedFilters} from '../../shared/ui/index.js';
import type {ObservationGroup,ObservationMember} from '../../shared/api/observations.js';
import {observationCopy,resolutionLabel,observationMemberLabel} from '../../shared/observation-copy.js';
import {prepareOperatorPacket} from '../../shared/observation-packet.js';
import {Timestamp} from '../settings/preferences.js';
import {useProjects} from '../tenancy/data.js';
import {useObservationGroups,useObservationMembers,readObservationMembers} from './data.js';
import {observationScreenState,observationExpansion} from './state.js';
export function ObservationsScreen({projectId,filter={}}:{projectId:string;filter?:{kind?:'filing'|'type'|'custody';group?:string;view?:'open'|'resolved'}}){
 const [store]=useState(()=>observationScreenState(filter.view)),state=useStore(store),projects=useProjects(),admin=projects.data?.find(p=>p.id===projectId)?.role==='admin';
 const query=useObservationGroups(projectId,state.view),custody=useObservationGroups(projectId,state.view,true,admin);
 const linked=Boolean(filter.kind||filter.group),opposite=state.view==='open'?'resolved':'open',other=useObservationGroups(projectId,opposite,false,linked),otherCustody=useObservationGroups(projectId,opposite,true,linked&&admin);
 const matches=(g:ObservationGroup)=>(!filter.kind||filter.kind===g.kind)&&(!filter.group||filter.group===g.id);
 const groups=[...(query.data?.items??[]),...(admin?custody.data?.items??[]:[])].filter(matches),filings=groups.filter(g=>g.kind==='filing');
 const countReady=!query.isPending&&!query.isError&&(!admin||!custody.isPending&&!custody.isError)&&(!linked||!other.isPending&&!other.isError&&(!admin||!otherCustody.isPending&&!otherCustody.isError));
 const counts=!countReady?{open:undefined,resolved:undefined}:linked?{[state.view]:groups.reduce((n,g)=>n+g.count,0),[opposite]:[...(other.data?.items??[]),...(admin?otherCustody.data?.items??[]:[])].filter(matches).reduce((n,g)=>n+g.count,0)}:{open:(query.data?.counts.open??0)+(admin?custody.data?.counts.open??0:0),resolved:(query.data?.counts.resolved??0)+(admin?custody.data?.counts.resolved??0:0)};
 const prepare=async(selected:readonly ObservationGroup[],one?:ObservationMember)=>{store.getState().begin();try{
  const entries=[];for(const group of selected){const members=one?[one]:await readObservationMembers(projectId,group.id,group.state,false);if(!members.length||(!one&&members.length!==group.count))throw new Error('Observation membership changed.');entries.push({group,members});}
  store.getState().prepared(prepareOperatorPacket(entries,new Date().toISOString()));
 }catch{store.getState().failed('The complete packet could not be prepared. Try again; no partial packet was produced.');}};
 const copy=async(text:string)=>{try{await navigator.clipboard.writeText(text);store.getState().notify('Copied.');}catch{store.getState().notify('Clipboard access is unavailable. Select and copy the packet or download it.');}};
 const download=()=>{if(!state.packet)return;const url=URL.createObjectURL(new Blob([state.packet],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='opintel-operator-packet.txt';a.click();URL.revokeObjectURL(url);};
 return <section className="screen on" data-layout="observations"><h1>Observations</h1><p className="sub">Things the system noticed and set aside rather than guessing about. Grouped by what happened, because the same cause can affect several things at once.</p>
 {linked?<p className="note">Showing the linked observation scope. <Link className="btn ghost" to="/projects/$projectId/$screen" params={{projectId,screen:'observations'}} search={{}}>Show all observations</Link></p>:null}
 <div className="filters"><SegmentedFilters label="Observation state" value={state.view} options={[{value:'open',label:'Open',count:counts.open},{value:'resolved',label:'Resolved',count:counts.resolved}]} onChange={state.show}/><Button variant="ghost" disabled={!filings.length||state.preparing||query.isPending||query.isError} onClick={()=>{void prepare(filings);}}>{state.preparing?'Preparing…':'Prepare for the operator'}</Button></div>
 {state.notice?<p className="note" role="status">{state.notice}</p>:null}
 {state.packet?<section className="card" data-purpose="operator-packet" aria-labelledby="operator-packet-heading"><header className="card-h"><h2 id="operator-packet-heading">Prepared for the operator</h2><Button variant="ghost" onClick={state.close}>Close packet</Button></header><div className="sheetb"><p>This is a packet for you to carry. Nothing has been sent.</p><div className="pgbox"><label htmlFor="operator-packet">Copyable summary</label><textarea id="operator-packet" readOnly rows={14} value={state.packet}/></div></div><footer className="sheetf"><Button variant="ghost" onClick={()=>{void copy(state.packet!);}}>Copy packet</Button><Button onClick={download}>Download packet</Button></footer></section>:null}
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Observations could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:null}
 {admin&&custody.isError?<ErrorState title="Key custody observations could not be loaded" description={custody.error.message} retry={()=>custody.refetch()}/>:null}
 {linked&&other.isError?<ErrorState title="Linked observation counts could not be loaded" description={other.error.message} retry={()=>other.refetch()}/>:null}
 {linked&&admin&&otherCustody.isError?<ErrorState title="Linked custody counts could not be loaded" description={otherCustody.error.message} retry={()=>otherCustody.refetch()}/>:null}
 {countReady&&!groups.length&&(!admin||!custody.isPending)&&!custody.isError?<p className="note">{state.view==='open'?'Nothing needs attention.':'No resolved observations recorded yet.'}</p>:null}
 <div data-mark-list="mixed">{groups.map(group=><Group key={group.id+group.state} projectId={projectId} group={group} preparing={state.preparing} prepare={(one)=>{void prepare([group],one);}} copyIds={member=>{void copy(`Landing zone ID: ${member.metadata.zoneId}\nFiling ID: ${member.metadata.filingId}\nEngine ID: ${member.metadata.engineId??'Not recorded'}`);}}/>)}</div>
 </section>;
}
function Group({projectId,group,preparing,prepare,copyIds}:{projectId:string;group:ObservationGroup;preparing:boolean;prepare:(one?:ObservationMember)=>void;copyIds:(member:ObservationMember)=>void}){
 const [store]=useState(observationExpansion),state=useStore(store),query=useObservationMembers(projectId,group,state.open),copy=observationCopy(group),id=`observation-${group.id}`;
 const unit=group.kind==='filing'?'filing':group.kind==='type'?'element':'key version';
 return <article className="card" data-layout="observation" data-state={group.state} aria-label={copy.title}><header className="card-h" data-mark-row="true" data-row-kind="finding">
 <span className="sev" role="img" aria-label={group.state==='resolved'?'Resolved':group.kind==='filing'?'Quarantined':'Needs attention'} title={group.state==='resolved'?'Resolved':group.kind==='filing'?'Quarantined':'Needs attention'}>{group.state==='open'?<Mark name={group.kind==='filing'?'quarantined':'needs-a-decision'} size={18}/>:null}</span>
 <div data-part="identity"><h2>{copy.title}</h2><span className="meta">{group.count} {unit}{group.count===1?'':'s'} · {group.state==='resolved'?'resolved':'oldest'} <Timestamp value={group.state==='resolved'?group.latestAt:group.oldestAt}/></span><p>{group.state==='open'?copy.consequence:'Resolved. The earlier finding and its recorded resolution remain below.'}</p></div><span className="mono" data-part="count">{group.count}</span><button className="toolchip" type="button" aria-expanded={state.open} aria-controls={id} onClick={state.toggle}>{state.open?'Hide':'Details'}</button>
 </header><div id={id} hidden={!state.open}>{state.open?<><div className="sheetb" data-part="remediation"><div><b>Resolved by {copy.owner}.</b><p>{group.state==='open'?copy.instructions:'This group is a record. Each row names the recorded resolution.'}</p>{copy.privacy?<p>{copy.privacy}</p>:null}</div>{group.kind==='filing'?<Button disabled={preparing} onClick={()=>prepare()}>Prepare for the operator</Button>:group.kind==='custody'?<Link className="btn ghost" to="/projects/$projectId/$screen" params={{projectId,screen:'token-key'}}>Open token key</Link>:<Link className="btn ghost" to="/projects/$projectId/$screen" params={{projectId,screen:'data-sources'}}>Open data sources</Link>}</div>
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Affected records could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:<DenseList kindScope="uniform" label={`Affected ${unit}s`}>{query.data.map(member=><div key={member.id} data-member-state={member.state}><DenseRow kind={group.kind} identity={<><b title={member.kind==='type'?`${member.metadata.sourceName}: ${observationMemberLabel(member)}`:member.metadata.filingId}>{observationMemberLabel(member)}</b>{group.state==='resolved'?<p>{resolutionLabel(member.resolution)}</p>:null}{member.kind==='custody'&&group.state==='open'?<p>{member.metadata.keyState==='retired'?'Retired. This retained key is needed to verify earlier evidence.':member.metadata.keyState==='current'?'Current. Source connections are refused until backup verification succeeds.':'Key role is not recorded.'}</p>:null}</>} metadata={<><span className="mono" title={member.kind==='filing'?`Filing ID: ${member.metadata.filingId}; landing zone ID: ${member.metadata.zoneId}; engine: ${member.metadata.engineName??'Not recorded'}`:member.metadata.sourceName}>{member.kind==='filing'?`${member.metadata.filingId?.slice(0,8)} · zone ${member.metadata.zoneId?.slice(0,8)}`:member.metadata.sourceName}</span><Timestamp value={member.resolvedAt??member.observedAt} appearance="rwhen"/></>} actions={<>{member.kind==='filing'?<><Button variant="ghost" aria-label={`Copy IDs for filing ${member.metadata.filingId}`} onClick={()=>copyIds(member)}>Copy ids</Button><Button variant="ghost" aria-label={`Prepare filing ${member.metadata.filingId} for the operator`} disabled={preparing} onClick={()=>prepare(member)}>Prepare</Button></>:member.kind==='type'&&member.metadata.runId?<Link className="btn ghost" to="/projects/$projectId/introspections/$runId" params={{projectId,runId:member.metadata.resolutionRunId??member.metadata.runId}}>View introspection</Link>:null}<button className="toolchip" type="button" aria-expanded={state.history===member.id} aria-controls={`${id}-${member.id}-history`} onClick={()=>state.toggleHistory(member.id)}>History</button></>}/><div className="sheetb" id={`${id}-${member.id}-history`} hidden={state.history!==member.id}>{state.history===member.id?<>{member.kind==='filing'?<><p>Filing ID: <span className="mono" style={{userSelect:'all'}}>{member.metadata.filingId}</span></p><p>Landing zone ID: <span className="mono" style={{userSelect:'all'}}>{member.metadata.zoneId}</span></p><p>Engine: {member.metadata.engineName??'Not recorded'} (<span className="mono" style={{userSelect:'all'}}>{member.metadata.engineId??'Not recorded'}</span>)</p></>:<p className="mono">{observationMemberLabel(member)}</p>}{member.history.map((fact,i)=><p key={i}><Timestamp value={fact.at}/> · {fact.state==='open'?observationCopy({...group,cause:fact.cause}).title:resolutionLabel(fact.resolution)}</p>)}</>:null}</div></div>)}</DenseList>}
 </>:null}</div></article>;
}
