import {Timestamp} from '../settings/preferences.js';
import {useState} from 'react';
import {useStore} from 'zustand';
import {Link} from '@tanstack/react-router';
import {Button,LoadingState,ErrorState,EmptyState} from '../../shared/ui/index.js';
import {domainMigrationConfirmation} from '../../shared/token-domain.js';
import {SuggestionAction,type Suggestion} from '../../shared/api/suggestions.js';
import {useProjects} from '../tenancy/data.js';
import {useSuggestions,useDomains,useAttempts,useDecision} from './data.js';
import {reviewForm} from './state.js';
export function SuggestionsScreen({projectId}:{projectId:string}){
 const query=useSuggestions(projectId),projects=useProjects(),admin=projects.data?.find(p=>p.id===projectId)?.role==='admin';
 return <section className="screen on"><h1>Suggested relationships</h1><p className="sub">An agent attempted these joins. That demonstrates a need; deciding that the columns identify the same entity belongs to an administrator. No source values are read.</p>
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Suggestions could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:!query.data.items.length?<EmptyState title="No join suggestions" description="Refused equality joins will appear here. Unanswered suggestions never change tokens."/>:query.data.items.map(item=><Review key={item.id} item={item} projectId={projectId} projectName={query.data.projectName} admin={admin}/>)}
 </section>;
}
function Review({item,projectId,projectName,admin}:{item:Suggestion;projectId:string;projectName:string;admin:boolean}){
 const [store]=useState(reviewForm),form=useStore(store),domains=useDomains(projectId),action=useDecision(projectId,item.id);
 const selected=domains.data?.find(d=>d.domain===form.domain),members=selected?.members??[];
 const draft=SuggestionAction.safeParse({action:'confirm',domain:form.domain,confirmation:form.confirmation,latestAttemptId:item.latestAttemptId,members:members.map(m=>({elementId:m.elementId,version:m.version}))});
 const canConfirm=admin&&!item.confirmationBlocked&&!domains.isPending&&!domains.isError&&draft.success&&form.confirmation===projectName&&(form.mode==='existing'?!!selected:!selected);
 return <article className="card"><div className="card-h"><h2 style={{overflowWrap:'anywhere'}}>{item.left.name} ↔ {item.right.name}</h2><span className="meta">{item.status==='not_sure'?'Not sure':item.status==='confirm'?'Confirmed':item.status==='reject'?'Rejected':'Awaiting review'}</span></div><div className="sheetb">
 <p>{item.queries} query attempts · {item.explains} explain attempts. Most recent: <Timestamp value={item.latestAt}/>. These count attempts, not independent needs.</p><p style={{overflowWrap:'anywhere'}}>Agents (self-declared): {item.agents.join(', ')}. Pools: {item.pools.map(p=>p.name).join(', ')}.</p>
 {item.raisedAgain?<p className="note">A later attempt raised this deferred suggestion again.</p>:null}
 <Button type="button" variant="ghost" aria-expanded={form.attemptsOpen} aria-controls={`attempts-${item.id}`} onClick={form.toggleAttempts}>Attempts and SQL</Button><div id={`attempts-${item.id}`} hidden={!form.attemptsOpen}>{form.attemptsOpen?<Attempts projectId={projectId} id={item.id}/>:null}</div>
 {item.confirmationBlocked?<p className="note">{item.confirmationBlocked} <Link to="/projects/$projectId/$screen" params={{projectId,screen:'entitlements'}}>Open entitlements</Link></p>:null}
 {!admin?<p className="note">Read-only. A project administrator reviews suggestions.</p>:null}
 <form onSubmit={e=>{e.preventDefault();if(canConfirm&&draft.success)action.mutate(draft.data,{onError:()=>form.confirm('')});}}>
 <div className="fld"><label htmlFor={`choice-${item.id}`}>Shared domain choice</label><select className="inp" style={{maxWidth:'100%'}} id={`choice-${item.id}`} value={form.mode} disabled={!admin||action.isPending||!!item.confirmationBlocked} onChange={e=>form.choose(e.target.value==='new'?'new':'existing')}><option value="existing">Choose an existing domain</option><option value="new">Declare a new domain</option></select></div>
 {domains.isPending?<LoadingState/>:domains.isError?<ErrorState title="Domains could not be loaded" description={domains.error.message} retry={()=>domains.refetch()}/>:form.mode==='existing'?<div className="fld"><label htmlFor={`domain-${item.id}`}>Existing shared domain</label><select className="inp" style={{maxWidth:'100%'}} id={`domain-${item.id}`} value={form.domain} disabled={!admin||action.isPending||!!item.confirmationBlocked} onChange={e=>form.edit(e.target.value)}><option value="">Choose explicitly</option>{domains.data.map(d=><option key={d.domain} value={d.domain}>{d.domain} — {d.members.map(m=>m.name).join(', ')}</option>)}</select><p className="hint">Each option names every existing member before you choose. No column’s domain is chosen automatically.</p></div>:<div className="fld"><label htmlFor={`domain-${item.id}`}>New shared domain</label><input id={`domain-${item.id}`} value={form.domain} disabled={!admin||action.isPending||!!item.confirmationBlocked} onChange={e=>form.edit(e.target.value)}/><p className="hint">Lowercase letters and digits. sentinel and the opintelisolated prefix are reserved.</p>{selected?<p className="note">This domain already exists. Choose it explicitly to review its members.</p>:null}</div>}
 {form.domain?<p className="note" style={{overflowWrap:'anywhere'}}>Existing members: {members.map(m=>m.name).join(', ')||'None'}. Confirming adds both columns to this namespace; it also enables compatible token joins with its other members across pools. Both columns’ existing canonicalisation declarations are preserved; this item does not test formats.</p>:null}
 <p className="note">{domainMigrationConfirmation} Past evidence retains its key and domain assignment versions.</p>
 <div className="fld"><label htmlFor={`confirm-${item.id}`}>Type project name: {projectName}</label><input id={`confirm-${item.id}`} value={form.confirmation} disabled={!admin||action.isPending||!!item.confirmationBlocked} onChange={e=>form.confirm(e.target.value)} autoComplete="off"/></div>
 <Button type="submit" disabled={!canConfirm||action.isPending}>{action.isPending&&action.variables?.action==='confirm'?'Confirming…':'Confirm'}</Button>{' '}<Button type="button" variant="ghost" disabled={!admin||action.isPending} onClick={()=>action.mutate({action:'reject',latestAttemptId:item.latestAttemptId})}>Reject</Button>{' '}<Button type="button" variant="ghost" disabled={!admin||action.isPending} onClick={()=>action.mutate({action:'not_sure',latestAttemptId:item.latestAttemptId})}>Not sure</Button>
 </form>{action.isError?<p className="note" role="alert">{action.error.message}</p>:null}{action.isSuccess?<p className="note" role="status">Decision recorded.</p>:null}
 <Button type="button" variant="ghost" aria-expanded={form.historyOpen} aria-controls={`history-${item.id}`} onClick={form.toggleHistory}>Decision and assignment history ({item.history.length})</Button><div id={`history-${item.id}`} hidden={!form.historyOpen}>{item.history.length?item.history.map(h=><p key={h.id} style={{overflowWrap:'anywhere'}}>{h.action==='not_sure'?'Not sure':h.action==='confirm'?'Confirmed':'Rejected'} by {h.actorName} ({h.actorId}) at <Timestamp value={h.at}/>{h.domain?` · Shared domain: ${h.domain}`:''}. {h.assignments.map(a=>`${a.elementId}: assignment version ${a.version}`).join(', ')}</p>):<p>No decisions recorded.</p>}</div>
 </div></article>;
}
function Attempts({projectId,id}:{projectId:string;id:string}){const query=useAttempts(projectId,id);return query.isPending?<LoadingState/>:query.isError?<ErrorState title="Attempts could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:<>{query.data.map(a=><div className="joinbox" key={a.id}><p>{a.operation} · <Timestamp value={a.at}/> · {a.agentId}</p>{a.statement?<pre className="mono" style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{a.statement}</pre>:<p>SQL hidden by Activity permissions or redaction policy.</p>}</div>)}</>;}
