import {PostgresElementDeclarations} from '../src/modules/catalog/index.js';
import {beforeAll,afterAll,it,expect} from 'vitest';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import {Client} from 'pg';
import {policyFixture,unwrap} from './fixtures/policy-version/fixture.js';
import {prepareSidecarDevelopment} from '../scripts/sidecar-dev.js';
import {developmentEngineOptions} from '../scripts/development-engine.js';
import {loadSidecarConfig} from '../sidecar/config.js';
import {createSidecarServer} from '../sidecar/http/server.js';
import {FileCustody} from '../sidecar/custody/infrastructure/file-custody.js';
import {DevelopmentFileKeyStore,DevelopmentFileKeyEscrow} from '../sidecar/custody/infrastructure/development-file-keys.js';
import {EngineRegistry,PostgresEngineRepository,HttpsEngineProbe,RegistryCustodyClient,authorizeEngineReceipt,engineRoutes} from '../src/modules/engines/index.js';
import {KeyCustodyService,PostgresCustodyRepository} from '../src/modules/entitlements/index.js';
import {createHttpServer} from '../src/platform/http/index.js';
import {withTenant,withPlatform} from '../src/platform/db/scope.js';
import {ok,Timestamp} from '../src/shared/kernel/index.js';
import {SidecarTokenizer,IanaZoneResolver} from '../sidecar/tokenize/index.js';
import {allowBulk} from './fixtures/bulk-entitlements/fixture.js';
let directory:string,host:ReturnType<typeof createSidecarServer>,options:Awaited<ReturnType<typeof developmentEngineOptions>>,custody:FileCustody;
beforeAll(async()=>{directory=await mkdtemp(join(tmpdir(),'engine-registry-'));await prepareSidecarDevelopment(directory);const {config,tls}=await loadSidecarConfig(join(directory,'service.json'));custody=new FileCustody(await DevelopmentFileKeyStore.open(config.custody!.keyStore),await DevelopmentFileKeyEscrow.open(config.custody!.keyEscrow));const unused=async()=>ok({reachable:true as const});host=createSidecarServer({config:{...config,port:0},tls,custody,connector:{testConnection:unused,introspect:unused,sampleTopValues:unused,estimateRowCount:unused} as Parameters<typeof createSidecarServer>[0]['connector']});const port=await host.listen();options={...await developmentEngineOptions(join(directory,'service.json')),baseUrl:`https://127.0.0.1:${port}`};},30000);
afterAll(async()=>{await host?.close();await rm(directory,{recursive:true,force:true});});
async function fixture(){const f=await policyFixture(1);await withPlatform(tx=>tx.query('INSERT INTO user_account(id,email) VALUES($1,$2) ON CONFLICT DO NOTHING',[f.ctx.userId,f.ctx.userId+'@test.example']));await f.set('tokenized');const repo=new PostgresEngineRepository(),registry=new EngineRegistry(repo,new HttpsEngineProbe(),options.tls);const registered=unwrap(await registry.register(f.ctx,{name:'Customer segment A',address:options.baseUrl,certificatePin:options.tls.certificatePin}));return {...f,repo,registry,registered};}
it('5.20: registration is unverified; a valid hex typo fails verification before assignment; correcting it requires a fresh check',async()=>{const f=await fixture();expect((await f.registry.forEngine(f.ctx,f.registered.id)).ok).toBe(false);unwrap(await f.registry.update(f.ctx,f.registered.id,{name:f.registered.name,address:options.baseUrl,certificatePin:'00'.repeat(32)}));const bad=await f.registry.verify(f.ctx,f.registered.id);expect(bad.ok).toBe(false);if(!bad.ok){expect(bad.error.message).toContain('could not be verified');expect(bad.error.message).not.toContain('ERR_TLS');}expect(unwrap(await f.repo.get(f.ctx,f.registered.id)).verifiedAt).toBeNull();expect((await f.registry.assign(f.ctx,f.source,f.registered.id)).ok).toBe(false);unwrap(await f.registry.update(f.ctx,f.registered.id,{name:f.registered.name,address:options.baseUrl,certificatePin:options.tls.certificatePin}));expect(unwrap(await f.registry.verify(f.ctx,f.registered.id))).toMatchObject({contractVersion:2,health:'healthy'});});
it('5.20: missing engine names the source; custody is designated explicitly and source assignment checks the primary sentinel',async()=>{const f=await fixture();const absent=await f.registry.forSource(f.ctx,f.source);expect(absent.ok).toBe(false);if(!absent.ok)expect(absent.error.message).toContain('Source Warehouse has no assigned engine');unwrap(await f.registry.verify(f.ctx,f.registered.id));unwrap(await f.registry.designate(f.ctx,f.registered.id));const service=new KeyCustodyService(new PostgresCustodyRepository(),new RegistryCustodyClient(f.registry),{...allowBulk,checkMany:async r=>Promise.all(r.map(q=>allowBulk.check(q)))});unwrap(await service.ensure(f.ctx));unwrap(await f.registry.assign(f.ctx,f.source,f.registered.id));expect(unwrap(await f.registry.forSource(f.ctx,f.source,true)).baseUrl).toBe(options.baseUrl);expect(await authorizeEngineReceipt(options.tls.certificatePin,f.ctx.projectId,f.source)).toBe(true);expect(await authorizeEngineReceipt('00'.repeat(32),f.ctx.projectId,f.source)).toBe(false);const foreign=await policyFixture(0);expect(await authorizeEngineReceipt(options.tls.certificatePin,foreign.ctx.projectId,f.source)).toBe(false);const page=await f.registry.list(f.ctx,null,10);expect(page[0]?.sources).toEqual([{id:f.source,name:'Warehouse'}]);});
it('5.20: an unprovisioned engine and a stale key after rotation refuse tokenized execution; clear routing remains available',async()=>{const f=await fixture();unwrap(await f.registry.verify(f.ctx,f.registered.id));unwrap(await f.registry.designate(f.ctx,f.registered.id));const actual=unwrap(await custody.invoke('initialize',f.ctx.projectId,{})) as {keyVersion:number;sentinelToken:string};await withTenant(f.ctx,tx=>tx.query("INSERT INTO token_key_version(project_id,version,sentinel_token,state) VALUES($1,1,$2,'current')",[f.ctx.projectId,actual.sentinelToken]));unwrap(await f.registry.assign(f.ctx,f.source,f.registered.id));await withTenant(f.ctx,async tx=>{await tx.query("UPDATE token_key_version SET state='retired'");await tx.query("INSERT INTO token_key_version(project_id,version,sentinel_token,state) VALUES($1,2,$2,'current')",[f.ctx.projectId,actual.sentinelToken]);});const stale=await f.registry.forSource(f.ctx,f.source,true);expect(stale.ok).toBe(false);if(!stale.ok)expect(stale.error.message).toContain('key version or sentinel');expect((await f.registry.forSource(f.ctx,f.source,false)).ok).toBe(true);expect((await f.registry.assign(f.ctx,f.source,f.registered.id)).ok).toBe(false);});
it('5.20: token execution independently rejects a wrong primary key even after a prior successful attestation',async()=>{const f=await fixture();const actual=unwrap(await custody.invoke('initialize',f.ctx.projectId,{})) as {sentinelToken:string};const tokenizer=new SidecarTokenizer({resolveBytes:async()=>Buffer.alloc(32,23)},new IanaZoneResolver(),{record:()=>{}});let ran=false;const result=await tokenizer.run(f.ctx.projectId,()=>{ran=true;return ok('wrong token');},1,actual.sentinelToken);expect(result.ok).toBe(false);expect(ran).toBe(false);});
it('5.20: contract mismatch is recorded and refused; engines and assignments cannot cross projects',async()=>{const f=await fixture();const registry=new EngineRegistry(f.repo,{health:async()=>ok({contract:99,queryEngineVersion:'',canonicalisers:[]}),sentinel:async()=>ok({version:null,sentinel:null})},options.tls);const result=await registry.verify(f.ctx,f.registered.id);expect(result.ok).toBe(false);expect(unwrap(await f.repo.get(f.ctx,f.registered.id))).toMatchObject({health:'contract_mismatch',contractVersion:99,verifiedAt:null});const other=await policyFixture(0);expect((await f.repo.get(other.ctx,f.registered.id)).ok).toBe(false);await expect(withTenant(other.ctx,tx=>tx.query('UPDATE data_source SET engine_id=$1 WHERE id=$2',[f.registered.id,other.source]))).rejects.toMatchObject({constraint:'source_engine_project'});});
it('5.20: registry writes require project administration; readers can inspect health and sources',async()=>{const f=await fixture();let admin=false;const server=createHttpServer(engineRoutes(f.registry),{authorization:{currentUser:async()=>f.actor,port:{...allowBulk,check:async r=>({...await allowBulk.check(r),allowed:r.permission==='view'||admin})}}});server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();if(!address||typeof address==='string')throw new Error();const url=`http://127.0.0.1:${address.port}/api/v1/projects/${f.ctx.projectId}/engines`;try{expect((await fetch(url)).status).toBe(200);const post=()=>fetch(url+'/'+f.registered.id+'/verify',{method:'POST',headers:{'content-type':'application/json'},body:'{}'});expect((await post()).status).toBe(403);admin=true;expect((await post()).status).toBe(200);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}});
it('5.20: the forward migration rolls down and up without inventing assignments',async()=>{const db=new Client({connectionString:process.env.TEST_DATABASE_URL});await db.connect();try{await db.query('BEGIN');await db.query(await readFile('migrations/058_engine_registry_policies.down.sql','utf8'));await db.query(await readFile('migrations/057_engine_registry.down.sql','utf8'));await db.query(await readFile('migrations/057_engine_registry.up.sql','utf8'));await db.query(await readFile('migrations/058_engine_registry_policies.up.sql','utf8'));const result=await db.query('SELECT engine_id FROM data_source');expect(result.rows.every((r:{engine_id:string|null})=>r.engine_id===null)).toBe(true);await db.query('ROLLBACK');}finally{await db.end();}});
it('ENG-002: two sources route to their own engines for introspection and validation; a cross-engine query refuses',async()=>{
 const f=await fixture();const {config,tls}=await loadSidecarConfig(join(directory,'service.json'));let sourceCalls=0,validationCalls=0;
 const unused=async()=>ok({reachable:true as const});
 const second=createSidecarServer({config:{...config,port:0},tls,custody,connector:{testConnection:async()=>{sourceCalls++;return ok({reachable:true as const});},introspect:unused,sampleTopValues:unused,estimateRowCount:unused} as Parameters<typeof createSidecarServer>[0]['connector'],execution:{execute:async()=>ok({}),validate:async()=>{validationCalls++;return ok({queryEngineVersion:'not-loaded',treatmentEvidence:{aggregateMinGroupSize:5,stage2Required:false,stage2Ran:false}});}}});
 try{const port=await second.listen();const b=unwrap(await f.registry.register(f.ctx,{name:'Customer segment B',address:`https://127.0.0.1:${port}`,certificatePin:options.tls.certificatePin}));unwrap(await f.registry.verify(f.ctx,f.registered.id));unwrap(await f.registry.verify(f.ctx,b.id));const actual=unwrap(await custody.invoke('initialize',f.ctx.projectId,{})) as {sentinelToken:string};const {SourceId}=await import('../src/shared/kernel/index.js');const source=SourceId(randomUUID());await withTenant(f.ctx,async tx=>{await tx.query("INSERT INTO token_key_version(project_id,version,sentinel_token,state) VALUES($1,1,$2,'current')",[f.ctx.projectId,actual.sentinelToken]);await tx.query("INSERT INTO data_source(id,project_id,name,exposed_alias,kind,credential_ref,status) VALUES($1,$2,'Segment B','segment_b','postgres','secret://test/source','connected')",[source,f.ctx.projectId]);});unwrap(await f.registry.assign(f.ctx,f.source,f.registered.id));unwrap(await f.registry.assign(f.ctx,source,b.id));
 const {registryConnector,RegistryQueryExecution}=await import('../src/modules/engines/index.js');const {SecretRef}=await import('../src/platform/secrets/index.js');const connector=registryConnector(f.registry,f.ctx,{projectId:f.ctx.projectId,sourceId:source,requestId:randomUUID(),sampling:async()=>ok({consentGiven:false,elements:[]})});unwrap(await connector.testConnection(SecretRef('secret://test/source')));expect(sourceCalls).toBe(1);
 const {validationRequest}=await import('../src/shared/execution-contract.js');const input=validationRequest.parse({requestId:randomUUID(),projectId:f.ctx.projectId,poolId:f.pool,sql:'SELECT 1',namespace:{catalog:'memory',schema:'main'},policyVersion:1,sources:[{sourceId:source,credentialRef:'secret://test/source'}],objects:[],entitlements:[],aggregateMinGroupSize:5,entitlementContext:null});const client=new RegistryQueryExecution(f.registry,f.repo);unwrap(await client.validate(input,undefined,f.ctx));expect(validationCalls).toBe(1);const cross=await client.validate({...input,sources:[...input.sources,{sourceId:f.source,credentialRef:'secret://test/source'}]},undefined,f.ctx);expect(cross.ok).toBe(false);if(!cross.ok)expect(cross.error.code).toBe('sources_cannot_be_joined');expect(validationCalls).toBe(1);
 }finally{await second.close();}
});
it('ENG-001: an in-flight verification cannot approve an address or pin edited while it was running',async()=>{
 const f=await fixture();let release!:()=>void,start!:()=>void;const started=new Promise<void>(r=>{start=r;});const gate=new Promise<void>(r=>{release=r;});
 const registry=new EngineRegistry(f.repo,{health:async()=>{start();await gate;return ok({contract:2,queryEngineVersion:'not-loaded',canonicalisers:[]});},sentinel:async()=>ok({version:null,sentinel:null})},options.tls);
 const pending=registry.verify(f.ctx,f.registered.id);await started;unwrap(await registry.update(f.ctx,f.registered.id,{name:f.registered.name,address:options.baseUrl,certificatePin:'00'.repeat(32)}));release();expect((await pending).ok).toBe(false);expect(unwrap(await f.repo.get(f.ctx,f.registered.id)).verifiedAt).toBeNull();
});
it('ENG-006: the live receipt listener accepts the assigned engine and rejects another project/source before persistence',async()=>{
 const f=await fixture();unwrap(await f.registry.verify(f.ctx,f.registered.id));unwrap(await f.repo.assign(f.ctx,f.source,f.registered.id));const foreign=await policyFixture(0);let accepted=0;
 const {createLandingReceiptServer}=await import('../src/modules/ingest/api/landing-receipt-server.js');const {AcceptLandingReceipt}=await import('../src/modules/ingest/application/landing-receipts.js');const {HttpsLandingReceipts}=await import('../sidecar/ingest/infrastructure/receipt-client.js');const {tls}=await loadSidecarConfig(join(directory,'service.json'));
 const server=createLandingReceiptServer(options.tls,new AcceptLandingReceipt({accept:async()=>{accepted++;return ok(undefined);}}),undefined,authorizeEngineReceipt);server.listen(0,'127.0.0.1');await once(server,'listening');const address=server.address();if(!address||typeof address==='string')throw new Error();const client=new HttpsLandingReceipts(`https://127.0.0.1:${address.port}`,{ca:tls.ca,cert:tls.cert,key:tls.key,pinnedCertificate:tls.clientPin});const {FilingId}=await import('../src/shared/kernel/index.js');const receipt={filingId:FilingId(randomUUID()),projectId:f.ctx.projectId,sourceId:f.source,partyCode:'test',kind:'test',period:'2026',asAt:null,strategy:'append_as_at' as const,landedTable:'test',rowCount:1,fileSha256:'ab'.repeat(32),supersedes:null,landedAt:new Date().toISOString()};
 try{expect((await client.send(receipt)).ok).toBe(true);expect(accepted).toBe(1);expect((await client.send({...receipt,projectId:foreign.ctx.projectId,sourceId:foreign.source})).ok).toBe(false);expect((await client.send({...receipt,sourceId:foreign.source})).ok).toBe(false);expect(accepted).toBe(1);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
it('ENG-004: a verified engine without a project key may serve a clear-only source, while tokenized dispatch refuses',async()=>{
 const f=await policyFixture(0),repo=new PostgresEngineRepository(),registry=new EngineRegistry(repo,new HttpsEngineProbe(),options.tls);const e=unwrap(await registry.register(f.ctx,{name:'Clear-only segment',address:options.baseUrl,certificatePin:options.tls.certificatePin}));unwrap(await registry.verify(f.ctx,e.id));unwrap(await registry.assign(f.ctx,f.source,e.id));expect((await registry.forSource(f.ctx,f.source)).ok).toBe(true);const tokens=await registry.forSource(f.ctx,f.source,true);expect(tokens.ok).toBe(false);if(!tokens.ok)expect(tokens.error.message).toContain('no recorded token key');
});
it('ENG-002: a missing engine names the source without marking the database itself unreachable',async()=>{
 const f=await fixture();const {IntrospectionJob,PostgresIntrospectionStore}=await import('../src/modules/sources/index.js');const {registryConnector}=await import('../src/modules/engines/index.js');const {UuidV7IdFactory}=await import('../src/shared/kernel/index.js');
 const job=new IntrospectionJob(new PostgresIntrospectionStore(new UuidV7IdFactory()),(source,runId,ctx)=>registryConnector(f.registry,ctx,{projectId:ctx.projectId,sourceId:source.id,requestId:runId,sampling:async()=>ok({consentGiven:false,elements:[]})}));
 const queued=unwrap(await job.enqueue(f.ctx,f.source));const failed=unwrap(await job.execute(f.ctx,queued.id));expect(failed.state).toBe('failed');expect(failed.error).toContain('Source Warehouse has no assigned engine');expect(unwrap(await job.source(f.ctx,f.source)).status).toBe('connected');
});

it('DECL-006: declaration discovery follows the element source to its verified pinned Engine',async()=>{
 const f=await fixture(),declarations=new PostgresElementDeclarations(new RegistryCustodyClient(f.registry));
 const absent=unwrap(await declarations.read(f.ctx,f.ids[0]!));expect(absent.canonicalisers).toEqual([]);expect(absent.discoveryError).toContain('Warehouse has no assigned engine');
 unwrap(await f.registry.verify(f.ctx,f.registered.id));unwrap(await f.registry.designate(f.ctx,f.registered.id));
 const service=new KeyCustodyService(new PostgresCustodyRepository(),new RegistryCustodyClient(f.registry),{...allowBulk,checkMany:async r=>Promise.all(r.map(q=>allowBulk.check(q)))});
 unwrap(await service.ensure(f.ctx));unwrap(await f.registry.assign(f.ctx,f.source,f.registered.id));
 const assigned=unwrap(await declarations.read(f.ctx,f.ids[0]!));expect(assigned.discoveryError).toBeNull();expect(assigned.canonicalisers).toEqual(expect.arrayContaining(['stdtext1','stdnum1','stdtime1','stddate1']));
});
