import { randomUUID } from 'node:crypto';
import { resolve } from 'node:path';
import { Client } from 'pg';
import { beforeAll,afterAll,it,expect,vi } from 'vitest';
import { PostgresSourceScope } from '../sidecar/infrastructure/postgres-source-scope.js';
import { PostgresStagingSource } from '../sidecar/execution/infrastructure/postgres-source.js';
import { StagedExecutor } from '../sidecar/execution/application/execute.js';
import { DuckDBSessionEngine } from '../sidecar/session/index.js';
import { SidecarTokenizer,IanaZoneResolver } from '../sidecar/tokenize/index.js';
import { executionRequest } from '../src/shared/execution-contract.js';
const schema='staging_'+randomUUID().replaceAll('-',''),sourceId=randomUUID();
async function fixture(sql:string){const c=new Client({connectionString:process.env.TEST_DATABASE_URL});try{await c.connect();await c.query(sql);}finally{await c.end();}}
beforeAll(async()=>{await fixture(`CREATE SCHEMA ${schema};CREATE TABLE ${schema}.orders(id integer,customer integer,hidden text);INSERT INTO ${schema}.orders VALUES(1,123,'secret'),(2,456,'secret'),(3,789,'secret');ALTER TABLE ${schema}.orders ADD COLUMN numbers bigint[] DEFAULT ARRAY[9007199254740993::bigint,2];ANALYZE ${schema}.orders;`);},30000);
afterAll(async()=>{await fixture(`DROP SCHEMA ${schema} CASCADE`);},30000);
function request(){const elementId=randomUUID();return executionRequest.parse({tokenKeyVersionSelected:1,requestId:'staging-source',entitlements:[{elementId,treatment:'clear'}],projectId:randomUUID(),poolId:randomUUID(),policyVersion:1,sql:'SELECT id FROM orders ORDER BY id',namespace:{catalog:'warehouse',schema:'public'},sources:[{sourceId,credentialRef:'secret://test/source'}],objects:[{catalog:'warehouse',schema:'public',name:'orders',sourceId,readPlan:{catalog:'warehouse',schema,object:'orders',columns:[{sourceIdentifier:'id',exposedName:'id',exposedType:'INTEGER',elementId,treatment:'clear',readAs:'native'}]}}],aggregateMinGroupSize:5,limits:{memoryMb:64,threads:1,timeoutMs:10000,rowLimit:2,concurrency:1},entitlementContext:null});}
function executor(proof?:{attachments:number;appended:unknown[][];closed:string[]}){const scope=new PostgresSourceScope({resolve:async()=>process.env.TEST_DATABASE_URL!},{maxConnectionsPerSource:1,statementTimeoutMs:5000,operationTimeoutMs:10000});const source=new PostgresStagingSource(scope,new SidecarTokenizer({resolveBytes:async()=>Buffer.alloc(32,1)},new IanaZoneResolver()));return new StagedExecutor(source,r=>{const native=new DuckDBSessionEngine(undefined,undefined,resolve('tmp/duckdb-extensions/postgres_scanner.duckdb_extension'),r.limits);return {open:async role=>{const session=await native.open(role);if(proof){const materialize=session.staging!.materialize,append=session.staging!.append,close=session.close;session.staging!.materialize=async(...args)=>{proof.attachments++;return materialize(...args);};session.staging!.append=async(...args)=>{proof.appended.push(...structuredClone(args[3]));return append(...args);};session.close=()=>{proof.closed.push(role);close();};}return session;}};});}
it('C.1 native PostgreSQL attach materializes only the pool columns after pushdown',async()=>{const r=request();r.sql='SELECT id FROM orders WHERE id>1 ORDER BY id';expect(await executor().execute(r)).toMatchObject({ok:true,value:{rows:[[2],[3]],truncated:false,executionPath:'staged'}});},30000);
it('C.1 connector tokenizes an integer before it reaches staging',async()=>{const r=request();r.objects[0]!.readPlan.columns.push({sourceIdentifier:'customer',exposedName:'customer',exposedType:'VARCHAR',elementId:randomUUID(),treatment:'tokenized',readAs:'text',token:{domain:'customer',canonId:'stdnum1',mode:'number',caseInsensitive:false}});r.entitlements.push({elementId:r.objects[0]!.readPlan.columns.at(-1)!.elementId,treatment:'tokenized'});r.sql='SELECT id,customer FROM orders ORDER BY id';const proof={attachments:0,appended:[] as unknown[][],closed:[] as string[]};const result=await executor(proof).execute(r);expect(result.ok,result.ok?'':result.error.message).toBe(true);expect(proof.attachments).toBe(0);expect(proof.appended[0]?.[1]).toMatch(/^v1_customer_/);expect(proof.closed).toEqual(['agent','privileged','agent','privileged']);expect(result).toMatchObject({value:{truncated:true}});if(result.ok){const value=result.value as {rows:unknown[][]};expect(value.rows[0]?.[1]).toMatch(/^v1_customer_/);expect(JSON.stringify(value)).not.toContain('secret');}},30000);

for(const treated of [false,true])it(`C.1 preserves exact clear arrays on the ${treated?'connector':'native'} path`,async()=>{
 const r=request(),elementId=randomUUID();r.objects[0]!.readPlan.columns.push({sourceIdentifier:'numbers',exposedName:'numbers',exposedType:'LIST(BIGINT)',elementId,treatment:'clear',readAs:'native'});r.entitlements.push({elementId,treatment:'clear'});
 if(treated){const c=r.objects[0]!.readPlan.columns[0]!;c.treatment='masked';c.mask={kind:'all'};c.readAs='text';c.exposedType='VARCHAR';r.entitlements[0]!.treatment='masked';}
 r.sql='SELECT numbers FROM orders';const result=await executor().execute(r);expect(result.ok,result.ok?'':result.error.message).toBe(true);expect(result).toMatchObject({value:{rows:[[['9007199254740993','2']],[['9007199254740993','2']]]}});
},30000);
it('J-024 execution telemetry contains only the allowlist, never source values or SQL',async()=>{
 const logs=vi.spyOn(console,'info').mockImplementation(()=>{});try{const r=request();r.sql="SELECT 'ROW_VALUE_SENTINEL' FROM orders";expect((await executor().execute(r)).ok).toBe(true);
 for(const [event] of logs.mock.calls){expect(Object.keys(event as object).every(k=>['event','requestId','projectId','poolId','operation','reason'].includes(k))).toBe(true);}
 expect(JSON.stringify(logs.mock.calls)).not.toContain('ROW_VALUE_SENTINEL');expect(logs).toHaveBeenCalled();}finally{logs.mockRestore();}
},30000);
