import { Link } from '@tanstack/react-router';
import { Button,EmptyState,ErrorState,LoadingState,StageRail,Treatment,type Stage } from '../../shared/ui/index.js';
import type { RunView } from '../../shared/api/introspection.js';
import { useProjects } from '../tenancy/data.js';
import { useSources } from '../sources/data.js';
import { active,useIntrospection,useIntrospections,useCancelIntrospection } from './data.js';
const stamp=(value:string|null)=>value?value.slice(0,19).replace('T',' ')+' UTC':'Not started';
function Badge({state}:{state:RunView['state']}){return <span className={state==='complete'?'tr clear':state==='failed'?'tr held':'tr ref'}><i aria-hidden="true"/>{state}</span>;}
export function IntrospectionListScreen({projectId,sourceId}:{projectId:string;sourceId:string}){
 const query=useIntrospections(projectId,sourceId);const sources=useSources(projectId);const name=sources.data?.find(s=>s.id===sourceId)?.name??'Source';const items=query.data?.pages.flatMap(p=>p.items)??[];
 return <section className="screen on"><h1>Introspection runs</h1><p className="sub">{name} · Structure discovered in this source, and what changed.</p><Link className="btn ghost" to="/projects/$projectId/$screen" params={{projectId,screen:'data-sources'}}>Data sources</Link>
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Runs could not be loaded" description={query.error.message} retry={()=>{void query.refetch();}}/>:!items.length?<EmptyState icon="⛁" title="No introspection runs yet" description="Return to Data sources to connect or retry this source."/>:<div className="card" style={{marginTop:14}}><div role="region" aria-label="Introspection history" tabIndex={0} style={{overflowX:'auto'}}><table><thead><tr><th>Run</th><th>State</th><th>Started</th><th>Changes</th></tr></thead><tbody>{items.map(run=><tr key={run.id}><td><Link className="mono" to="/projects/$projectId/introspections/$runId" params={{projectId,runId:run.id}}>{run.id}</Link></td><td><Badge state={run.state}/></td><td className="mono">{stamp(run.startedAt)}</td><td>{run.diff===null?'Not published':run.diff.length===0?'No changes':run.diff.length}</td></tr>)}</tbody></table></div>{query.hasNextPage?<Button variant="ghost" disabled={query.isFetchingNextPage} onClick={()=>{void query.fetchNextPage();}}>Load more runs</Button>:null}</div>}</section>;
}
const phases=['queued','connecting','reading','diffing','complete'] as const;
export function IntrospectionRunScreen({projectId,runId}:{projectId:string;runId:string}){
 const query=useIntrospection(projectId,runId);const cancel=useCancelIntrospection(projectId,runId);const projects=useProjects();const run=query.data;
 const stages:Stage[]=phases.map(name=>({name,detail:name===run?.state?'Current state':'',status:!run?'wait':name===run.state?run.state==='complete'?'done':'run':phases.indexOf(name)<phases.findIndex(p=>p===run.state)?'done':'wait'}));
 return <section className="screen on"><h1>Introspection run</h1><p className="sub">The source’s structure and changes to the catalogue.</p>
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Run could not be loaded" description={query.error.message} retry={()=>{void query.refetch();}}/>:run?<>
 <div className="filters"><Link className="btn ghost" to="/projects/$projectId/sources/$sourceId/introspections" params={{projectId,sourceId:run.sourceId}}>All source runs</Link><Badge state={run.state}/>{projects.data?.find(p=>p.id===projectId)?.role==='admin'&&['queued','connecting','reading'].includes(run.state)?<Button variant="ghost" disabled={cancel.isPending} onClick={()=>cancel.mutate()}>{cancel.isPending?'Cancelling…':'Cancel introspection'}</Button>:null}</div>
 <p className="note mono" style={{overflowWrap:'anywhere'}}>Run {run.id}<br/>Started: {stamp(run.startedAt)}{run.endedAt?<><br/>Ended: {stamp(run.endedAt)}</>:null}</p>
 <StageRail title={`Introspection ${run.state}`} elapsed={`${run.progress.objects}${run.progress.total===null?'':` / ${run.progress.total}`} objects`} stages={stages}/>
 {active(run.state)?<p className="note" role="status">Progress refreshes every 5 seconds. The diff appears when introspection completes.</p>:null}
 {run.error?<p role="alert">{run.error}</p>:null}{cancel.isError?<p role="alert">{cancel.error.message}</p>:null}
 {run.state==='cancelled'?<EmptyState icon="⛁" title="Introspection cancelled" description="The previous catalogue is preserved. Return to Data sources to start a new run."/>:run.state==='failed'?<p className="note">The previous catalogue is preserved. Return to Data sources to retry.</p>:run.diff!==null&&run.diff.length===0?<EmptyState calm icon="✓" title="No changes since the last introspection." description="The catalogue is unchanged. Existing access decisions are preserved."/>:run.diff?<section className="card"><div className="card-h"><h2>Catalogue diff</h2><span className="meta">{run.diff.length} changes</span></div><div role="region" aria-label="Catalogue changes" tabIndex={0} style={{overflowX:'auto'}}><table><thead><tr><th>Element</th><th>Change</th><th>Before</th><th>After</th><th>Access decision</th></tr></thead><tbody>{run.diff.map((diff,index)=><tr key={index}><td className="mono"><span title={diff.elementId??undefined}>{diff.duckdbName??'Unnameable'}</span></td><td>{diff.change.replaceAll('_',' ')}{diff.breaking?<><br/><span className="tr held"><i aria-hidden="true"/>Breaking change</span></>:null}</td><td className="mono">{diff.before??'—'}</td><td className="mono">{diff.after??'—'}</td><td>{diff.change==='type_changed'&&diff.breaking?<><Treatment kind="undecided" label="Reverts to undecided"/><p className="note">Type family changed. The previous decision is discarded; a new decision is required.</p></>:diff.change==='added'?<Treatment kind="undecided"/>:diff.change==='removed'?'Decision retained, inactive.':diff.change==='renamed'?'Identity and decision retained.':diff.change==='type_changed'?'Decision retained.':'Review the assigned name.'}</td></tr>)}</tbody></table></div><p className="note" style={{padding:16}}>Only a type-family change discards an access decision. Removed elements retain their decisions for evidence reproducibility.</p></section>:null}
 </>:null}</section>;
}
