export { CatalogElement, CatalogObject } from './domain/catalog.js';
export type { AssignElementIdentity, CatalogChange, CatalogObjectState, ElementDiscovery, ElementState } from './domain/catalog.js';
export { CatalogNaming } from './application/naming.js';
export type { AssignedName, IdentifierTransliterator } from './application/naming.js';
export { mapSourceType, classifySourceType, numericDefault, postTreatmentType } from './domain/type-mapping.js';
export type { ExposedType, SourceTypeSpec, Treatment } from './domain/type-mapping.js';
export { describeElement } from './domain/describe-element.js';
export { exposedObjectName } from './domain/namespace.js';
export { reconcileSnapshot, type IntrospectionDiff } from './application/introspection-diff.js';
export { AsciiTransliterator } from './infrastructure/ascii-transliterator.js';
export { PostgresTemporalRepository } from './infrastructure/temporal.js';
export { validateTokenizedTemporal } from './application/temporal.js';
export type { TemporalRepository, TemporalDeclarations, TemporalView, TemporalContext } from './application/temporal.js';
export { PostgresTokenDeclarations } from './infrastructure/token-declarations.js';
export { validateTokenDeclarations } from './application/token-declarations.js';
export type { TokenDeclarationRepository, TokenDeclarations } from './application/token-declarations.js';
export { hydrateCatalogObject, type CatalogObjectRow, type CatalogElementRow } from './infrastructure/hydration.js';

export { standardCanonId, validateCanonicaliserType } from './application/canonicaliser-mode.js';
export { PostgresElementDeclarations } from './infrastructure/declarations.js';
export { effectiveDeclarations, tokenBehaviour } from './application/declarations.js';
export type { DeclarationRepository, DeclarationCanonicalisers } from './application/declarations.js';
