import {randomUUID} from 'node:crypto';
import {withTenant} from '../../../platform/db/scope.js';
import {EngineId,DomainError,err,ok,type SourceId} from '../../../shared/kernel/index.js';
import {EngineView,type EngineRegistration} from '../../../shared/api/engines.js';
import type {EngineContext,EngineRepository,EngineRecord} from '../application/registry.js';
const columns=`id,name,address,certificate_pin AS "certificatePin",contract_version AS "contractVersion",to_char(verified_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS "verifiedAt",to_char(last_seen_at AT TIME ZONE 'UTC','YYYY-MM-DD"T"HH24:MI:SS.MS"Z"') AS "lastSeenAt",health,health_message AS "healthMessage",custody`;
const record=(r:unknown):EngineRecord=>EngineView.omit({sources:true}).parse(r);
export class PostgresEngineRepository implements EngineRepository {
 update(ctx:EngineContext,id:EngineId,input:EngineRegistration){return withTenant(ctx,async tx=>{const rows=await tx.query("UPDATE engine SET name=$2,address=$3,certificate_pin=$4,verified_at=NULL,contract_version=NULL,health='unverified',health_message=NULL WHERE id=$1 RETURNING id",[id,input.name,input.address,input.certificatePin]);return rows.length?ok(undefined):err(new DomainError('not_found','Engine not found in this project.'));});}
 async register(ctx:EngineContext,input:EngineRegistration){try{return await withTenant(ctx,async tx=>{const [r]=await tx.query(`INSERT INTO engine(id,project_id,name,address,certificate_pin) VALUES($1,$2,$3,$4,$5) RETURNING ${columns}`,[randomUUID(),ctx.projectId,input.name,input.address,input.certificatePin]);return ok(record(r));});}catch(e){if(e instanceof Error&&'code'in e&&e.code==='23505')return err(new DomainError('conflict','This engine address is already registered in the project.'));throw e;}}
 get(ctx:EngineContext,id:EngineId){return withTenant(ctx,async tx=>{const [r]=await tx.query(`SELECT ${columns} FROM engine WHERE id=$1`,[id]);return r?ok(record(r)):err(new DomainError('not_found','Engine not found in this project.'));});}
 list(ctx:EngineContext,after:EngineId|null,limit:number){return withTenant(ctx,async tx=>(await tx.query(`SELECT ${columns},COALESCE((SELECT jsonb_agg(jsonb_build_object('id',s.id,'name',s.name) ORDER BY s.name,s.id) FROM data_source s WHERE s.engine_id=engine.id AND s.status<>'archived'),'[]'::jsonb) AS sources FROM engine WHERE ($1::uuid IS NULL OR id>$1) ORDER BY id LIMIT $2`,[after,limit])).map(r=>EngineView.parse(r)));}
 health(ctx:EngineContext,id:EngineId,v:{contractVersion:number|null;health:EngineView['health'];message:string|null;verified:boolean;address:string;certificatePin:string;name:string}){return withTenant(ctx,async tx=>{await tx.query(`UPDATE engine SET contract_version=$2,health=$3,health_message=$4,last_seen_at=CASE WHEN $2::integer IS NULL THEN last_seen_at ELSE now() END,verified_at=CASE WHEN $5 THEN now() ELSE NULL END WHERE id=$1 AND address=$6 AND certificate_pin=$7 AND name=$8`,[id,v.contractVersion,v.health,v.message,v.verified,v.address,v.certificatePin,v.name]);});}
 custody(ctx:EngineContext){return withTenant(ctx,async tx=>{const [r]=await tx.query(`SELECT ${columns} FROM engine WHERE custody`);return r?ok(record(r)):err(new DomainError('source_unavailable','This project has no designated custody engine. Designate a verified engine in Settings.'));});}
 designate(ctx:EngineContext,id:EngineId){return withTenant(ctx,async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtextextended($1,57))',[ctx.projectId]);const pending=await tx.query('SELECT id FROM token_key_operation WHERE completed_at IS NULL');if(pending.length)return err(new DomainError('conflict','Finish the pending custody operation before changing the custody engine.'));const target=await tx.query('SELECT id FROM engine WHERE id=$1 AND verified_at IS NOT NULL AND contract_version=2 FOR UPDATE',[id]);if(!target.length)return err(new DomainError('conflict','Engine verification changed; verify it again.'));await tx.query('UPDATE engine SET custody=false WHERE custody');await tx.query('UPDATE engine SET custody=true WHERE id=$1',[id]);return ok(undefined);});}
 source(ctx:EngineContext,id:SourceId){return withTenant(ctx,async tx=>{const [r]=await tx.query<{id:SourceId;name:string;engineId:EngineId|null;tokenized:boolean}>(`SELECT s.id,s.name,s.engine_id AS "engineId",EXISTS(SELECT 1 FROM entitlement t JOIN catalog_element e ON e.id=t.element_id JOIN catalog_object o ON o.id=e.object_id WHERE o.source_id=s.id AND t.treatment='tokenized') AS tokenized FROM data_source s WHERE s.id=$1`,[id]);return r?ok(r):err(new DomainError('not_found','Source not found in this project.'));});}
 assign(ctx:EngineContext,source:SourceId,id:EngineId){return withTenant(ctx,async tx=>{const rows=await tx.query('UPDATE data_source SET engine_id=$2 WHERE id=$1 AND EXISTS(SELECT 1 FROM engine WHERE id=$2 AND verified_at IS NOT NULL AND contract_version=2) RETURNING id',[source,id]);return rows.length?ok(undefined):err(new DomainError('conflict','Source or verified engine not found in this project.'));});}
 key(ctx:EngineContext){return withTenant(ctx,async tx=>{const [r]=await tx.query<{version:number;sentinel:string}>("SELECT version,sentinel_token AS sentinel FROM token_key_version WHERE state='current'");return r??null;});}
}
