import {useMemo} from 'react';
import {createStore,useStore} from 'zustand';
import {Link} from '@tanstack/react-router';
import {Button,Treatment,Mark,type MarkName} from '../../shared/ui/index.js';
import type {EvidenceDetail} from '../../shared/api/activity.js';
import {Timestamp as DisplayTimestamp} from '../settings/preferences.js';
import {evidenceElementName,shortPath,treatmentLabels} from './presentation.js';
const stamp=(value:string|null)=>value===null?'Never':<DisplayTimestamp value={value} appearance="rwhen"/>;
export function AnswerTreatments({counts}:{counts:Record<string,number>}){
 return <div className="interp" data-part="answer-treatments" role="list" data-mark-list="uniform" aria-label="Recorded answer treatments">{Object.entries(counts).filter(([kind,n])=>['clear','tokenized','masked','aggregate_only'].includes(kind)&&n>0).map(([kind,n])=><span className="ichip" key={kind} role="listitem" data-mark-row="true" data-row-kind="treatment" title={`${treatmentLabels[kind]}: ${n} recorded elements`}><Mark name={`treatment-${kind==='aggregate_only'?'aggregate':kind}` as MarkName} label={treatmentLabels[kind]} size={17} treatmentColour="var(--ink-2)"/><span>{n}</span></span>)}</div>;
}
export function EvidenceDetails({r,projectId,permalink=false}:{r:EvidenceDetail;projectId:string;permalink?:boolean}){
 const store=useMemo(()=>createStore<{extra:boolean;notice:string;toggle:()=>void;notify:(notice:string)=>void}>(set=>({extra:false,notice:'',toggle:()=>set(s=>({extra:!s.extra})),notify:notice=>set({notice})})),[r.id,r.startedAt]);
 const state=useStore(store),candidate=r.metadata.refusal?.candidate;
 const delivered=r.elements.filter(e=>e.state==='released'||e.state==='aggregated'),omitted=r.elements.filter(e=>e.state==='withheld'||e.state==='undecided');
 const bodyId=`metadata-${r.id}`;
 return <>
 {r.status==='incomplete'?<p className="joinbox">No answer was recorded. No completion was recorded, so this evidence does not establish whether a response reached the agent.</p>:r.metadata.refusal?<div className="joinbox"><b>{r.status==='failed'?'Request failed.':'Request refused.'}</b> {r.metadata.refusal.message}<p>Recorded reason: {r.refusalCode??'Not recorded'}{r.metadata.refusal.stage?` · ${r.metadata.refusal.stage}`:''}</p>{candidate?<p>{candidate.columns.map(c=>shortPath(c.name)).join(' · ')}</p>:null}</div>:null}
 <div className="scopepick" data-layout="paired">
 <section className="card"><header className="card-h"><h2>Statement</h2><span className="meta">{r.argumentVisibility==='literal_stripped'?'literals removed':r.argumentVisibility==='raw'?'as recorded':'arguments hidden'}</span></header><div className="sheetb"><div className="qbox">{r.request??(r.recordKind==='rollup'?'Request arguments were removed by retention.':'Arguments are hidden by your permissions or the evidence policy.')}</div></div><footer className="sheetf">Policy {r.versions.policy} · Catalogue {r.versions.catalog} · Key used {r.status==='incomplete'?'unknown':r.tokenKeyVersionUsed??'none'}</footer></section>
 <section className="card"><header className="card-h"><h2>{r.status==='refused'||r.status==='failed'?'Recorded plan':'What the answer contained'}</h2></header><div className="sheetb">
 {r.status==='refused'||r.status==='failed'?<><p className="note">These are planned object references, not deliveries.</p>{r.objects.map(o=><p key={o.catalog+o.schema+o.name} className="mono" title={`${o.catalog}.${o.schema}.${o.name}`}>{o.name}</p>)}</>:r.recordKind==='rollup'?<><p className="note">Summary counts only; element detail was removed by retention.</p><AnswerTreatments counts={r.treatmentCounts}/></>:delivered.length?<div role="list" data-mark-list="uniform" aria-label="Delivered elements">{delivered.map((e,i)=>{const name=evidenceElementName(r,e.elementId,e.exposedName);return <div className="ichip" role="listitem" data-mark-row="true" data-row-kind="element" key={i}><Mark name={`treatment-${e.treatment==='aggregate_only'?'aggregate':e.treatment}` as MarkName} label={treatmentLabels[e.treatment??'']} size={17} treatmentColour="var(--ink-2)"/><span title={name.full}>{name.short}</span><span>{treatmentLabels[e.treatment??'']}</span></div>;})}</div>:<p className="note">No element deliveries were recorded.</p>}
 {omitted.length?<><h3>Recorded omissions</h3><div role="list" data-mark-list="uniform" aria-label="Recorded omissions">{omitted.map((e,i)=>{const name=evidenceElementName(r,e.elementId,e.exposedName);return <div className="ichip" role="listitem" data-mark-row="true" data-row-kind="element" key={i}><Mark name={e.state==='withheld'?'treatment-withheld':'treatment-undecided'} size={17} label={treatmentLabels[e.state]} treatmentColour="var(--ink-2)"/><span title={name.full}>{name.short}</span><span>{e.withheldReason??treatmentLabels[e.state]}</span></div>;})}</div></>:null}
 {r.detailCaptured===false?<p className="note">Source plan and stages were omitted by sampling. Recorded element deliveries remain available.</p>:null}
 </div></section></div>
 <div className="filters">
 {candidate?<Link className="btn" to="/projects/$projectId/$screen" params={{projectId,screen:'relationship-suggestions'}} search={{poolId:r.poolId,elementId:candidate.columns[0].elementId}}>Review as a suggestion</Link>:null}
 {!permalink?<Link className="btn ghost" to="/projects/$projectId/runs/$runId" params={{projectId,runId:r.id}} search={{startedAt:r.startedAt}}>Open evidence record</Link>:null}
 <Button variant="ghost" onClick={async()=>{try{await navigator.clipboard.writeText(r.id);state.notify('Record id copied.');}catch{state.notify('Copy failed. Select the record id below.');}}}>Copy record id</Button>
 <button className="toolchip" type="button" aria-expanded={state.extra} aria-controls={bodyId} onClick={state.toggle}>Full recorded metadata</button></div>
 <p className="mono" style={{overflowWrap:'anywhere',userSelect:'all'}}>Record {r.id}</p><p role="status">{state.notice}</p>
 <div id={bodyId} hidden={!state.extra} style={{overflowWrap:'anywhere'}}>{state.extra?<>

 {r.recordKind==='rollup'?<div className="seg"><h2 className="seglab">Rollup · summary only</h2><p className="joinbox">Full evidence was aged into this rollup {stamp(r.rolledUpAt)}. Treatment counts are summaries, not element-level delivery facts.</p><div className="interp">{Object.entries(r.treatmentCounts).map(([treatment,count])=><span className="ichip" key={treatment}><b>{treatment}</b><span className="mono">{count}</span></span>)}</div></div>:null}
 <div className="seg"><h2 className="seglab">Capture and stored redaction</h2><p className="note">Detail capture rate at open: {r.capturePercent}%. {r.detailCaptured===null?'Completion not recorded.':r.detailCaptured?(r.recordKind==='rollup'?'Detail was captured before retention.':'Detail captured.'):r.recordKind==='rollup'?'Detailed stages and source plan were omitted by sampling.':'Detailed stages and source plan omitted by sampling; element deliveries retained.'} Refusals and failures always retain detail.</p>{r.redactions.length?r.redactions.map((event,i)=><p className="note" key={i}>Stored arguments redacted {stamp(event.at)} under {event.policy.redaction}{event.policy.redaction==='allowlist'?` (${event.policy.allowlistedFields.join(', ')||'no allowed fields'})`:''}: {event.fields.join(', ')}.</p>):<p className="note">No stored argument redaction recorded.</p>}</div>
 {r.status==='incomplete'?<div className="seg"><p className="joinbox">Incomplete: the run opened but no completion was recorded. No answer was recorded.</p></div>:null}
 <div className="seg"><h2 className="seglab">Versions recorded at open</h2><div className="interp">{[['Policy version',r.versions.policy],['Catalogue generation',r.versions.catalog],['Vocabulary version',r.versions.vocabulary],['Token key selected',r.versions.tokenKeyVersionSelected??'None'],['Token key used',r.status==='incomplete'?'Unknown — incomplete':r.tokenKeyVersionUsed??'None']].map(([label,value])=><span className="ichip" key={label}><b>{label}</b><span className="mono">{value}</span></span>)}</div>{r.versions.tokenKeyVersionSelected!==null&&r.status!=='incomplete'&&r.tokenKeyVersionUsed===null?<p className="note">Selected but unused: no token was produced.</p>:null}</div>
 <div className="seg"><h2 className="seglab">Request {r.argumentVisibility==='literal_stripped'?'· literals stripped':r.argumentVisibility==='raw'?'as sent':'· redacted'}</h2><div className="qbox">{r.request??(r.recordKind==='rollup'?'Request arguments were removed by retention.':'Arguments are hidden by your permissions or the project’s evidence policy.')}</div></div>
 {r.generatedSql?<div className="seg"><h2 className="seglab">Generated SQL</h2><div className="qbox">{r.generatedSql}</div></div>:null}
 {r.versions.tokenKeyVersionSelected!==null?<div className="seg"><h2 className="seglab">Token declarations in force</h2>{r.tokenDeclarations===null?<p className="note">{r.recordKind==='rollup'?"Declaration detail was removed by retention. It cannot be reconstructed from today's catalogue.":"Declarations were not recorded for this answer. They cannot be reconstructed from today's catalogue."}</p>:!r.tokenDeclarations.length?<p className="note">No tokenized elements were in this plan.</p>:r.tokenDeclarations.map(t=><div className="joinbox" key={t.elementId}><b title={t.qualifiedName}>{shortPath(t.qualifiedName)}</b><p>Domain: {t.domain} · Assignment version: {t.domainVersion??'Not recorded'} · Canonicaliser: {t.canonId} · Mode: {t.mode} · Case folding: {t.caseInsensitive?'Enabled':'Disabled'}{t.sourceTimezone?` · Timezone: ${t.sourceTimezone}`:''}{t.epochUnit?` · Epoch: ${t.epochUnit}`:''}</p></div>)}</div>:null}
 <div className="seg"><h2 className="seglab">Elements recorded</h2>{!r.elements.length?<p className="joinbox">{r.recordKind==='rollup'?'Element-level facts were removed by retention; only the rollup counts remain.':`No element deliveries were recorded${r.status==='incomplete'?' before the run stopped':''}.`}</p>:<div role="region" aria-label="Element evidence" tabIndex={0} style={{overflowX:'auto'}}><table style={{minWidth:600}}><thead><tr><th>Element</th><th>State</th><th>Returned under</th><th>Reason</th></tr></thead><tbody>{r.elements.map((e,i)=><tr key={i}><td className="mono">{e.exposedName}{e.elementId?r.objects.filter(o=>o.columns.some(c=>c.elementId===e.elementId)).map(o=><div className="note" key={o.catalog+o.schema+o.name}>{o.catalog}.{o.schema}.{o.name}</div>):null}{e.elementId===null?<div className="note">Derived or unbound element</div>:null}</td><td style={{whiteSpace:'nowrap'}}>{e.state}</td><td>{e.treatment===null?'Nothing delivered':<Treatment kind={e.treatment==='aggregate_only'?'aggregate':e.treatment}/>}</td><td>{e.withheldReason??'—'}</td></tr>)}</tbody></table></div>}</div>
 <div className="seg"><h2 className="seglab">Sources reached</h2>{r.sources.length?r.sources.map(s=><div className="step" key={s.id}><div className="sb"><div className="sname" style={{overflowWrap:'anywhere'}}>{s.id}</div><div className="srows">{s.origin} · {s.freshnessMode}{s.landingStrategy?` · ${s.landingStrategy}`:''}<br/>Last introspected: {s.lastIntrospectedAt?stamp(s.lastIntrospectedAt):'Not recorded'}</div></div></div>):<p className="joinbox">{r.recordKind==='rollup'?'Source detail was removed by retention.':r.status==='incomplete'?'Source contact is not established.':'No source contact recorded.'}</p>}</div>
 <div className="seg"><h2 className="seglab">Returned to the agent</h2><div className="outbox"><div><div className="n mono">{r.rowCount??'—'}</div><div className="l">Rows</div></div><div><div className="n mono">{r.latencyMs===null?'—':`${r.latencyMs}ms`}</div><div className="l">Latency</div></div></div>{r.refusalCode?<p className="note">Refusal: {r.refusalCode}</p>:null}{r.truncated?<p className="note">The result was truncated.</p>:null}{r.synthetic?<p className="note">Synthetic: this run reached a demo source.</p>:null}</div>
 <div className="seg"><h2 className="seglab">Stages</h2>{r.stages.length?r.stages.map((s,i)=><p className="note" key={i}>{s.stage} · {s.result} · {s.ms}ms{s.code?` · ${s.code}`:''}</p>):<p className="note">{r.recordKind==='rollup'?'Stage detail was removed by retention.':'No stages recorded.'}</p>}</div>
 </>:null}</div></>;
}
