import {Mark} from '../../shared/ui/index.js';
import { AsyncButton } from '../../shared/ui/index.js';
import {Timestamp as DisplayTimestamp} from '../settings/preferences.js';
import {useMemo,useRef,type RefObject} from 'react';
import {useStore} from 'zustand';
import {useNavigate} from '@tanstack/react-router';
import {Button,EmptyState,ErrorState,LoadingState,Treatment} from '../../shared/ui/index.js';
import {ActivityStatus,type ActivityEntry,type ActivityFilters} from '../../shared/api/activity.js';
import {usePools} from '../entitlements/data.js';
import {useActivity,useEvidence} from './data.js';
import {createActivityState,activityRowHeight as height,activityWindowSize as windowSize} from './state.js';
const stamp=(value:string|null)=>value===null?'Never':<DisplayTimestamp value={value} appearance="rwhen"/>;
function Outcome({status}:{status:ActivityEntry['status']}){return <span className={status==='answered'?'tr clear':status==='failed'?'tr held':'tr ref'}>{status==='refused'?<Mark name="refused"/>:status==='incomplete'?<Mark name="incomplete"/>:null}{status}</span>;}
export function ActivityScreen({projectId,filters,onFilters}:{projectId:string;filters:ActivityFilters;onFilters:(filters:ActivityFilters)=>void}){
 const query=useActivity(projectId,filters),pools=usePools(projectId);const store=useMemo(createActivityState,[projectId]);const state=store.getState();const viewport=useRef<HTMLDivElement>(null);
 const items=useMemo(()=>query.data?.pages.flatMap(p=>p.items)??[],[query.data]);
 function change(key:keyof ActivityFilters,value:string){onFilters({...filters,[key]:value||undefined});state.scroll(0);if(viewport.current)viewport.current.scrollTop=0;}
 return <section className="screen on"><h1>Activity</h1><p className="sub">Every request, what it read, and what the agent received. Each record preserves the decisions in force at the time.</p>
 <div className="filters">
 <span className="pick"><label htmlFor="activity-mode">Mode</label><select id="activity-mode" value={filters.mode??''} onChange={e=>change('mode',e.target.value)}><option value="">All modes</option><option value="query">Queries</option><option value="prompt">Prompts</option></select></span>
 <span className="pick"><label htmlFor="activity-pool">Pool</label><select id="activity-pool" value={filters.poolId??''} onChange={e=>change('poolId',e.target.value)}><option value="">All pools</option>{pools.data?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></span>
 <span className="pick"><label htmlFor="activity-outcome">Outcome</label><select id="activity-outcome" value={filters.outcome??''} onChange={e=>change('outcome',e.target.value)}><option value="">All outcomes</option>{ActivityStatus.options.map(o=><option key={o} value={o}>{o}</option>)}</select></span>
 <div className="fld" style={{marginBottom:0,maxWidth:'100%'}}><label htmlFor="activity-agent">Agent ID (self-declared)</label><input id="activity-agent" value={filters.agentId??''} onChange={e=>change('agentId',e.target.value)} maxLength={200}/></div>
 {(['from','to'] as const).map(key=><div className="fld" style={{marginBottom:0,maxWidth:'100%'}} key={key}><label htmlFor={'activity-'+key}>{key==='from'?'From (UTC)':'Before (UTC)'}</label><input id={'activity-'+key} type="datetime-local" value={filters[key]?.slice(0,16)??''} onChange={e=>change(key,e.target.value?new Date(e.target.value+'Z').toISOString():'')}/></div>)}
 <Button variant="ghost" onClick={()=>{onFilters({});state.scroll(0);}}>Clear filters</Button><AsyncButton variant="ghost" pendingLabel="Refreshing…" refusal={query.isError?query.error.message:null} run={()=>query.refetch()}>Refresh</AsyncButton>
 </div>{pools.isError?<p role="alert">{pools.error.message}</p>:null}
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Activity could not be loaded" description="Retry to load the records." retry={()=>query.refetch()}/>:!items.length?<EmptyState title="No requests match" description="Clear the filters or send a request through a pool to create an evidence record."/>:<ActivityRecords projectId={projectId} items={items} query={query} store={store} viewport={viewport}/>}</section>;
}
function ActivityRecords({projectId,items,query,store,viewport}:{projectId:string;items:ActivityEntry[];query:ReturnType<typeof useActivity>;store:ReturnType<typeof createActivityState>;viewport:RefObject<HTMLDivElement|null>}){
 const state=useStore(store),navigate=useNavigate();
 const start=Math.max(0,Math.min(Math.floor(state.top/height)-2,items.length-1)),visible=items.slice(start,start+windowSize);
 return <div className="card"><div className="card-h"><h2>Requests</h2><span className="meta">Newest first</span></div>
 <div ref={viewport} role="region" aria-label="Activity records" tabIndex={0} onKeyDown={e=>{if(e.target!==e.currentTarget)return;const delta=e.key==='PageDown'?e.currentTarget.clientHeight:e.key==='PageUp'?-e.currentTarget.clientHeight:e.key==='ArrowDown'?height:e.key==='ArrowUp'?-height:0;if(delta){e.preventDefault();e.currentTarget.scrollTop+=delta;}else if(e.key==='Home'||e.key==='End'){e.preventDefault();e.currentTarget.scrollTop=e.key==='Home'?0:e.currentTarget.scrollHeight;}}} style={{height:Math.min(items.length,5)*height,overflow:'auto',contain:'layout paint'}} onScroll={e=>{state.scroll(e.currentTarget.scrollTop);if(e.currentTarget.scrollTop+e.currentTarget.clientHeight>=e.currentTarget.scrollHeight-height&&query.hasNextPage&&!query.isFetchingNextPage)void query.fetchNextPage();}}>
 <div role="list" data-mark-list="uniform" style={{height:items.length*height,position:'relative'}}>{visible.map((r,i)=><div className="rec" role="listitem" data-mark-row="true" data-row-kind={r.mode} aria-posinset={start+i+1} aria-setsize={query.hasNextPage?-1:items.length} key={r.id+r.startedAt} style={{position:'absolute',top:(start+i)*height,height,width:'100%',overflow:'hidden'}}><div className="rhead" style={{height:'100%',alignItems:'center'}}><div className="rbody" style={{minWidth:0}}><a className={r.mode==='query'?'rtext q':'rtext'} href={`/projects/${projectId}/runs/${r.id}?${new URLSearchParams({startedAt:r.startedAt})}`} onClick={e=>{if(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey)return;e.preventDefault();void navigate({to:"/projects/$projectId/runs/$runId",params:{projectId,runId:r.id},search:{startedAt:r.startedAt}});}} style={{display:'block',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',color:'var(--ink)'}}>{r.recordKind==='rollup'?'Rollup · summary only':r.request??`${r.mode==='query'?'Query':'Prompt'} · arguments redacted`}</a><div className="rmeta"><Outcome status={r.status}/><span>{r.mode}</span>{r.capturePercent<100?<span>{r.capturePercent}% detail capture</span>:null}<span>{r.agentId??'No agent ID'} · {r.keyPrefix}</span>{r.synthetic?<span>Synthetic demo</span>:null}</div><div className="rmeta" style={{overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{stamp(r.startedAt)} · {r.rowCount===null?'No answer recorded':`${r.rowCount} rows`}</div></div></div></div>)}</div></div>
 {query.hasNextPage?<AsyncButton variant="ghost" disabled={query.isFetchingNextPage} pendingLabel="Loading…" refusal={query.isError?query.error.message:null} run={()=>query.fetchNextPage()}>Load more requests</AsyncButton>:null}</div>;
}
export function RecordScreen({projectId,runId,startedAt}:{projectId:string;runId:string;startedAt:string}){
 const query=useEvidence(projectId,runId,startedAt),r=query.data;
 return <section className="screen on"><h1>Run record</h1><p className="sub">Historical evidence of what this request read and returned.</p>
 {query.isPending?<LoadingState/>:query.isError&&query.error.code==='not_found'?<EmptyState title="Record not found" description={query.error.message+' Select another request in Activity. An incomplete run still has a record.'}/>:query.isError?<ErrorState title="Record could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:!r?<EmptyState title="No record" description="Select a request in Activity."/>:<article className="rec open"><div className="rhead"><div className="rbody" style={{minWidth:0}}><Outcome status={r.status}/><p className="note" style={{overflowWrap:'anywhere'}}>Run {r.id}<br/>{stamp(r.startedAt)}<br/>Pool {r.poolId}<br/>Agent {r.agentId??'not supplied'} (self-declared)</p></div></div><div className="rdetail" style={{overflowWrap:'anywhere'}}>
 {r.recordKind==='rollup'?<div className="seg"><h2 className="seglab">Rollup · summary only</h2><p className="joinbox">Full evidence was aged into this rollup {stamp(r.rolledUpAt)}. Treatment counts are summaries, not element-level delivery facts.</p><div className="interp">{Object.entries(r.treatmentCounts).map(([treatment,count])=><span className="ichip" key={treatment}><b>{treatment}</b><span className="mono">{count}</span></span>)}</div></div>:null}
 <div className="seg"><h2 className="seglab">Capture and stored redaction</h2><p className="note">Detail capture rate at open: {r.capturePercent}%. {r.detailCaptured===null?'Completion not recorded.':r.detailCaptured?(r.recordKind==='rollup'?'Detail was captured before retention.':'Detail captured.'):r.recordKind==='rollup'?'Detailed stages and source plan were omitted by sampling.':'Detailed stages and source plan omitted by sampling; element deliveries retained.'} Refusals and failures always retain detail.</p>{r.redactions.length?r.redactions.map((event,i)=><p className="note" key={i}>Stored arguments redacted {stamp(event.at)} under {event.policy.redaction}{event.policy.redaction==='allowlist'?` (${event.policy.allowlistedFields.join(', ')||'no allowed fields'})`:''}: {event.fields.join(', ')}.</p>):<p className="note">No stored argument redaction recorded.</p>}</div>
 {r.status==='incomplete'?<div className="seg"><p className="joinbox">Incomplete: the run opened but no completion was recorded. An answer is not established.</p></div>:null}
 <div className="seg"><h2 className="seglab">Versions recorded at open</h2><div className="interp">{[['Policy version',r.versions.policy],['Catalogue generation',r.versions.catalog],['Vocabulary version',r.versions.vocabulary],['Token key selected',r.versions.tokenKeyVersionSelected??'None'],['Token key used',r.status==='incomplete'?'Unknown — incomplete':r.tokenKeyVersionUsed??'None']].map(([label,value])=><span className="ichip" key={label}><b>{label}</b><span className="mono">{value}</span></span>)}</div>{r.versions.tokenKeyVersionSelected!==null&&r.status!=='incomplete'&&r.tokenKeyVersionUsed===null?<p className="note">Selected but unused: no token was produced.</p>:null}</div>
 <div className="seg"><h2 className="seglab">Request {r.argumentVisibility==='literal_stripped'?'· literals stripped':r.argumentVisibility==='raw'?'as sent':'· redacted'}</h2><div className="qbox">{r.request??(r.recordKind==='rollup'?'Request arguments were removed by retention.':'Arguments are hidden by your permissions or the project’s evidence policy.')}</div></div>
 {r.generatedSql?<div className="seg"><h2 className="seglab">Generated SQL</h2><div className="qbox">{r.generatedSql}</div></div>:null}
 {r.versions.tokenKeyVersionSelected!==null?<div className="seg"><h2 className="seglab">Token declarations in force</h2>{r.tokenDeclarations===null?<p className="note">{r.recordKind==='rollup'?"Declaration detail was removed by retention. It cannot be reconstructed from today's catalogue.":"Declarations were not recorded for this answer. They cannot be reconstructed from today's catalogue."}</p>:!r.tokenDeclarations.length?<p className="note">No tokenized elements were in this plan.</p>:r.tokenDeclarations.map(t=><div className="joinbox" key={t.elementId}><b>{t.qualifiedName}</b><p>Domain: {t.domain} · Assignment version: {t.domainVersion??'Not recorded'} · Canonicaliser: {t.canonId} · Mode: {t.mode} · Case folding: {t.caseInsensitive?'Enabled':'Disabled'}{t.sourceTimezone?` · Timezone: ${t.sourceTimezone}`:''}{t.epochUnit?` · Epoch: ${t.epochUnit}`:''}</p></div>)}</div>:null}
 <div className="seg"><h2 className="seglab">Elements recorded</h2>{!r.elements.length?<p className="joinbox">{r.recordKind==='rollup'?'Element-level facts were removed by retention; only the rollup counts remain.':`No element deliveries were recorded${r.status==='incomplete'?' before the run stopped':''}.`}</p>:<div role="region" aria-label="Element evidence" tabIndex={0} style={{overflowX:'auto'}}><table style={{minWidth:600}}><thead><tr><th>Element</th><th>State</th><th>Returned under</th><th>Reason</th></tr></thead><tbody>{r.elements.map((e,i)=><tr key={i}><td className="mono">{e.exposedName}{e.elementId?r.objects.filter(o=>o.columns.some(c=>c.elementId===e.elementId)).map(o=><div className="note" key={o.catalog+o.schema+o.name}>{o.catalog}.{o.schema}.{o.name}</div>):null}{e.elementId===null?<div className="note">Derived or unbound element</div>:null}</td><td style={{whiteSpace:'nowrap'}}>{e.state}</td><td>{e.treatment===null?'Nothing delivered':<Treatment kind={e.treatment==='aggregate_only'?'aggregate':e.treatment}/>}</td><td>{e.withheldReason??'—'}</td></tr>)}</tbody></table></div>}</div>
 <div className="seg"><h2 className="seglab">Sources reached</h2>{r.sources.length?r.sources.map(s=><div className="step" key={s.id}><div className="sb"><div className="sname" style={{overflowWrap:'anywhere'}}>{s.id}</div><div className="srows">{s.origin} · {s.freshnessMode}{s.landingStrategy?` · ${s.landingStrategy}`:''}<br/>Last introspected: {s.lastIntrospectedAt?stamp(s.lastIntrospectedAt):'Not recorded'}</div></div></div>):<p className="joinbox">{r.recordKind==='rollup'?'Source detail was removed by retention.':r.status==='incomplete'?'Source contact is not established.':'No source contact recorded.'}</p>}</div>
 <div className="seg"><h2 className="seglab">Returned to the agent</h2><div className="outbox"><div><div className="n mono">{r.rowCount??'—'}</div><div className="l">Rows</div></div><div><div className="n mono">{r.latencyMs===null?'—':`${r.latencyMs}ms`}</div><div className="l">Latency</div></div></div>{r.refusalCode?<p className="note">Refusal: {r.refusalCode}</p>:null}{r.truncated?<p className="note">The result was truncated.</p>:null}{r.synthetic?<p className="note">Synthetic: this run reached a demo source.</p>:null}</div>
 <div className="seg"><h2 className="seglab">Stages</h2>{r.stages.length?r.stages.map((s,i)=><p className="note" key={i}>{s.stage} · {s.result} · {s.ms}ms{s.code?` · ${s.code}`:''}</p>):<p className="note">{r.recordKind==='rollup'?'Stage detail was removed by retention.':'No stages recorded.'}</p>}</div>
 </div></article>}</section>;
}
