import {useEffect,useMemo,useRef,type PropsWithChildren,type RefObject} from 'react';
import {useStore} from 'zustand';
import {AsyncButton,Button,EmptyState,ErrorState,InlineExpansion,LoadingState,Mark,SegmentedFilters} from '../../shared/ui/index.js';
import {ActivityStatus,ActivityFilters,type ActivityEntry,type ActivitySummary} from '../../shared/api/activity.js';
import {Timestamp} from '../settings/preferences.js';
import {usePools} from '../entitlements/data.js';
import {useActivity,useActivitySummary,useEvidence} from './data.js';
import {createActivityState,activityWindowSize} from './state.js';
import {AnswerTreatments,EvidenceDetails} from './detail.js';
import {requestLabel} from './presentation.js';
const filterDefinition='Completed answers with recorded tokenized, masked or aggregate-only deliveries. Excludes planned reads, omissions, refusals and incomplete requests.';
type Tab='all'|'refused'|'incomplete'|'answerTreated';
function Outcome({r}:{r:ActivityEntry}){return <span className={r.status==='answered'||r.status==='reduced'?'tr clear':r.status==='incomplete'?'tr wait':'tr ref'} data-part="outcome">{r.status==='refused'?<Mark name="refused"/>:r.status==='incomplete'?<Mark name="incomplete"/>:null}{r.status==='answered'||r.status==='reduced'?`${r.rowCount??'—'} ${r.rowCount===1?'row':'rows'}`:r.status==='incomplete'?'Incomplete':r.status==='refused'?'Refused':r.status==='failed'?'Failed':'Clarification'}</span>;}
function Chevron(){return <svg data-part="picker-chevron" viewBox="0 0 10 6" aria-hidden="true" focusable="false"><path d="m1 1 4 4 4-4" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg>;}
export function ActivityScreen({projectId,filters,onFilters}:{projectId:string;filters:ActivityFilters;onFilters:(filters:ActivityFilters)=>void}){
 const query=useActivity(projectId,filters),summary=useActivitySummary(projectId,filters),pools=usePools(projectId);
 const store=useMemo(createActivityState,[projectId]),viewport=useRef<HTMLDivElement>(null);
 const items=useMemo(()=>query.data?.pages.flatMap(p=>p.items)??[],[query.data]);
 const tab:Tab=filters.answerTreated==='true'?'answerTreated':filters.outcome==='refused'?'refused':filters.outcome==='incomplete'?'incomplete':'all';
 function apply(next:ActivityFilters){onFilters(next);store.getState().scroll(0);if(viewport.current)viewport.current.scrollTop=0;}
 function change(key:keyof ActivityFilters,value:string){apply(ActivityFilters.parse({...filters,[key]:value||undefined}));}
 function changeTab(value:Tab){apply({...filters,outcome:value==='refused'||value==='incomplete'?value:undefined,answerTreated:value==='answerTreated'?'true':undefined});}
 const now=new Date(),range=filters.from?String(Math.max(1,Math.ceil((now.getTime()-Date.parse(filters.from))/86400000))):'all';
 return <section className="screen on" data-layout="activity"><h1>Activity</h1><p className="sub">Every request, what it read, and what the agent received. Each record keeps the decisions in force at the time.</p>
 <div className="filters" data-part="activity-toolbar">
 <SegmentedFilters label="Activity outcome" value={tab} options={[{value:'all',label:'All',count:summary.data?.counts.all},{value:'refused',label:'Refused',count:summary.data?.counts.refused},{value:'incomplete',label:'Incomplete',count:summary.data?.counts.incomplete},{value:'answerTreated',label:'Answer treated',count:summary.data?.counts.answerTreated}]} onChange={changeTab}/>
 <span className="pick"><label htmlFor="activity-agent">Agent</label><input className="inp" id="activity-agent" aria-label="Agent ID (self-declared)" size={12} value={filters.agentId??''} onChange={e=>change('agentId',e.target.value)} maxLength={200} placeholder="Any"/></span>
 <span className="pick"><label htmlFor="activity-pool">Pool</label><select id="activity-pool" value={filters.poolId??''} onChange={e=>change('poolId',e.target.value)}><option value="">Any</option>{pools.data?.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><Chevron/></span>
 <span className="pick"><label htmlFor="activity-range">Last</label><select id="activity-range" value={['1','7','30','all'].includes(range)?range:'custom'} onChange={e=>{const days=e.target.value;apply({...filters,from:days==='all'?undefined:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),now.getUTCDate()-Number(days)+1)).toISOString(),to:undefined});}}><option value="all">All time</option><option value="1">Today (UTC)</option><option value="7">7 days</option><option value="30">30 days</option>{range==='custom'||!['1','7','30','all'].includes(range)?<option value="custom">Custom range</option>:null}</select><Chevron/></span>
 <input className="inp" type="search" aria-label="Filter by object or element" value={filters.search??''} onChange={e=>change('search',e.target.value)} maxLength={200} placeholder="Object or element…"/>
 </div>
 <div className="filters"><span className="note" title={filterDefinition}>Answer treated: recorded tokenized, masked or aggregate-only deliveries.</span><Button variant="ghost" onClick={()=>apply({})}>Clear filters</Button><AsyncButton variant="ghost" pendingLabel="Refreshing…" refusal={null} run={async()=>{await query.refetch();await summary.refetch();}}>Refresh</AsyncButton></div>
 {pools.isError?<p role="alert">{pools.error.message}</p>:null}{summary.isError?<p role="alert">Day summaries could not be loaded: {summary.error.message}</p>:null}
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Activity could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:!items.length?<EmptyState title="No requests match" description="Clear the filters or send a request through a pool to create an evidence record."/>:<ActivityRecords projectId={projectId} items={items} query={query} summary={summary.data} store={store} viewport={viewport} pools={pools.data}/>}
 </section>;
}
type TimelineItem={key:string;record:ActivityEntry}|{key:string;day:string};
function Measured({id,store,children}:PropsWithChildren<{id:string;store:ReturnType<typeof createActivityState>}>){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const el=ref.current;if(!el)return;let frame=0;const observer=new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>store.getState().measure(id,Math.ceil(el.getBoundingClientRect().height)));});observer.observe(el);return()=>{observer.disconnect();cancelAnimationFrame(frame);};},[id,store]);
 return <div ref={ref}>{children}</div>;
}
function DayStrip({day,summary}:{day:string;summary?:ActivitySummary}){
 const data=summary?.days.find(d=>d.day===day);
 return <header className="card-h" data-part="day"><b>{day}</b><span className="meta">{data?`${data.counts.all} requests · ${data.counts.refused} refused · ${data.counts.incomplete} incomplete`:'Day totals unavailable'}</span>{data?<span data-part="day-outcomes" tabIndex={0} role="img" aria-label={ActivityStatus.options.map(status=>`${data.outcomes[status]} ${status}`).join(', ')}><svg width={data.counts.all*9} height="6" aria-hidden="true" focusable="false" data-request-count={data.counts.all}><defs>{ActivityStatus.options.map(status=><pattern key={status} id={`day-${day}-${status}`} width="9" height="6" patternUnits="userSpaceOnUse"><circle cx="3" cy="3" r="3" className={status==='answered'||status==='reduced'?'tr clear':status==='incomplete'?'tr wait':'tr ref'} fill={status==='incomplete'?'var(--yellow-br)':'currentColor'}/></pattern>)}</defs>{ActivityStatus.options.map((status,index)=><rect key={status} data-outcome={status} data-count={data.outcomes[status]} x={ActivityStatus.options.slice(0,index).reduce((total,previous)=>total+data.outcomes[previous],0)*9} width={data.outcomes[status]*9} height="6" fill={`url(#day-${day}-${status})`}/>)}</svg></span>:null}</header>;
}
function ActivityRecords({projectId,items,query,summary,store,viewport,pools}:{projectId:string;items:ActivityEntry[];query:ReturnType<typeof useActivity>;summary?:ActivitySummary;store:ReturnType<typeof createActivityState>;viewport:RefObject<HTMLDivElement|null>;pools?:Array<{id:string;name:string}>}){
 const state=useStore(store);
 useEffect(()=>{const el=viewport.current;if(!el)return;let frame=0;const observer=new ResizeObserver(()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>store.getState().resize(el.clientWidth));});observer.observe(el);return()=>{observer.disconnect();cancelAnimationFrame(frame);};},[store,viewport]);
 const timeline=useMemo(()=>{const result:TimelineItem[]=[];let previous='';for(const record of items){const day=record.startedAt.slice(0,10);if(day!==previous){result.push({key:'day-'+day,day});previous=day;}result.push({key:record.id+'@'+record.startedAt,record});}return result;},[items]);
 const offsets=useMemo(()=>{let top=0;return timeline.map(item=>{const position=top;top+=state.heights[item.key]??('day' in item?52:(state.width<=820?210:58)+(state.expanded.has(item.key)?520:0));return {item,top:position,bottom:top};});},[timeline,state.heights,state.width,state.expanded]);
 let index=offsets.findIndex(item=>item.bottom>state.top);if(index<0)index=Math.max(0,offsets.length-1);
 const start=Math.max(0,index-1),visible=offsets.slice(start,start+activityWindowSize),total=offsets.at(-1)?.bottom??0;
 return <div className="card"><div className="card-h"><h2>Requests</h2><span className="meta">Newest first · Days grouped in UTC</span></div>
 <div ref={viewport} role="region" aria-label="Activity records" data-loaded-records={items.length} tabIndex={0} style={{height:520,overflow:'auto',contain:'layout paint'}} onKeyDown={e=>{if(e.target!==e.currentTarget)return;const delta=e.key==='PageDown'?e.currentTarget.clientHeight:e.key==='PageUp'?-e.currentTarget.clientHeight:e.key==='ArrowDown'?42:e.key==='ArrowUp'?-42:0;if(delta){e.preventDefault();e.currentTarget.scrollTop+=delta;}else if(e.key==='Home'||e.key==='End'){e.preventDefault();e.currentTarget.scrollTop=e.key==='Home'?0:e.currentTarget.scrollHeight;}}} onScroll={e=>{state.scroll(e.currentTarget.scrollTop);if(e.currentTarget.scrollTop+e.currentTarget.clientHeight>=e.currentTarget.scrollHeight-200&&query.hasNextPage&&!query.isFetchingNextPage)void query.fetchNextPage();}}>
 <div role="list" data-mark-list="uniform" style={{height:total,position:'relative'}}>{visible.map(({item,top})=><div key={item.key} role={'day' in item?'listitem':undefined} data-row-kind={'day' in item?'day':undefined} style={{position:'absolute',top,width:'100%'}}><Measured id={item.key} store={store}>{'day' in item?<DayStrip day={item.day} summary={summary}/>:<InlineExpansion kind={item.record.mode} id={`record-${item.record.id}`} open={state.expanded.has(item.key)} onToggle={()=>state.toggle(item.key)} label={state.expanded.has(item.key)?'Hide':'Details'} leading={<Outcome r={item.record}/>} identity={<><b title={requestLabel(item.record)}>{requestLabel(item.record)}</b><p title={item.record.metadata.objects?.map(o=>`${o.catalog}.${o.schema}.${o.name}`).join(' · ')}>{item.record.status==='incomplete'?'No answer was recorded':item.record.metadata.objects?.map(o=>o.name).join(' · ')||'Object detail not recorded'}{item.record.capturePercent<100?` · ${item.record.capturePercent}% detail capture`:''}</p></>} secondary={<AnswerTreatments counts={item.record.metadata.delivered}/>} metadata={<p className="rtext q" title={`Agent ID (self-declared): ${item.record.agentId??'not supplied'}; pool ${pools?.find(p=>p.id===item.record.poolId)?.name??'name unavailable'} (${item.record.poolId})`}><b>{item.record.agentId??'No agent ID'}</b>{pools?.length===1&&pools[0]?.id===item.record.poolId?null:<><br/><span data-part="pool-name">{pools?.find(p=>p.id===item.record.poolId)?.name??'Pool name unavailable'}</span></>}</p>} timestamp={<div data-part="timestamp"><Timestamp value={item.record.startedAt} appearance="rwhen"/></div>}><InlineEvidence projectId={projectId} r={item.record}/></InlineExpansion>}</Measured></div>)}</div></div>
 {query.hasNextPage?<AsyncButton variant="ghost" disabled={query.isFetchingNextPage} pendingLabel="Loading…" refusal={query.isError?query.error.message:null} run={()=>query.fetchNextPage()}>Load more requests</AsyncButton>:null}</div>;
}
function InlineEvidence({projectId,r}:{projectId:string;r:ActivityEntry}){
 const query=useEvidence(projectId,r.id,r.startedAt);
 return query.isPending?<LoadingState/>:query.isError?<ErrorState title="Record could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:query.data?<EvidenceDetails r={query.data} projectId={projectId}/>:null;
}
export function RecordScreen({projectId,runId,startedAt}:{projectId:string;runId:string;startedAt:string}){
 const query=useEvidence(projectId,runId,startedAt),r=query.data;
 return <section className="screen on" data-layout="activity"><h1>Run record</h1><p className="sub">Historical evidence of what this request read and returned.</p>{query.isPending?<LoadingState/>:query.isError&&query.error.code==='not_found'?<EmptyState title="Record not found" description={query.error.message+' Select another request in Activity. An incomplete run still has a record.'}/>:query.isError?<ErrorState title="Record could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:r?<article className="rec open"><div className="rdetail"><EvidenceDetails r={r} projectId={projectId} permalink/></div></article>:<EmptyState title="No record" description="Select a request in Activity."/>}</section>;
}
