import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { createApiClient,type AppError } from '../../shared/api/index.js';
import { PoolChoices,readEntitlements,ViewDefinitionResponse,type EntitlementFilter } from '../../shared/api/entitlement-read.js';
import { bulkSetEntitlements,type BulkEntitlementBody,type BulkEntitlementResponse } from '../../shared/api/bulk-entitlements.js';
import { projectKeys } from '../tenancy/data.js';
import { elementKeys } from '../catalog/data.js';
export const poolKeys={lists:(project:string)=>[...projectKeys.scope(project),'pool','list'] as const};
export const entitlementKeys={all:(project:string)=>[...projectKeys.scope(project),'entitlement'] as const,list:(project:string,pool:string,filter:EntitlementFilter)=>[...entitlementKeys.all(project),pool,'list',filter] as const,definition:(project:string,pool:string)=>[...entitlementKeys.all(project),pool,'definition'] as const};
export function usePools(project:string){return useQuery<z.infer<typeof PoolChoices>['items'],AppError>({queryKey:poolKeys.lists(project),staleTime:60_000,retry:false,queryFn:async()=>{const items:z.infer<typeof PoolChoices>['items']=[];let cursor:string|null=null;do{const result:{ok:true;value:z.infer<typeof PoolChoices>}|{ok:false;error:AppError}=await createApiClient().request({path:`/api/v1/projects/${project}/pools${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`,response:PoolChoices});if(!result.ok)throw result.error;items.push(...result.value.items);cursor=result.value.nextCursor;}while(cursor);return items;}});}
export function entitlementOptions(project:string,pool:string,filter:EntitlementFilter){return {queryKey:entitlementKeys.list(project,pool,filter),retry:false as const,staleTime:60_000,queryFn:async()=>{const result=await readEntitlements(project,pool,filter);if(!result.ok)throw result.error;return result.value;}};}
export function useDefinition(project:string,pool:string,enabled:boolean){return useQuery<z.infer<typeof ViewDefinitionResponse>,AppError>({queryKey:entitlementKeys.definition(project,pool),enabled,staleTime:60_000,retry:false,queryFn:async()=>{const result=await createApiClient().request({path:`/api/v1/pools/${pool}/view-definition?projectId=${project}`,response:ViewDefinitionResponse});if(!result.ok)throw result.error;return result.value;}});}
export function useBulk(project:string,pool:string){const cache=useQueryClient();return useMutation<BulkEntitlementResponse,AppError,{body:BulkEntitlementBody;key:string}>({mutationFn:async({body,key})=>{const result=await bulkSetEntitlements(pool,body,key);if(!result.ok)throw result.error;return result.value;},onSuccess:async()=>{await Promise.all([entitlementKeys.all(project),poolKeys.lists(project),elementKeys.lists(project),projectKeys.stats(project)].map(queryKey=>cache.invalidateQueries({queryKey})));}});}
