import {useInfiniteQuery} from '@tanstack/react-query';
import {readGroups,readMembers,type GroupFilter,type MemberFilter} from '../../shared/api/entitlement-groups.js';
import {poolKeys} from '../pools/keys.js';
import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { z } from 'zod';
import { createApiClient,type AppError } from '../../shared/api/index.js';
import { PoolChoices,readEntitlements,type EntitlementFilter } from '../../shared/api/entitlement-read.js';
import { bulkSetEntitlements,type BulkEntitlementBody,type BulkEntitlementResponse } from '../../shared/api/bulk-entitlements.js';
import { projectKeys } from '../tenancy/data.js';
import { elementKeys } from '../catalog/data.js';
export {poolKeys} from '../pools/keys.js';
export const entitlementKeys={all:(project:string)=>[...projectKeys.scope(project),'entitlement'] as const,list:(project:string,pool:string,filter:EntitlementFilter)=>[...entitlementKeys.all(project),pool,'list',filter] as const,groups:(project:string,pool:string,filter:GroupFilter)=>[...entitlementKeys.all(project),pool,'groups',filter] as const,members:(project:string,pool:string,filter:MemberFilter)=>[...entitlementKeys.all(project),pool,'members',filter] as const,definition:(project:string,pool:string)=>[...entitlementKeys.all(project),pool,'definition'] as const};
export function usePools(project:string){return useQuery<z.infer<typeof PoolChoices>['items'],AppError>({queryKey:poolKeys.lists(project),staleTime:60_000,retry:false,queryFn:async()=>{const items:z.infer<typeof PoolChoices>['items']=[];let cursor:string|null=null;do{const result:{ok:true;value:z.infer<typeof PoolChoices>}|{ok:false;error:AppError}=await createApiClient().request({path:`/api/v1/projects/${project}/pools${cursor?`?cursor=${encodeURIComponent(cursor)}`:''}`,response:PoolChoices});if(!result.ok)throw result.error;items.push(...result.value.items);cursor=result.value.nextCursor;}while(cursor);return items;}});}
export function entitlementOptions(project:string,pool:string,filter:EntitlementFilter){return {queryKey:entitlementKeys.list(project,pool,filter),retry:false as const,staleTime:60_000,queryFn:async()=>{const result=await readEntitlements(project,pool,filter);if(!result.ok)throw result.error;return result.value;}};}
export function useBulk(project:string,pool:string){const cache=useQueryClient();return useMutation<BulkEntitlementResponse,AppError,{body:BulkEntitlementBody;key:string}>({mutationFn:async({body,key})=>{const result=await bulkSetEntitlements(pool,body,key);if(!result.ok)throw result.error;return result.value;},onSuccess:async()=>{await Promise.all([entitlementKeys.all(project),poolKeys.lists(project),elementKeys.lists(project),elementKeys.declarations(project),projectKeys.stats(project)].map(queryKey=>cache.invalidateQueries({queryKey})));}});}

export function useGroups(pool:string,filter:GroupFilter){return useInfiniteQuery({queryKey:entitlementKeys.groups(filter.projectId,pool,filter),initialPageParam:undefined as string|undefined,retry:false,staleTime:60_000,queryFn:async({pageParam})=>{const result=await readGroups(pool,{...filter,cursor:pageParam});if(!result.ok)throw result.error;return result.value;},getNextPageParam:page=>page.nextCursor??undefined});}
export function useMembers(pool:string,filter:MemberFilter){return useInfiniteQuery({queryKey:entitlementKeys.members(filter.projectId,pool,filter),initialPageParam:undefined as string|undefined,retry:false,staleTime:60_000,queryFn:async({pageParam})=>{const result=await readMembers(pool,{...filter,cursor:pageParam});if(!result.ok)throw result.error;return result.value;},getNextPageParam:page=>page.nextCursor??undefined});}
