import {test} from './fixtures.js';
import {expect,type Page} from '@playwright/test';
import axe from 'axe-core';
import {mockActivity,activityPath,detailPath,entry,project,pool,id} from './activity-fixture.js';
async function accessible(page:Page){await page.addScriptTag({content:axe.source});expect(await page.evaluate(async()=>(await axe.run()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test.use({reducedMotion:'reduce'});
for(const width of [390,900,1440])test(`RED-015/018: measured Activity and bounded inline evidence at ${width}`,async({page},testInfo)=>{
 await page.clock.setFixedTime(new Date('2026-10-06T15:43:00Z'));const state=await mockActivity(page);await page.setViewportSize({width,height:1000});await page.goto(activityPath);
 const region=page.getByRole('region',{name:'Activity records'}),row=region.locator('.rec').first();
 await expect(row.getByText('Read 1 object',{exact:true})).toBeVisible();await expect(row.getByText('treaties',{exact:true})).toBeVisible();await expect(row.locator('[data-mark-category=kind]')).toHaveCount(0);await expect(row.locator('[data-part=identity] > b')).toHaveCSS('font-size','13.5px');await expect(row.locator('[data-part=identity] > b')).toHaveCSS('font-weight','560');
 await expect(row.getByRole('img',{name:'Tokenized',exact:true})).toBeVisible();expect(state.detailRequests).toHaveLength(0);
 const measurements=await row.evaluate(el=>{const header=el.querySelector('.rhead')!,label=el.querySelector('[data-part=identity] > b')!,toolbar=document.querySelector('[data-part=activity-toolbar]')!;return {row:header.getBoundingClientRect().height,cells:[...header.children].map(c=>({part:c.getAttribute("data-part"),height:c.getBoundingClientRect().height,lineHeight:getComputedStyle(c).lineHeight})),labelSize:getComputedStyle(label).fontSize,labelWeight:getComputedStyle(label).fontWeight,toolbar:toolbar.getBoundingClientRect().height,day:document.querySelector('[data-part=day]')?.getBoundingClientRect().height,pickers:[...toolbar.querySelectorAll('.pick')].map(p=>({width:p.getBoundingClientRect().width,chevronClearance:p.querySelector('[data-part=picker-chevron]')?p.getBoundingClientRect().right-p.querySelector('[data-part=picker-chevron]')!.getBoundingClientRect().right:null}))};});
 await row.getByRole('button',{name:'Details',exact:true}).click();await expect(row.getByRole('heading',{name:'What the answer contained',exact:true})).toBeVisible();await expect(row.getByRole('list',{name:'Delivered elements'})).toContainText('treaties.treaty_ref');await expect(row.getByRole('heading',{name:'Recorded omissions',exact:true})).toHaveCount(0);
 const pair=await row.locator('.scopepick').evaluate(el=>({width:el.getBoundingClientRect().width,columns:getComputedStyle(el).gridTemplateColumns,gap:getComputedStyle(el).gap}));await testInfo.attach('activity-measurements',{body:JSON.stringify({width,...measurements,pair},null,2),contentType:'application/json'});console.log(JSON.stringify({width,...measurements,pair}));
 await accessible(page);await row.getByRole('button',{name:'Hide',exact:true}).click();await expect(row.getByRole('heading',{name:'Statement',exact:true})).toHaveCount(0);await row.getByRole('button',{name:'Details',exact:true}).click();await expect.poll(()=>state.detailRequests.length).toBe(2);await row.getByRole('button',{name:'Hide',exact:true}).click();
 await region.focus();await page.keyboard.press('End');await expect.poll(()=>region.locator('.rec').count()).toBeLessThanOrEqual(12);await expect(row.getByRole('heading',{name:'Statement',exact:true})).toHaveCount(0);await accessible(page);
});
test('RED-016/017: outcome tabs, exact day counts and existing candidate navigation',async({page})=>{
 const state=await mockActivity(page);state.total=3;state.rows=[entry,{...entry,id:'018f8f9d-7f83-7abc-8def-000000000004',status:'refused',rowCount:null,metadata:{...entry.metadata,delivered:{},objects:[{catalog:'warehouse',schema:'public',name:'left'},{catalog:'warehouse',schema:'public',name:'right'}]}},{...entry,id:'018f8f9d-7f83-7abc-8def-000000000005',startedAt:'2026-08-31T23:59:59Z',status:'incomplete',rowCount:null,metadata:{objects:null,delivered:{},omissions:{},refusal:null}}];
 state.record={...state.record,status:'refused',rowCount:null,refusalCode:'sql_not_permitted',metadata:{...state.rows[1]!.metadata,refusal:{message:'An administrator must make both columns tokenized under a shared domain.',stage:'validate',candidate:{id,columns:[{elementId:id,name:'warehouse.public.left.id'},{elementId:pool,name:'warehouse.public.right.id'}]}}}};
 await page.goto(activityPath);await expect(page.getByRole('button',{name:'All 3',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Answer treated 1',exact:true})).toBeVisible();await expect(page.getByText('No answer was recorded',{exact:true})).toBeVisible();await expect(page.getByText('2026-08-31',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Refused 1',exact:true}).click();await expect.poll(()=>state.requests.at(-1)).toContain('outcome=refused');const row=page.getByRole('region',{name:'Activity records'}).locator('.rec').first();await expect(row).toContainText('Planned to read 2 objects');await row.getByRole('button',{name:'Details',exact:true}).click();await expect(row.getByText(/administrator must/)).toBeVisible();
 const link=row.getByRole('link',{name:'Review as a suggestion',exact:true});await expect(link).toHaveAttribute('href',new RegExp(`/projects/${project}/relationship-suggestions.*poolId=${pool}`));await expect(link).toHaveAttribute('href',new RegExp(`elementId=${id}`));await accessible(page);
});
test('RED-015: evidence permalink shares sampled/retained honesty and no reconstruction of missing detail',async({page})=>{
 const state=await mockActivity(page);state.total=1;state.record={...state.record,recordKind:'rollup',request:null,argumentVisibility:'hidden',rolledUpAt:'2026-09-28T12:00:00Z',detailCaptured:false,elements:[],objects:[],treatmentCounts:{tokenized:2},metadata:{objects:null,delivered:{tokenized:2},omissions:{},refusal:null}};
 await page.goto(detailPath);await expect(page.getByText('Summary counts only; element detail was removed by retention.',{exact:true})).toBeVisible();await expect(page.getByText('Request arguments were removed by retention.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Full recorded metadata',exact:true}).click();await expect(page.getByRole('heading',{name:'Versions recorded at open',exact:true})).toBeVisible();await accessible(page);
});

test('RED-015: agent identity fits and pool names replace key prefixes',async({page})=>{
 const state=await mockActivity(page);state.total=1;state.entry.agentId='engine-test-harness';state.entry.synthetic=true;
 await page.setViewportSize({width:1440,height:1000});await page.goto(activityPath);
 const actor=page.locator('.rec [data-part=actor]').first();
 await expect(actor).toContainText('engine-test-harness');await expect(actor).not.toContainText('opk_example');await expect(actor).not.toContainText('Reporting pool');
 const metrics=await actor.locator('b').evaluate(el=>({text:el.getBoundingClientRect().width,available:el.parentElement!.getBoundingClientRect().width}));expect(metrics.text).toBeLessThanOrEqual(metrics.available);console.log(JSON.stringify({agent:metrics}));
 state.pools[0]!.name='Development Demo Synthetic';state.pools.push({id,name:'Second pool',sourceIds:[]});await page.reload();await expect(actor).toContainText('Development Demo Synthetic');const poolSize=await actor.locator('[data-part=pool-name]').evaluate(el=>({text:el.getBoundingClientRect().width,available:el.parentElement!.getBoundingClientRect().width}));expect(poolSize.text).toBeLessThanOrEqual(poolSize.available);console.log(JSON.stringify({pool:poolSize}));await expect(actor).not.toContainText('opk_example');await expect(actor).not.toContainText('Synthetic demo');await accessible(page);
});

test('RED-016: day strips represent exact requests and outcome colours, not proportions',async({page})=>{
 const state=await mockActivity(page);state.total=11;state.rows=Array.from({length:11},(_,n)=>({...entry,id:`018f8f9d-7f83-7abc-8def-${String(n+10).padStart(12,'0')}`,startedAt:n<3?'2026-10-06T12:00:00Z':'2026-10-05T12:00:00Z',status:n===0?'refused':n===1?'incomplete':'answered'}));
 await page.setViewportSize({width:1440,height:1000});await page.goto(activityPath);
 for(const [day,count] of [['2026-10-06',3],['2026-10-05',8]] as const){const strip=page.locator('[data-part=day]').filter({has:page.getByText(day,{exact:true})}).locator('[data-part=day-outcomes]');await expect(strip.locator('svg')).toHaveAttribute('data-request-count',String(count));await expect(strip.locator('svg')).toHaveAttribute('width',String(count*9));expect(await strip.locator('rect').evaluateAll(elements=>elements.reduce((sum,el)=>sum+Number(el.getAttribute('data-count')),0))).toBe(count);}
 const first=page.locator('[data-part=day]').filter({has:page.getByText('2026-10-06',{exact:true})});for(const outcome of ['answered','refused','incomplete'])await expect(first.locator(`rect[data-outcome=${outcome}]`)).toHaveAttribute('data-count','1');
 const colours=await first.locator('circle').evaluateAll(elements=>elements.map(el=>({colour:getComputedStyle(el).color,fill:getComputedStyle(el).fill})));expect(new Set([colours[1]!.colour,colours[0]!.fill,colours[3]!.colour]).size).toBe(3);
 const refused=page.locator('.rec').filter({hasText:'Planned to read 1 object'}).first();const label=refused.locator('[data-part=identity] > b');await expect(label).toHaveCSS('white-space','nowrap');expect(await label.evaluate(el=>el.getBoundingClientRect().height)).toBe(18);await accessible(page);
});
