import {test} from './fixtures.js';
import {expect,type Page} from '@playwright/test';
import axe from 'axe-core';
import {mockDashboard,dashboardPath,project,pool,joinSuggestion} from './dashboard-fixture.js';
import {inspectControls,controlPatterns} from './conformance/checker.js';
async function accessible(page:Page){await page.addScriptTag({content:axe.source});expect(await page.evaluate(async()=>(await axe.run()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect((await page.evaluate(inspectControls,controlPatterns)).findings).toEqual([]);}
for(const width of [390,900,1440,1680])test(`RED-019/020: Dashboard geometry, factual visuals and evidence links at ${width}`,async({page},info)=>{
 const state=await mockDashboard(page);state.suggestions=[joinSuggestion()];await page.clock.setFixedTime(new Date('2026-09-29T01:00:00Z'));await page.setViewportSize({width,height:1000});await page.goto(dashboardPath);
 await expect(page.getByRole('heading',{name:'Needs you',exact:true})).toBeVisible();await expect(page.getByText('100 decisions across 1 pool',{exact:true})).toBeVisible();
 await expect(page.locator('[data-metric=requests] .v')).toHaveText('12');await expect(page.locator('[data-metric=refused] .v')).toHaveText('1');await expect(page.locator('[data-metric=incomplete] .v')).toHaveText('1');
 await expect(page.locator('[data-part=chart-label]')).toHaveCount(3);await expect(page.locator('[data-part=chart-label]')).toHaveText(['Last 7 days (UTC)','Last 7 days (UTC)','Last 7 days (UTC)']);await expect(page.getByText('Presence history is not recorded.',{exact:true})).toBeVisible();await expect(page.getByText('Join attempted',{exact:true})).toBeVisible();
 const measurements=await page.locator('[data-layout=dashboard]').evaluate(el=>{
  const measure=(selector:string)=>[...el.querySelectorAll(selector)].map(node=>{const r=node.getBoundingClientRect(),c=getComputedStyle(node);return {height:r.height,width:r.width,fontSize:c.fontSize,fontWeight:c.fontWeight,columns:c.gridTemplateColumns};});
  return {contentWidth:el.clientWidth-parseFloat(getComputedStyle(el).paddingLeft)-parseFloat(getComputedStyle(el).paddingRight),screen:{width:el.getBoundingClientRect().width,padding:getComputedStyle(el).padding},findings:measure('.card[data-layout=finding]'),counts:measure('[data-part=finding-count]'),labels:measure('[data-part=finding-label]'),exposure:measure('.spec'),exposureHeading:measure('.spec h3'),findingHeadings:measure('.card[data-layout=finding] h2'),metrics:measure('[data-layout=metrics]'),values:measure('.tile .v'),sparks:measure('.spark'),feed:measure('.feed .t')};
 });console.log(JSON.stringify({width,...measurements}));await info.attach('dashboard-measurements',{body:JSON.stringify({width,...measurements},null,2),contentType:'application/json'});
 expect(measurements.findings.every(c=>c.height>=186)).toBe(true);expect(measurements.counts.every(c=>c.fontSize==='38px')).toBe(true);expect(measurements.values.every(c=>c.fontSize==='30px')).toBe(true);expect(measurements.sparks.every(c=>c.height===22)).toBe(true);expect(measurements.feed.every(c=>c.fontSize==='13.5px'&&c.fontWeight==='560')).toBe(true);
 if(measurements.contentWidth>1150)expect(measurements.exposure[0]!.width).toBe(270);else expect(measurements.exposure[0]!.width).toBe(measurements.contentWidth);await accessible(page);
 const evidence=page.getByRole('link',{name:'Record',exact:true});await expect(evidence).toHaveAttribute('href',new RegExp(`/projects/${project}/runs/.*startedAt=`));await expect(page.locator('[data-layout=dashboard]')).not.toContainText('SELECT');await evidence.click();await expect(page.getByRole('heading',{name:'What the answer contained',exact:true})).toBeVisible();await accessible(page);
});
test('RED-019: count links carry the destination scope; observation tabs exclude unrelated findings',async({page})=>{
 const state=await mockDashboard(page);state.custody=true;state.suggestions=[joinSuggestion()];await page.goto(dashboardPath);await expect(page.getByRole('heading',{name:'Needs you'})).toBeVisible();
 const decide=page.getByRole('link',{name:'Decide',exact:true});await expect(decide).toHaveAttribute('href',new RegExp(`poolId=${pool}`));await expect(decide).toHaveAttribute('href',/decision=undecided/);
 const refused=page.locator('[data-metric=refused]').getByRole('link',{name:'Open Activity'});const url=new URL(await refused.getAttribute('href')??'', 'http://localhost');expect(url.searchParams.get('outcome')).toBe('refused');expect(url.searchParams.get('from')).toBe('2026-09-29T00:00:00.000Z');expect(url.searchParams.get('to')).toBe('2026-09-29T00:30:00.001Z');
 await expect(page.getByRole('link',{name:'Reporting pool: 100 decisions',exact:true})).toHaveAttribute('href',/decision=all/);await expect(page.getByRole('link',{name:'Reporting pool: 0 seen',exact:true})).toHaveAttribute('href',`/projects/${project}/pools/${pool}`);
 await decide.click();await expect(page.getByRole('button',{name:'Needs a decision 2',exact:true})).toBeVisible();await expect(page.getByText('2 members in 1 visible group.',{exact:true})).toBeVisible();await page.goto(dashboardPath);
 await page.getByRole('link',{name:'Review',exact:true}).first().click();await expect(page).toHaveURL(`/projects/${project}/relationship-suggestions`);await expect(page.getByRole('article')).toHaveCount(1);await expect(page.getByText('Join attempted',{exact:true})).toBeVisible();await page.goto(dashboardPath);
 await page.getByRole('link',{name:'Prepare for the operator',exact:true}).click();await expect(page).toHaveURL(/observationKind=filing/);await expect(page.getByRole('button',{name:'Open 1',exact:true})).toBeVisible();await expect(page.getByRole('article')).toHaveCount(1);await expect(page.getByRole('button',{name:'Resolved 0',exact:true})).toBeVisible();await accessible(page);
});
test('RED-020: clean attention band disappears, failure stays honest and setup remains usable',async({page})=>{
 const state=await mockDashboard(page);state.stats.spectrum.undecided=0;state.observations=[];state.recent=[];await page.goto(dashboardPath);await expect(page.getByRole('heading',{name:'Where the project stands',exact:true})).toBeVisible();await expect(page.getByRole('heading',{name:'Needs you',exact:true})).toHaveCount(0);await expect(page.getByText(/no issues|nothing to report/i)).toHaveCount(0);await accessible(page);
 state.error=true;await page.getByRole('button',{name:'Refresh dashboard'}).click();await expect(page.getByText('Dashboard could not be loaded')).toBeVisible();await expect(page.getByRole('heading',{name:'Where the project stands'})).toHaveCount(0);
 state.error=false;state.stats.pools=0;state.stats.sources=0;state.stats.requests=state.stats.queries=state.stats.prompts=state.stats.refused=state.stats.incomplete=0;await page.getByRole('button',{name:'Try again'}).click();await expect(page.getByText('Nothing to watch yet',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Connect a source',exact:true})).toBeVisible();await accessible(page);
});
