import {test} from './fixtures.js';
import {expect,type Page} from '@playwright/test';
import axe from 'axe-core';
import {mockDashboard,dashboardPath,project,pool,filing} from './dashboard-fixture.js';
const accessible=async(page:Page)=>{await page.addScriptTag({content:axe.source});expect(await page.evaluate(async()=>(await axe.run()).violations.map(v=>({id:v.id,nodes:v.nodes.map(n=>n.target)})))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);};
test.use({reducedMotion:'reduce',timezoneId:'America/Toronto'});
for(const width of [390,900,1440])test(`O-004 dashboard findings and quiet states at ${width}`,{tag:'@visual'},async({page})=>{
 const state=await mockDashboard(page);await page.setViewportSize({width,height:1000});await page.goto(dashboardPath);await expect(page.getByRole('heading',{name:'Needs a decision'})).toBeVisible();await expect(page.getByText('100 decisions across 2 pools',{exact:true})).toBeVisible();await expect(page.getByText('2026-09-29',{exact:true})).toBeVisible();await accessible(page);await expect(page).toHaveScreenshot(`dashboard-ready-${width}.png`,{fullPage:true});
 state.findings=[];state.stats.spectrum={...state.stats.spectrum,clear:82,undecided:0};state.shields[0]!.spectrum={...state.stats.spectrum};await page.getByRole('button',{name:'Refresh dashboard'}).click();await expect(page.getByRole('heading',{name:'Needs a decision'})).toHaveCount(0);await expect(page.locator('.feed,.ringnote,.warnrow')).toHaveCount(0);await expect(page.getByText(/no issues|nothing to report|worth a look/i)).toHaveCount(0);await accessible(page);await expect(page).toHaveScreenshot(`dashboard-clean-${width}.png`,{fullPage:true});
 state.stats={...state.stats,pools:0,sources:0,requests:0,queries:0,prompts:0,incomplete:0,refused:0,connectedAgents:0,spectrum:{clear:0,tokenized:0,masked:0,aggregate_only:0,withheld:0,undecided:0}};state.shields=[];await page.getByRole('button',{name:'Refresh dashboard'}).click();await expect(page.getByText('Nothing to watch yet',{exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Connect a source',exact:true})).toBeVisible();await accessible(page);await expect(page).toHaveScreenshot(`dashboard-empty-${width}.png`,{fullPage:true});
});
test('O-001/O-003 loading and error states recover; failures do not masquerade as clean',async({page})=>{
 const state=await mockDashboard(page);state.loading=true;await page.goto(dashboardPath);await expect(page.getByText('Preparing this view').first()).toBeVisible();await expect(page.getByRole('heading',{name:'Needs a decision'})).toBeVisible();state.loading=false;state.error=true;await page.getByRole('button',{name:'Refresh dashboard'}).click();await expect(page.getByText('Dashboard facts are temporarily unavailable. Retry the request.').first()).toBeVisible();state.error=false;await page.getByRole('button',{name:'Try again'}).first().click();await expect(page.getByText('Dashboard facts are temporarily unavailable. Retry the request.')).toHaveCount(0);await accessible(page);
});
test('O-004 quarantine has category and no filename; custody is gated; shields link to the specific pool',async({page})=>{
 const state=await mockDashboard(page);state.custody=true;await page.goto(dashboardPath);await expect(page.getByText('verification_mismatch',{exact:true})).toBeVisible();await expect(page.getByText('Key version 1: escrow could not be verified')).toBeVisible();const resolution=page.getByRole('button',{name:'Local resolution instructions',exact:true});await expect(resolution).toHaveAttribute('aria-expanded','false');await expect(resolution).toHaveAttribute('aria-controls',`resolution-quarantine:${filing}`);await resolution.click();await expect(resolution).toHaveAttribute('aria-expanded','true');await expect(page.getByText(/npm run sidecar:register -- show/)).toBeVisible();await expect(page.getByText(/PRIVATE.xlsx/)).toHaveCount(0);
 const counts=page.getByRole('button',{name:'Treatment counts for Reporting pool, Warehouse',exact:true});await expect(counts).toHaveAttribute('aria-expanded','false');await counts.click();await expect(counts).toHaveAttribute('aria-expanded','true');await expect(page.getByText('In the clear: 80',{exact:true})).toBeVisible();
 await page.getByRole('link',{name:'Reporting pool',exact:true}).click();await expect(page).toHaveURL(`/projects/${project}/pools/${pool}`);await expect(page.getByRole('navigation',{name:'Breadcrumb'}).getByRole('link',{name:'Pools',exact:true})).toBeVisible();
 state.admin=false;state.reads=[];await page.goto(dashboardPath);await expect(page.getByRole('heading',{name:'Needs a decision'})).toBeVisible();await expect(page.getByText('Key version 1: escrow could not be verified')).toHaveCount(0);expect(state.reads.some(p=>p.endsWith('/token-key'))).toBe(false);
});
test('O-004 clean feed stays absent through an SSE refresh',async({page})=>{
 const state=await mockDashboard(page);await page.goto(dashboardPath);await expect(page.getByRole('heading',{name:'Needs a decision'})).toBeVisible();state.findings=[];state.stats.spectrum.undecided=0;
 await page.evaluate(()=>{const s=(window as unknown as {dashboardStream:{onmessage:(m:{data:string})=>void}}).dashboardStream;s.onmessage({data:JSON.stringify({type:'snapshot',sequence:0,at:new Date().toISOString(),invalidate:['catalogElement']})});});await expect(page.getByRole('heading',{name:'Needs a decision'})).toHaveCount(0);await expect(page.locator('.feed')).toHaveCount(0);
});
