import {test} from './fixtures.js';
import {expect,type Page} from '@playwright/test';
import axe from 'axe-core';
import {mockDashboard,project,source} from './dashboard-fixture.js';
const engine='018f8f9d-7f83-7abc-8def-000000000005';
async function fixture(page:Page){const dashboard=await mockDashboard(page);await page.route('**/api/v1/projects/*/settings',route=>route.fulfill({json:{settings:{}}}));const state={empty:false,error:false,loading:false,verified:false,unreachable:false,pin:'AB'.repeat(32),actions:[] as string[]};await page.route('**/api/v1/projects/*/engines**',async route=>{const path=new URL(route.request().url()).pathname;if(state.loading)await new Promise(r=>setTimeout(r,900));if(state.error)return route.fulfill({status:503,json:{error:{code:'dependency_unavailable',message:'Engine registry unavailable. Retry.',requestId:'test',retryable:true}}});if(route.request().method()==='GET')return route.fulfill({json:{items:state.empty?[]:[{id:engine,name:'Customer network',address:'https://engine.customer.internal:3100',certificatePin:state.pin,contractVersion:state.verified?2:null,verifiedAt:state.verified?'2026-10-04T12:00:00Z':null,lastSeenAt:state.verified?'2026-10-04T12:00:00Z':null,health:state.unreachable?'unavailable':state.verified?'healthy':'unverified',healthMessage:null,custody:false,sources:[{id:source,name:'Reinsurance customer source with a long name'}]}],nextCursor:null}});state.actions.push(path);if(path.endsWith('/verify'))state.verified=true;return route.fulfill({json:{ok:true}});});await page.route('**/api/v1/projects/*/sources',route=>route.fulfill({json:{items:[{id:source,engineId:null,name:'Warehouse',exposedAlias:'warehouse',kind:'postgres',origin:'customer',status:'connected',error:null,landingStrategy:null,filingCount:null,elementCount:2,unsupportedCount:0,undecidedCount:0,latestIntrospectionId:null,lastIntrospectedAt:null}],nextCursor:null}}));return {state,dashboard};}
async function accessible(page:Page){await page.evaluate(axe.source);const result=await page.evaluate(()=>window.axe.run(document.querySelector('#opintel-app')!));expect(result.violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
for(const width of [900,1440])test(`ENG-007: reach registration through the drawer at ${width}`,async({page})=>{
 await fixture(page);await page.setViewportSize({width,height:1000});await page.goto(`/projects/${project}/dashboard`);
 const nav=page.getByRole('navigation',{name:'Primary navigation'});
 await nav.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByRole('tab',{name:'Engines',exact:true}).click();await page.getByRole('button',{name:'Register an engine',exact:true}).click();
 await expect(page).toHaveURL(`/projects/${project}/settings-engines`);
 await expect(page.getByRole('heading',{name:'Register engine',exact:true})).toBeVisible();
});
test('ENG-007: verification gates assignment; engine registration and custody actions are explicit; viewer is read-only',async({page})=>{const f=await fixture(page);await page.goto(`/projects/${project}/settings-engines`);await expect(page.getByRole('heading',{name:'Engines',exact:true})).toBeVisible();await expect(page.getByRole('tab',{name:'Engines',exact:true})).toBeVisible();await page.getByRole('button',{name:'Edit Customer network',exact:true}).click();await expect(page.getByRole('button',{name:'Designate custody engine'})).toBeDisabled();await expect(page.getByLabel('Warehouse')).toHaveText('Choose a verified engine');await page.getByRole('button',{name:'Test connection',exact:true}).click();await expect(page.getByRole('button',{name:'Designate custody engine'})).toBeEnabled();await expect(page.locator('.screen').getByRole('status')).toHaveText('Connection verified.');await page.getByLabel('Warehouse').selectOption(engine);await page.getByRole('button',{name:'Designate custody engine'}).click();expect(f.state.actions.at(-1)).toContain('/custody');await accessible(page);f.dashboard.admin=false;await page.reload();await page.getByRole('button',{name:'Register an engine',exact:true}).click();await expect(page.getByRole('button',{name:'Register',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Edit Customer network',exact:true}).click();await expect(page.getByRole('button',{name:'Test connection',exact:true})).toBeDisabled();});
test('ENG-007: loading, empty and error recover',async({page})=>{const f=await fixture(page);f.state.loading=true;await page.goto(`/projects/${project}/settings-engines`);await expect(page.getByText('Preparing this view').first()).toBeVisible();f.state.loading=false;await expect(page.getByText('Customer network',{exact:true})).toBeVisible();f.state.empty=true;await page.reload();await expect(page.getByText('No engines registered',{exact:true})).toBeVisible();f.state.error=true;await page.reload();await expect(page.getByText('Engine registry unavailable. Retry.')).toBeVisible();f.state.error=false;await page.getByRole('button',{name:'Try again'}).click();await expect(page.getByText('No engines registered',{exact:true})).toBeVisible();});
for(const width of [390,900,1440])test(`ENG-007 engines at ${width}`,{tag:'@visual'},async({page})=>{await fixture(page);await page.setViewportSize({width,height:1000});await page.goto(`/projects/${project}/settings-engines`);await expect(page.getByText('Customer network',{exact:true})).toBeVisible();await accessible(page);await expect(page).toHaveScreenshot(`engines-${width}.png`,{fullPage:true});});

for(const width of [390,900,1440])test(`SET-004: engine list and assignment select geometry at ${width}`,async({page},info)=>{
 await fixture(page);await page.setViewportSize({width,height:1000});await page.goto(`/projects/${project}/settings-engines`);await expect(page.getByRole('button',{name:'Edit Customer network'})).toBeVisible();
 const result=await page.evaluate(()=>{const row=document.querySelector<HTMLElement>('[data-layout="engine"]')!,label=row.querySelector<HTMLElement>('[data-part="identity"] > b')!,select=document.querySelector<HTMLSelectElement>('select[name="engineId"]')!,b=select.getBoundingClientRect(),arrow=select.parentElement!.querySelector('svg')!.getBoundingClientRect(),style=getComputedStyle(select);return {width:innerWidth,rowHeight:row.getBoundingClientRect().height,labelFont:getComputedStyle(label).fontSize,labelWeight:getComputedStyle(label).fontWeight,appearance:style.appearance,backgroundImage:style.backgroundImage,health:row.querySelector('[data-part="engine-health"]')!.textContent,overlap:(()=>{const s=row.querySelector('[data-part="engine-sources"]')!.getBoundingClientRect(),h=row.querySelector('[data-part="engine-health"]')!.getBoundingClientRect();return s.left<h.right&&s.right>h.left&&s.top<h.bottom&&s.bottom>h.top;})(),selectWidth:b.width,left:parseFloat(style.paddingLeft),right:b.right-parseFloat(style.borderRightWidth)-arrow.right,overflow:document.documentElement.scrollWidth>innerWidth};});
 console.log('SET-004 Engines',result);await info.attach('engine-geometry',{body:JSON.stringify(result),contentType:'application/json'});expect(result.appearance).toBe('none');expect(result.backgroundImage).toBe('none');expect(result.overlap).toBe(false);expect(result.health).toBe('Unverified');expect(result.labelFont).toBe('13.5px');expect(result.labelWeight).toBe('560');expect(result.left).toBe(10);expect(result.right).toBe(10);expect(result.overflow).toBe(false);
 await expect(page.getByLabel('Engine name',{exact:true})).toBeHidden();await page.getByRole('button',{name:'Register an engine',exact:true}).click();await expect(page.getByLabel('Engine name',{exact:true})).toBeVisible();await accessible(page);await page.getByRole('button',{name:'Register an engine',exact:true}).click();await page.getByRole('button',{name:'Edit Customer network',exact:true}).click();await accessible(page);
 const path=info.outputPath('engine-review.png');await page.screenshot({path,fullPage:true});await info.attach('engine-review',{path,contentType:'image/png'});
});

test('SET-004: engine health uses one state mark with its word',async({page})=>{const f=await fixture(page);await page.goto(`/projects/${project}/settings-engines`);const health=page.locator('[data-part="engine-health"]');await expect(health).toHaveText('Unverified');await expect(health.locator('[data-mark="needs-a-decision"]')).toHaveCount(1);f.state.verified=true;await page.reload();await expect(health).toHaveText('Healthy');await expect(health.locator('[data-mark="healthy"] circle')).toHaveAttribute('fill','var(--green-dk)');f.state.unreachable=true;await page.reload();await expect(health).toHaveText('Unreachable');await expect(health.locator('[data-mark="unreachable"] circle')).toHaveAttribute('fill','var(--ink-3)');await expect(page.locator('[data-mark-row="true"] [data-mark-category="state"]')).toHaveCount(1);await accessible(page);});
