import {test} from './fixtures.js';
import {expect,type Page} from '@playwright/test';
import axe from 'axe-core';
import {mockDashboard,project,source} from './dashboard-fixture.js';
const engine='018f8f9d-7f83-7abc-8def-000000000005';
async function fixture(page:Page){const dashboard=await mockDashboard(page);const state={empty:false,error:false,loading:false,verified:false,pin:'AB'.repeat(32),actions:[] as string[]};await page.route('**/api/v1/projects/*/engines**',async route=>{const path=new URL(route.request().url()).pathname;if(state.loading)await new Promise(r=>setTimeout(r,900));if(state.error)return route.fulfill({status:503,json:{error:{code:'dependency_unavailable',message:'Engine registry unavailable. Retry.',requestId:'test',retryable:true}}});if(route.request().method()==='GET')return route.fulfill({json:{items:state.empty?[]:[{id:engine,name:'Customer network',address:'https://engine.customer.internal:3100',certificatePin:state.pin,contractVersion:state.verified?2:null,verifiedAt:state.verified?'2026-10-04T12:00:00Z':null,lastSeenAt:state.verified?'2026-10-04T12:00:00Z':null,health:state.verified?'healthy':'unverified',healthMessage:null,custody:false,sources:[]}],nextCursor:null}});state.actions.push(path);if(path.endsWith('/verify'))state.verified=true;return route.fulfill({json:{ok:true}});});await page.route('**/api/v1/projects/*/sources',route=>route.fulfill({json:{items:[{id:source,engineId:null,name:'Warehouse',exposedAlias:'warehouse',kind:'postgres',origin:'customer',status:'connected',error:null,landingStrategy:null,filingCount:null,elementCount:2,unsupportedCount:0,undecidedCount:0,latestIntrospectionId:null,lastIntrospectedAt:null}],nextCursor:null}}));return {state,dashboard};}
async function accessible(page:Page){await page.evaluate(axe.source);const result=await page.evaluate(()=>window.axe.run(document.querySelector('#opintel-app')!));expect(result.violations).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
for(const width of [900,1440])test(`ENG-007: reach registration through the drawer at ${width}`,async({page})=>{
 await fixture(page);await page.setViewportSize({width,height:1000});await page.goto(`/projects/${project}/dashboard`);
 const nav=page.getByRole('navigation',{name:'Primary navigation'});
 await nav.getByRole('button',{name:'Settings',exact:true}).click();
 await nav.getByRole('link',{name:'Engines',exact:true}).click();
 await expect(page).toHaveURL(`/projects/${project}/settings-engines`);
 await expect(page.getByRole('heading',{name:'Register engine',exact:true})).toBeVisible();
});
test('ENG-007: verification gates assignment; engine registration and custody actions are explicit; viewer is read-only',async({page})=>{const f=await fixture(page);await page.goto(`/projects/${project}/settings-engines`);await expect(page.getByRole('heading',{name:'Engines',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Engines',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Designate custody engine'})).toBeDisabled();await expect(page.getByLabel('Warehouse')).toHaveText('Choose a verified engine');await page.getByRole('button',{name:'Test connection',exact:true}).click();await expect(page.getByRole('button',{name:'Designate custody engine'})).toBeEnabled();await page.getByLabel('Warehouse').selectOption(engine);await page.getByRole('button',{name:'Designate custody engine'}).click();expect(f.state.actions.at(-1)).toContain('/custody');await accessible(page);f.dashboard.admin=false;await page.reload();await expect(page.getByRole('button',{name:'Register',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'Test connection',exact:true})).toBeDisabled();});
test('ENG-007: loading, empty and error recover',async({page})=>{const f=await fixture(page);f.state.loading=true;await page.goto(`/projects/${project}/settings-engines`);await expect(page.getByText('Preparing this view').first()).toBeVisible();f.state.loading=false;await expect(page.getByRole('heading',{name:'Customer network',exact:true})).toBeVisible();f.state.empty=true;await page.reload();await expect(page.getByText('No engines registered',{exact:true})).toBeVisible();f.state.error=true;await page.reload();await expect(page.getByText('Engine registry unavailable. Retry.')).toBeVisible();f.state.error=false;await page.getByRole('button',{name:'Try again'}).click();await expect(page.getByText('No engines registered',{exact:true})).toBeVisible();});
for(const width of [390,900,1440])test(`ENG-007 engines at ${width}`,{tag:'@visual'},async({page})=>{await fixture(page);await page.setViewportSize({width,height:1000});await page.goto(`/projects/${project}/settings-engines`);await expect(page.getByRole('heading',{name:'Customer network',exact:true})).toBeVisible();await accessible(page);await expect(page).toHaveScreenshot(`engines-${width}.png`,{fullPage:true});});
