import {test} from './fixtures.js';
import {expect,type Page} from '@playwright/test';
import axe from 'axe-core';
import {readFile} from 'node:fs/promises';
import type {ObservationGroup,ObservationMember} from '../src/shared/api/observations.js';
const project='018f8f9d-7f83-7abc-8def-000000000001',source='018f8f9d-7f83-7abc-8def-000000000002',engine='018f8f9d-7f83-7abc-8def-000000000003',actor='018f8f9d-7f83-7abc-8def-000000000004';
const path=`/projects/${project}/observations`,privateValue='OBS_PRIVATE_FILE_CONTENT';
function group(cause:ObservationGroup['cause'],count:number,kind:ObservationGroup['kind']='filing'):ObservationGroup{return {id:`${kind}:${cause}:`,kind,cause,causeDetail:'',state:'open',count,oldestAt:'2026-10-01T12:00:00Z',latestAt:'2026-10-03T12:00:00Z'};}
function member(i:number):ObservationMember{const id=`018f8f9d-7f83-7abc-8def-${String(i+10).padStart(12,'0')}`;return {id,kind:'filing',state:'open',observedAt:'2026-10-01T12:00:00Z',resolvedAt:null,resolution:null,metadata:{filingId:id,zoneId:source,sourceName:'Monthly returns',engineId:engine,engineName:'Customer engine'},history:[{at:'2026-10-01T12:00:00Z',state:'open',resolution:null,cause:'no_rule_matched'}]};}
async function setup(page:Page){
 await page.clock.setFixedTime(new Date('2026-10-06T15:43:00Z'));
 const state={groups:[group('no_rule_matched',3),group('merged_header',1)],resolved:[] as ObservationGroup[],members:[member(0),member(1),member(2)],other:[{...member(3),history:[{...member(3).history[0]!,cause:'merged_header' as const}]}],custody:[] as ObservationGroup[],custodyMembers:[] as ObservationMember[],admin:true,loading:false,error:false,memberError:false,requests:[] as string[]};
 await page.route('**/api/v1/**',async route=>{const url=new URL(route.request().url()),p=url.pathname;state.requests.push(route.request().method()+' '+p);
 if(p.endsWith('/auth/me'))return route.fulfill({json:{id:actor,email:'admin@example.test',fullName:'Admin',timezone:'UTC',method:'magic_link',sessionCreatedAt:'2026-01-01T00:00:00Z',deviceConfirmed:true}});
 if(p.endsWith('/projects'))return route.fulfill({json:{items:[{id:project,name:'Reporting',company:{id:actor,name:'Example'},industry:{id:actor,name:'General'},region:'eu-west-1',role:state.admin?'admin':'viewer'}],nextCursor:null}});
 if(p.endsWith('/observations')||p.endsWith('/custody-observations')){
  if(state.loading)await new Promise(resolve=>setTimeout(resolve,600));if(state.error)return route.fulfill({status:503,json:{error:{code:'dependency_unavailable',message:'Observation history is temporarily unavailable.',requestId:'test',retryable:true}}});
  const custody=p.endsWith('/custody-observations'),view=url.searchParams.get('view'),items=custody?state.custody:view==='resolved'?state.resolved:state.groups;
  return route.fulfill({json:{items,nextCursor:null,counts:{open:custody?state.custody.reduce((n,g)=>n+g.count,0):state.groups.reduce((n,g)=>n+g.count,0),resolved:custody?0:state.resolved.reduce((n,g)=>n+g.count,0)}}});
 }
 if(p.endsWith('/observations/members')||p.endsWith('/custody-observations/members')){
  if(state.memberError)return route.fulfill({status:503,json:{error:{code:'dependency_unavailable',message:'Affected records are temporarily unavailable.',requestId:'members',retryable:true}}});
  const cause=url.searchParams.get('group')??'',items=p.includes('custody-observations')?state.custodyMembers:cause.includes('no_rule_matched')?state.members:state.other;
  return route.fulfill({json:{items:items.map(m=>({...m,metadata:{...m.metadata,filename:privateValue,reason:privateValue}})),nextCursor:null}});
 }
 return route.fulfill({status:404,json:{}});
 });return state;
}
async function accessible(page:Page){await page.addScriptTag({content:axe.source});expect(await page.evaluate(async()=>(await axe.run()).violations.map(v=>v.id))).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);}
test('RED-012: one explanation per cause, keyboard disclosure and short member rows',async({page})=>{
 const state=await setup(page);await page.goto(path);await expect(page.getByRole('article')).toHaveCount(2);const noRule=page.getByRole('article',{name:'No filing-party rule matched.',exact:true});
 await expect(noRule.getByText('Nothing landed, so this data is not in the catalogue.',{exact:true})).toHaveCount(1);await expect(noRule.getByText('A filing arrived in the landing zone',{exact:true})).toHaveCount(0);
 await noRule.getByRole('button',{name:'Details',exact:true}).focus();await page.keyboard.press('Enter');await expect(noRule.getByRole('listitem')).toHaveCount(3);await expect(noRule.getByText('Resolved by whoever operates the Opintel Engine.',{exact:true})).toBeVisible();await expect(noRule.getByText('The full reason stays in the customer environment because it may contain file contents.',{exact:true})).toHaveCount(1);
 await expect(noRule.getByRole('button',{name:`Copy IDs for filing ${state.members[0]!.id}`})).toBeVisible();await noRule.getByRole('button',{name:'Hide',exact:true}).focus();await page.keyboard.press('Space');await expect(noRule.getByRole('listitem')).toHaveCount(0);await accessible(page);
});
test('RED-013: resolved facts remain muted behind Resolved; history explains the earlier quarantine',async({page})=>{
 const state=await setup(page);state.groups=[];state.resolved=[{...group('no_rule_matched',3),state:'resolved'}];state.members=state.members.map(m=>({...m,state:'resolved',resolvedAt:'2026-10-04T12:00:00Z',resolution:'landed',history:[...m.history,{at:'2026-10-04T12:00:00Z',state:'resolved',cause:'no_rule_matched',resolution:'landed'}]}));
 await page.goto(path);await expect(page.getByText('Nothing needs attention.',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Resolved 3',exact:true}).click();const card=page.getByRole('article');await expect(card).toHaveAttribute('data-state','resolved');await expect(card).toHaveCSS('background-color','rgb(248, 246, 251)');await card.getByRole('button',{name:'Details',exact:true}).click();await expect(card.getByText('The filing landed.',{exact:true})).toHaveCount(3);
 await card.getByRole('button',{name:'History',exact:true}).first().click();await expect(card.getByText('Filing ID:',{exact:false})).toBeVisible();await expect(card.locator('[id$="-history"]').filter({visible:true}).getByText('No filing-party rule matched.',{exact:false})).toBeVisible();await accessible(page);
});
test('RED-014: prepare all cause groups produces a copy/download packet, full ids, no local values and no delivery',async({page,context})=>{
 const state=await setup(page);await context.grantPermissions(['clipboard-read','clipboard-write']);await page.goto(path);await page.getByRole('button',{name:'Prepare for the operator',exact:true}).click();const packet=page.getByLabel('Copyable summary');await expect(packet).toBeVisible();const text=await packet.inputValue();for(const m of [...state.members,...state.other])expect(text).toContain(m.id);expect(text).toContain(source);expect(text).toContain(engine);expect(text).toContain('Customer engine');expect(text).toContain('No filing-party rule matched.');expect(text).toContain('The header contains merged cells.');expect(text).not.toContain(privateValue);await expect(page.getByText('This is a packet for you to carry. Nothing has been sent.',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Copy packet',exact:true}).click();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe(text);const downloaded=page.waitForEvent('download');await page.getByRole('button',{name:'Download packet',exact:true}).click();const file=await(await downloaded).path();expect(await readFile(file!,'utf8')).toBe(text);expect(state.requests.every(r=>r.startsWith('GET '))).toBe(true);await accessible(page);
});
test('RED-014: one filing packet contains only that filing; incomplete fetch produces no partial packet',async({page})=>{
 const state=await setup(page);await page.goto(path);const card=page.getByRole('article',{name:'No filing-party rule matched.',exact:true});await card.getByRole('button',{name:'Details',exact:true}).click();await card.getByRole('button',{name:`Prepare filing ${state.members[0]!.id} for the operator`}).click();const text=await page.getByLabel('Copyable summary').inputValue();expect(text).toContain(state.members[0]!.id);expect(text).not.toContain(state.members[1]!.id);await page.getByRole('button',{name:'Close packet',exact:true}).click();state.memberError=true;await card.getByRole('button',{name:'Prepare for the operator',exact:true}).click();await expect(page.getByRole('status').filter({hasText:'The complete packet'})).toContainText('no partial packet was produced');await expect(page.getByLabel('Copyable summary')).toHaveCount(0);await accessible(page);
});
test('RED-012/013: loading, quiet empty, errors and recovery; viewer does not request custody metadata',async({page})=>{
 const state=await setup(page);state.admin=false;state.loading=true;await page.goto(path);await expect(page.getByText('Preparing this view',{exact:true})).toBeVisible();await expect(page.getByRole('article')).toHaveCount(2);expect(state.requests.some(r=>r.includes('custody-observations'))).toBe(false);state.loading=false;state.error=true;await page.reload();await expect(page.getByText('Observation history is temporarily unavailable.',{exact:true})).toBeVisible();state.error=false;state.groups=[];await page.getByRole('button',{name:'Try again',exact:true}).click();await expect(page.getByText('Nothing needs attention.',{exact:true})).toBeVisible();await expect(page.locator('.blank')).toHaveCount(0);await accessible(page);
});
for(const width of [390,900,1440])test(`RED-012: measured grouped Observations ${width}`,async({page})=>{
 await setup(page);await page.setViewportSize({width,height:1000});await page.goto(path);const card=page.getByRole('article',{name:'No filing-party rule matched.',exact:true});await card.getByRole('button',{name:'Details',exact:true}).click();await expect(card.getByRole('listitem')).toHaveCount(3);await page.evaluate(()=>document.fonts.ready);
 const measurements=await card.evaluate(el=>{const rect=(selector:string)=>{const n=el.querySelector<HTMLElement>(selector)!;const c=getComputedStyle(n),r=n.getBoundingClientRect();return {height:r.height,width:r.width,fontSize:c.fontSize,fontWeight:c.fontWeight,padding:c.padding,grid:c.gridTemplateColumns};};return {header:rect('.card-h'),title:rect('h2'),mark:rect('.sev'),count:rect('[data-part="count"]'),remediation:rect('[data-part="remediation"]'),row:rect('.rhead'),rowName:rect('.rhead [data-part="identity"] > b')};});
 console.log('Observations measurements',width,JSON.stringify(measurements));expect(measurements.title.fontSize).toBe('15px');expect(measurements.title.fontWeight).toBe('650');expect(measurements.rowName.fontSize).toBe('13.5px');expect(measurements.rowName.fontWeight).toBe('560');expect(measurements.mark.width).toBe(32);expect(measurements.count.fontSize).toBe('27px');await accessible(page);
});


test('RED-012/013: mapping and custody groups name their resolver, preserve short labels and distinguish current from retained keys',async({page})=>{
 const state=await setup(page);state.groups=[{...group('unmapped',1,'type'),id:'type:unmapped:inet',causeDetail:'inet'}];state.other=[{id:source,kind:'type',state:'open',observedAt:'2026-10-01T12:00:00Z',resolvedAt:null,resolution:null,metadata:{elementId:source,sourceId:source,sourceName:'Warehouse',object:'records',column:'address',sourceType:'inet',runId:engine},history:[{at:'2026-10-01T12:00:00Z',state:'open',cause:'unmapped',resolution:null}]}];state.custody=[group('custody_failed',2,'custody')];state.custodyMembers=[1,2].map(version=>({id:String(version),kind:'custody',state:'open',observedAt:'2026-10-01T12:00:00Z',resolvedAt:null,resolution:null,metadata:{keyVersion:version,keyState:version===1?'retired':'current'},history:[{at:'2026-10-01T12:00:00Z',state:'open',cause:'custody_failed',resolution:null}]}));
 await page.goto(path);await expect(page.getByRole('button',{name:'Prepare for the operator',exact:true})).toBeDisabled();const types=page.getByRole('article',{name:'A source type has no mapping: inet',exact:true}),custody=page.getByRole('article',{name:'Escrow could not be verified',exact:true});
 await types.getByRole('button',{name:'Details',exact:true}).click();await expect(types.getByText('records.address',{exact:true})).toBeVisible();await expect(types.getByText('Resolved by the Opintel maintainer, then the source operator.',{exact:true})).toBeVisible();await expect(types.getByRole('link',{name:'View introspection'})).toHaveAttribute('href',`/projects/${project}/introspections/${engine}`);
 await custody.getByRole('button',{name:'Details',exact:true}).click();await expect(custody.getByText('Retired. This retained key is needed to verify earlier evidence.',{exact:true})).toBeVisible();await expect(custody.getByText('Current. Source connections are refused until backup verification succeeds.',{exact:true})).toBeVisible();await expect(custody.getByRole('link',{name:'Open token key'})).toHaveAttribute('href',`/projects/${project}/token-key`);await accessible(page);
});
