import type {Page} from '@playwright/test';
import {mockDashboard,source} from './dashboard-fixture.js';
export async function fixture(page:Page){const dashboard=await mockDashboard(page);const state={error:false,loading:false,settings:{discovery:{newElements:'rules_only',typeFamilyChange:'revert',renameHandling:'carry',adoptRenamedNames:false,valueSampling:false},query:{},evidence:{}} as Record<string,unknown>,personal:{email:'admin@example.com',fullName:'Admin',timezone:'UTC',dateFormat:'YYYY-MM-DD',reducedMotion:false},company:{id:source,name:'Example Company',defaultIndustryId:source,defaultRegion:'eu-west-1',allowedDomains:[],idleTimeoutMins:480,ssoEnforced:false,enabledProviders:[]},writes:[] as unknown[]};
 await page.route('**/api/v1/**',async route=>{const path=new URL(route.request().url()).pathname;if(path.endsWith('/companies'))return route.fulfill({json:{items:[{id:source,name:'Example Company',role:dashboard.admin?'admin':'member',projectCount:1}],nextCursor:null}});if(path.endsWith('/industries'))return route.fulfill({json:[{id:source,slug:'reinsurance-treaty',name:'Reinsurance',description:null,inheritedTermCount:0,hasDemoPack:false}]});if(path.endsWith('/engines'))return route.fulfill({json:{items:[],nextCursor:null}});if(!path.endsWith('/settings'))return route.fallback();
 if(state.loading)await new Promise(r=>setTimeout(r,700));if(state.error)return route.fulfill({status:503,json:{error:{code:'dependency_unavailable',message:'Settings unavailable. Retry the request.',requestId:'settings',retryable:true}}});
 const kind=path.includes('/me/')?'personal':path.includes('/companies/')?'company':'project';
 if(route.request().method()==='PATCH'){const body=route.request().postDataJSON() as Record<string,unknown>;state.writes.push(body);if(kind==='project')state.settings={...state.settings,...body};else if(kind==='personal')Object.assign(state.personal,body);else Object.assign(state.company,body);}
 return route.fulfill({json:kind==='project'?{settings:state.settings}:kind==='personal'?state.personal:state.company});
 });return {state,dashboard};}
