import type {ObservationGroup,ObservationMember} from './api/observations.js';
export const quarantineLabels:Record<string,string>={
 no_rule_matched:'No filing-party rule matched.',multiple_rules_matched:'More than one filing-party rule matched.',unreadable_format:'The file format could not be read.',sheet_absent:'The declared sheet is missing.',merged_header:'The header contains merged cells.',formula_uncached:'A formula has no cached value.',locale_undeclared:'The filing party has no declared locale.',period_unparseable:'The period does not match the declared format.',verification_mismatch:'The content does not match the attributed filing party.',column_type_changed:'A column type differs from earlier filings.',rule_invalid:'The filing rule is invalid.',attribution_missing:'The filing could not be attributed to a party.',header_invalid:'The declared header is invalid.',
};
export const observationCopy=(group:Pick<ObservationGroup,'kind'|'cause'|'causeDetail'>)=>{
 if(group.kind==='filing')return {title:quarantineLabels[group.cause]??'The filing needs local review before it can land.',consequence:group.cause==='merged_header'?"Column names could not be read with confidence, so nothing was extracted. Nothing landed, and this data is not in the catalogue.":"Nothing landed, so this data is not in the catalogue.",owner:'whoever operates the Opintel Engine',instructions:'Inspect the filing in the local register, correct its rule or the file, and retry it.',privacy:'The full reason stays in the customer environment because it may contain file contents.'};
 if(group.kind==='type')return {title:`A source type has no mapping: ${group.causeDetail}`,consequence:'These elements were catalogued but cannot be exposed or receive access decisions. This is an Opintel mapping gap, not a problem with your data.',owner:'the Opintel maintainer, then the source operator',instructions:'The maintainer supplies the type mapping; the source operator re-introspects the source after that repair. Existing element identities and decisions are retained by a mapping repair.',privacy:null};
 return {title:group.cause==='custody_mismatch'?'Escrow does not match the recorded key':'Escrow could not be verified',consequence:'Unverified backup for the current key refuses source connections. Retained keys are needed to verify earlier evidence.',owner:'the key custody operator',instructions:'Check the independent backup location and run a restore rehearsal. Do not rotate to repair a missing key: rotation cannot recover earlier tokens.',privacy:null};
};
export const resolutionLabel=(resolution:string|null)=>({landed:'The filing landed.',mapping_repaired:'The mapping was repaired.',explicitly_excluded:'The type is now explicitly excluded.',removed:'The element was removed.',source_type_changed:'The source type changed.',source_archived:'The source was archived.',backup_verified:'A restore rehearsal verified the backup.',cause_changed:'A later check recorded a different cause.'}[resolution??'']??'Resolution recorded.');
export const observationMemberLabel=(member:ObservationMember)=>member.kind==='filing'?'A filing arrived in the landing zone':member.kind==='type'?`${member.metadata.object??'Unnameable object'}.${member.metadata.column??'Unnameable element'}`:`Key version ${member.metadata.keyVersion}`;
