import {Timestamp} from '../settings/preferences.js';
import {useForm} from 'react-hook-form';
import {useEngines,useEngineAction} from './data.js';
import {useProjects} from '../tenancy/data.js';
import {useSources} from '../sources/data.js';
import {EngineRegistration} from '../../shared/api/engines.js';
import {Button,LoadingState,ErrorState,EmptyState} from '../../shared/ui/index.js';
export function EnginesScreen({projectId}:{projectId:string}){
 const engines=useEngines(projectId),projects=useProjects(),sources=useSources(projectId),action=useEngineAction(projectId);
 const form=useForm({defaultValues:{name:'',address:'',certificatePin:''}});
 if(engines.isPending||projects.isPending||sources.isPending)return <LoadingState/>;
 if(engines.isError||projects.isError||sources.isError)return <ErrorState title="Engines could not be loaded" description={(engines.error??projects.error??sources.error)?.message??'Try again.'} retry={()=>Promise.all([engines.refetch(),projects.refetch(),sources.refetch()])}/>;
 const admin=projects.data?.find(p=>p.id===projectId)?.role==='admin';
 return <section className="screen on"><h1>Engines</h1><p className="sub">Register a private engine, test its connection, then assign sources. Health reflects the last check.</p>{!admin?<p className="note">Read-only. A project administrator registers and assigns engines.</p>:null}
 <form className="card" onSubmit={form.handleSubmit(async v=>{const parsed=EngineRegistration.safeParse(v);if(!parsed.success){form.setError('root',{message:parsed.error.issues.map(i=>i.message).join(' ')});return;}await action.mutateAsync({path:'engines',body:parsed.data}).then(()=>form.reset()).catch(()=>undefined);})}><div className="card-h"><h2>Register engine</h2><Button type="submit" disabled={!admin||action.isPending}>{action.isPending?'Working…':'Register'}</Button></div><div className="sheetb">{(['name','address','certificatePin'] as const).map(key=><div className="fld" key={key}><label htmlFor={`engine-${key}`}>{key==='name'?'Engine name':key==='address'?'Private HTTPS address':'Certificate SHA-256 pin'}</label><input id={`engine-${key}`} disabled={!admin||action.isPending} required {...form.register(key)}/>{key==='certificatePin'?<p className="hint">64 hexadecimal characters. A valid-looking typo is caught by Test connection before this engine can be used.</p>:null}</div>)}{form.formState.errors.root?<p role="alert">{form.formState.errors.root.message}</p>:null}</div></form>
 {action.isError&&action.variables?.path==='engines'?<p className="note" role="alert">{action.error.message}</p>:null}{action.isSuccess&&action.variables?.path==='engines'?<p className="note" role="status">Engine operation completed.</p>:null}
 {!engines.data.length?<EmptyState icon="⚙" title="No engines registered" description="Register and verify an engine before assigning sources."/>:engines.data.map(engine=><article className="card" key={engine.id}><div className="card-h"><h2>{engine.name}{engine.custody?' · Custody engine':''}</h2><span className="meta">{engine.health.replaceAll('_',' ')}</span></div><div className="sheetb"><p className="mono" style={{whiteSpace:'normal',overflowWrap:'anywhere'}}>{engine.address}</p><EngineEdit projectId={projectId} engine={engine} disabled={!admin}/><p>Contract: {engine.contractVersion??'Not checked'} · Last seen: {engine.lastSeenAt?<Timestamp value={engine.lastSeenAt}/>:'Never'}</p>{engine.healthMessage?<p className="note">{engine.healthMessage}</p>:null}<p>Sources: {engine.sources.map(s=>s.name).join(', ')||'None assigned'}</p><Button disabled={!admin||action.isPending} onClick={()=>action.mutate({path:`engines/${engine.id}/verify`,body:{}})}>{action.isPending&&action.variables?.path===`engines/${engine.id}/verify`?'Testing…':'Test connection'}</Button> <Button disabled={!admin||action.isPending||!engine.verifiedAt||engine.custody} onClick={()=>action.mutate({path:`engines/${engine.id}/custody`,body:{}})}>Designate custody engine</Button>{action.isError&&action.variables?.path.startsWith(`engines/${engine.id}/`)?<p role="alert" className="note">{action.error.message}</p>:null}{action.isSuccess&&action.variables?.path===`engines/${engine.id}/verify`?<p role="status" className="note">Connection verified.</p>:null}</div></article>)}
 <div className="card"><div className="card-h"><h2>Source assignments</h2></div>{sources.data.map(source=><form className="frow" key={source.id} onSubmit={e=>{e.preventDefault();const value=new FormData(e.currentTarget).get('engineId');if(typeof value==='string'&&value)action.mutate({path:`sources/${source.id}/engine`,method:'PATCH',body:{engineId:value}});}}><div className="fl"><label htmlFor={`engine-source-${source.id}`}><b>{source.name}</b></label><span>{source.engineId?'Assigned to '+(engines.data.find(e=>e.id===source.engineId)?.name??source.engineId):'No engine assigned; introspection and query are refused.'}</span></div><select className="inp" id={`engine-source-${source.id}`} name="engineId" required defaultValue={source.engineId??''} disabled={!admin||action.isPending}><option value="">Choose a verified engine</option>{engines.data.filter(e=>e.verifiedAt&&e.contractVersion===2).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><Button type="submit" disabled={!admin||action.isPending||!engines.data.some(e=>e.verifiedAt&&e.contractVersion===2)}>Assign</Button>{action.isError&&action.variables?.path===`sources/${source.id}/engine`?<p role="alert" className="note">{action.error.message}</p>:null}</form>)}</div></section>;
}

function EngineEdit({projectId,engine,disabled}:{projectId:string;engine:import('../../shared/api/engines.js').EngineView;disabled:boolean}){const form=useForm({defaultValues:{name:engine.name,address:engine.address,certificatePin:engine.certificatePin}}),action=useEngineAction(projectId);return <form onSubmit={form.handleSubmit(async v=>{const p=EngineRegistration.safeParse(v);if(!p.success){form.setError('root',{message:p.error.issues.map(i=>i.message).join(' ')});return;}await action.mutateAsync({path:`engines/${engine.id}`,method:'PATCH',body:p.data}).catch(()=>undefined);})}>{(['name','address','certificatePin'] as const).map(key=><div className="fld" key={key}><label htmlFor={`edit-${engine.id}-${key}`}>{key==='name'?'Engine name':key==='address'?'Private address':'Certificate pin'}</label><input id={`edit-${engine.id}-${key}`} disabled={disabled||action.isPending} {...form.register(key)}/></div>)}<Button type="submit" disabled={disabled||action.isPending}>{action.isPending?'Saving…':'Save and require verification'}</Button>{form.formState.errors.root?<p role="alert">{form.formState.errors.root.message}</p>:null}{action.isError?<p role="alert">{action.error.message}</p>:null}</form>;}
