import {SettingsSelect} from '../settings/controls.js';
import {useEngineDisclosure} from './state.js';
import {FindingCard,Mark} from '../../shared/ui/index.js';
import {Timestamp} from '../settings/preferences.js';
import {useForm} from 'react-hook-form';
import {useEngines,useEngineAction} from './data.js';
import {useProjects} from '../tenancy/data.js';
import {useSources} from '../sources/data.js';
import {EngineRegistration} from '../../shared/api/engines.js';
import {Button,LoadingState,ErrorState,EmptyState} from '../../shared/ui/index.js';
export function EnginesScreen({projectId,embedded=false}:{projectId:string;embedded?:boolean}){
 const engines=useEngines(projectId),projects=useProjects(),sources=useSources(projectId),action=useEngineAction(projectId),ui=useEngineDisclosure();
 const form=useForm({defaultValues:{name:'',address:'',certificatePin:''}}),registration=ui.expanded[projectId+':register']??false;
 if(engines.isPending||projects.isPending||sources.isPending)return <LoadingState/>;
 if(engines.isError||projects.isError||sources.isError)return <ErrorState title="Engines could not be loaded" description={(engines.error??projects.error??sources.error)?.message??'Try again.'} retry={()=>Promise.all([engines.refetch(),projects.refetch(),sources.refetch()])}/>;
 const admin=projects.data?.find(p=>p.id===projectId)?.role==='admin',unhealthy=engines.data.filter(e=>e.health!=='healthy'),unassigned=sources.data.filter(s=>!s.engineId),finding=unhealthy[0];
 return <div className={embedded?undefined:'screen on'} data-layout={embedded?undefined:'settings'}><h2>Engines</h2><p className="sub">Each source is read by one Engine. Register one, verify it, then assign sources. Health reflects the last check.</p>{!admin?<p className="note">Read-only. A project administrator registers and assigns engines.</p>:null}
 {!engines.data.length&&unassigned.length?<FindingCard title="Engine required" needsDecision footer={<Button onClick={()=>ui.toggle(projectId+':register')}>Register an engine</Button>}><strong data-part="finding-count">{unassigned.length}</strong><p>{unassigned.length===1?'Source needs':'Sources need'} a registered and verified engine.</p></FindingCard>:finding?<FindingCard title="Engine verification" needsDecision footer={<Button disabled={!admin||action.isPending} onClick={()=>action.mutate({path:`engines/${finding.id}/verify`,body:{}})}>{action.isPending&&action.variables?.path.endsWith('/verify')?'Testing…':'Test connection'}</Button>}><strong data-part="finding-count">{unhealthy.length}</strong><p>{finding.name} {finding.health==='contract_mismatch'?'reports a different contract version. Update the Engine to the application’s contract version and test again.':finding.health==='unverified'?'needs verification. Check its address, certificate pin and the application’s TLS trust.':'could not be verified. Check its address, certificate pin and the application’s TLS trust.'}</p>{action.isError&&action.variables?.path===`engines/${finding.id}/verify`?<p role="alert">{action.error.message}</p>:null}</FindingCard>:unassigned.length?<FindingCard title="Source assignments" needsDecision footer={<a className="btn" href="#source-assignments">Assign sources</a>}><strong data-part="finding-count">{unassigned.length}</strong><p>{unassigned.length===1?'Source needs':'Sources need'} an engine before introspection or query.</p></FindingCard>:null}
 {action.isSuccess&&action.variables?.path.endsWith('/verify')?<p className="note" role="status">Connection verified.</p>:null}
 <div className="card"><div className="card-h"><h2>Registered</h2><button className="btn" type="button" disabled={action.isPending} aria-expanded={registration} aria-controls="engine-registration" onClick={()=>ui.toggle(projectId+':register')}>Register an engine</button></div>
 <div id="engine-registration" hidden={!registration}><form onSubmit={form.handleSubmit(async v=>{const parsed=EngineRegistration.safeParse(v);if(!parsed.success){form.setError('root',{message:parsed.error.issues.map(i=>i.message).join(' ')});return;}try{await action.mutateAsync({path:'engines',body:parsed.data});form.reset();ui.close(projectId+':register');}catch{/* Mutation error is shown in this form. */}})}><div className="sheetb"><h3>Register engine</h3>{(['name','address','certificatePin'] as const).map(key=><div className="fld" key={key}><label htmlFor={`engine-${key}`}>{key==='name'?'Engine name':key==='address'?'Private HTTPS address':'Certificate SHA-256 pin'}</label><input id={`engine-${key}`} disabled={!admin||action.isPending} required {...form.register(key)}/>{key==='certificatePin'?<p className="hint">64 hexadecimal characters. The Engine prints this pin at startup; use its sidecar:pin command to read it later. A valid-looking typo is caught by Test connection before use.</p>:null}</div>)}<Button type="submit" disabled={!admin||action.isPending}>{action.isPending?'Working…':'Register'}</Button>{form.formState.errors.root?<p role="alert">{form.formState.errors.root.message}</p>:null}{action.isError&&action.variables?.path==='engines'?<p role="alert">{action.error.message}</p>:null}</div></form></div>
 {action.isSuccess&&action.variables?.path==='engines'?<p className="note" role="status">Engine operation completed.</p>:null}
 {!engines.data.length?<EmptyState title="No engines registered" description="Register and verify an engine before assigning sources."/>:<div role="list" aria-label="Registered engines" data-mark-list="uniform">{engines.data.map(engine=>{const open=ui.expanded[engine.id]??false;return <div key={engine.id} role="listitem" data-mark-row="true" data-row-kind="engine"><div className="frow" data-layout="engine"><div data-part="identity"><b>{engine.name}</b>{engine.custody?<span className="tr">Custody</span>:null}<div className="mono" data-part="engine-address">{engine.address}</div></div><span data-part="engine-sources">{engine.sources.length} {engine.sources.length===1?'source':'sources'}{engine.sources.length?' · '+engine.sources.map(s=>s.name).join(', '):''}</span><span className="tr" data-part="engine-health"><Mark name={engine.health==='healthy'?'healthy':engine.health==='unavailable'?'unreachable':'needs-a-decision'} size={18}/>{engine.health==='unavailable'?'Unreachable':engine.health==='contract_mismatch'?'Contract mismatch':engine.health==='healthy'?'Healthy':'Unverified'}</span><button className="toolchip" type="button" aria-label={`Edit ${engine.name}`} aria-expanded={open} aria-controls={'engine-'+engine.id} onClick={()=>ui.toggle(engine.id)}>Edit</button></div>
 <div className="rdetail" id={'engine-'+engine.id} hidden={!open}>{open?<EngineEdit projectId={projectId} engine={engine} disabled={!admin}/>:null}<p>Certificate pin: <code>{engine.certificatePin}</code></p><p>Contract: {engine.contractVersion??'Not checked'} · Last seen: {engine.lastSeenAt?<Timestamp value={engine.lastSeenAt}/>:'Never'}</p>{engine.healthMessage?<p className="note">{engine.healthMessage}</p>:null}{engine.id!==finding?.id?<Button disabled={!admin||action.isPending} onClick={()=>action.mutate({path:`engines/${engine.id}/verify`,body:{}})}>{action.isPending&&action.variables?.path.endsWith('/verify')?'Testing…':'Test connection'}</Button>:null} <Button disabled={!admin||action.isPending||!engine.verifiedAt||engine.custody} onClick={()=>action.mutate({path:`engines/${engine.id}/custody`,body:{}})}>Designate custody engine</Button>{action.isError&&action.variables?.path.startsWith(`engines/${engine.id}/`)&&(engine.id!==finding?.id||!action.variables.path.endsWith('/verify'))?<p role="alert" className="note">{action.error.message}</p>:null}</div></div>;})}</div>}</div>
 <div className="card" id="source-assignments"><div className="card-h"><h2>Source assignments</h2></div>{sources.data.map(source=><form className="frow" key={source.id} onSubmit={e=>{e.preventDefault();const value=new FormData(e.currentTarget).get('engineId');if(typeof value==='string'&&value)action.mutate({path:`sources/${source.id}/engine`,method:'PATCH',body:{engineId:value}});}}><div className="fl"><label htmlFor={`engine-source-${source.id}`}><b>{source.name}</b></label><span>{source.engineId?'Assigned to '+(engines.data.find(e=>e.id===source.engineId)?.name??source.engineId):'No engine assigned; introspection and query are refused.'}</span></div><SettingsSelect className="inp" id={`engine-source-${source.id}`} name="engineId" required defaultValue={source.engineId??''} disabled={!admin||action.isPending}><option value="">Choose a verified engine</option>{engines.data.filter(e=>e.verifiedAt&&e.contractVersion===2).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</SettingsSelect><Button type="submit" disabled={!admin||action.isPending||!engines.data.some(e=>e.verifiedAt&&e.contractVersion===2)}>Assign</Button>{action.isError&&action.variables?.path===`sources/${source.id}/engine`?<p role="alert" className="note">{action.error.message}</p>:null}</form>)}</div></div>;
}

function EngineEdit({projectId,engine,disabled}:{projectId:string;engine:import('../../shared/api/engines.js').EngineView;disabled:boolean}){const form=useForm({defaultValues:{name:engine.name,address:engine.address,certificatePin:engine.certificatePin}}),action=useEngineAction(projectId);return <form onSubmit={form.handleSubmit(async v=>{const p=EngineRegistration.safeParse(v);if(!p.success){form.setError('root',{message:p.error.issues.map(i=>i.message).join(' ')});return;}await action.mutateAsync({path:`engines/${engine.id}`,method:'PATCH',body:p.data}).catch(()=>undefined);})}>{(['name','address','certificatePin'] as const).map(key=><div className="fld" key={key}><label htmlFor={`edit-${engine.id}-${key}`}>{key==='name'?'Engine name':key==='address'?'Private address':'Certificate pin'}</label><input id={`edit-${engine.id}-${key}`} disabled={disabled||action.isPending} {...form.register(key)}/></div>)}<Button type="submit" disabled={disabled||action.isPending}>{action.isPending?'Saving…':'Save and require verification'}</Button>{form.formState.errors.root?<p role="alert">{form.formState.errors.root.message}</p>:null}{action.isError?<p role="alert">{action.error.message}</p>:null}</form>;}
