import {useState} from 'react';
import {createStore,useStore} from 'zustand';
import {AppRoot,Button,FindingGrid,FindingCard,SegmentedFilters,DenseList,DenseRow,GroupedRow,InlineExpansion,WeightedActionBar,RelationshipBand,Mark} from '../shared/ui/index.js';

function previewState(){return createStore<{filter:'all'|'open';open:boolean;selected:boolean}>(()=>({filter:'all',open:false,selected:true}));}
/** Development-only review surface; no backend commands or fabricated history. */
export function SharedPatternsScreen(){
 const [store]=useState(previewState),state=useStore(store);
 return <AppRoot><main className="body"><section className="screen on"><h1>Shared structural patterns</h1><p className="sub">5.28 review fixtures. Example actions are disabled; these are shared patterns, not production screens.</p>
 <FindingGrid><FindingCard title="Needs a decision" needsDecision footer={<><span className="meta">One explicit group</span><Button disabled>Decide</Button></>}><p><b>19</b> elements have no decision.</p></FindingCard><FindingCard title="Filings set aside" footer={<Button disabled>Prepare for the operator</Button>}><p>No filing-party rule matched. Nothing landed; this filing’s data is not in the catalogue.</p></FindingCard><FindingCard title="A join needs review" footer={<Button disabled>Review</Button>}><p>An attempted join needs an administrator’s judgement.</p></FindingCard></FindingGrid>
 <div className="filters"><SegmentedFilters label="Example status" value={state.filter} onChange={filter=>store.setState({filter})} options={[{value:'all',label:'All',count:2},{value:'open',label:'Open',count:1}]}/><SegmentedFilters label="Unavailable choice" value="ready" onChange={()=>{}} options={[{value:'ready',label:'Ready'},{value:'absent',label:'Unavailable',disabled:true}]}/></div>
 <section className="card"><header className="card-h"><h2>Dense rows and inline expansion</h2></header><DenseList label="Example requests" kindScope="uniform"><InlineExpansion kind="query" identity={<><b>Read one table</b><p className="meta">reinsurance.public.cedant_02_premium</p></>} metadata="harness · incomplete" id="preview-record" label="Show record" open={state.open} onToggle={()=>store.setState({open:!state.open})}><p>No completion recorded. Whether an answer reached the agent is unknown.</p><Button disabled>Open evidence record</Button></InlineExpansion><DenseRow kind="query" identity={<><Mark name="incomplete" size={16}/>{' '}<b>No completion recorded</b></>} metadata="harness" actions={<Button disabled>Record</Button>}/></DenseList></section>
 <div><section className="card"><header className="card-h"><h2>Grouped element row</h2></header><DenseList label="Example elements" kindScope="uniform"><GroupedRow kind="element" selection={<input type="checkbox" aria-label="Select written premium" checked={state.selected} onChange={e=>store.setState({selected:e.target.checked})}/>} identity={<><b>written_premium_from_the_reinsurance_landing</b><p className="meta">4 objects</p></>} type="DECIMAL(18, 2)" signal={<><Mark name="treatment-undecided" size={16} label="Undecided"/>{' '}Asked for once</>} actions={<Button disabled>Declarations</Button>}/></DenseList></section>
 {state.selected?<WeightedActionBar count={<><b>1</b> group · 4 elements</>} consequence="Applies to the explicit members in the selected pool. Prior answers remain explainable."><Button variant="ghost" onClick={()=>store.setState({selected:false})}>Cancel selection</Button><Button variant="go" disabled>Apply</Button></WeightedActionBar>:null}
 </div>
 <RelationshipBand left={<><b>written_premium</b><p className="meta">Isolated — joins only this element</p></>} right={<><b>treaty_ref</b><p className="meta">Isolated — joins only this element</p></>}/>
 <div className="scopepick" data-layout="paired" role="group" aria-label="Example domain choices"><button className="eo" type="button" disabled><span className="et"><b>Choose an existing domain</b><span>Review every member before choosing.</span></span></button><button className="eo" type="button" disabled><span className="et"><b>Declare a new domain</b><span>A name and typed confirmation belong in the form.</span></span></button></div>
 </section></main></AppRoot>;
}
