import {z} from 'zod';
import {defineRoute,errorEnvelopeSchema,cursorPagination} from '../../../platform/http/index.js';
import {EngineRegistration,EnginePage,EngineAssignment,EngineMutationResponse} from '../../../shared/api/engines.js';
import {EngineId,ProjectId,SourceId,DomainError} from '../../../shared/kernel/index.js';
import type {EngineRegistry} from '../application/registry.js';
const params=z.object({id:z.uuid(),engineId:z.uuid().optional(),sourceId:z.uuid().optional()});
const success=EngineMutationResponse;
export function engineRoutes(service:EngineRegistry){const ctx=(r:{params:{id:string};actor:{id:import('../../../shared/kernel/index.js').UserId}})=>({projectId:ProjectId(r.params.id),userId:r.actor.id});return [
 defineRoute({method:'GET',path:'/api/v1/projects/:id/engines',params,request:z.undefined(),query:z.object({cursor:z.uuid().optional(),limit:z.coerce.number().int().positive().optional()}),permission:{resource:'project',id:r=>r.params.id,permission:'view'},response:z.union([EnginePage,errorEnvelopeSchema]),handle:async r=>{const p=cursorPagination(undefined,r.query.limit);const rows=await service.list(ctx(r),r.query.cursor?EngineId(r.query.cursor):null,p.limit+1);const items=rows.slice(0,p.limit);return {body:{items,nextCursor:rows.length>p.limit?items.at(-1)!.id:null}};}}),
 defineRoute({method:'POST',path:'/api/v1/projects/:id/engines',params,request:EngineRegistration,permission:{resource:'project',id:r=>r.params.id,permission:'administer'},response:z.union([success,errorEnvelopeSchema]),handle:async r=>{const value=await service.register(ctx(r),r.body);if(!value.ok)throw value.error;return {status:201,body:{ok:true as const}};}}),
 defineRoute({method:'PATCH',path:'/api/v1/projects/:id/engines/:engineId',params,request:EngineRegistration,permission:{resource:'project',id:r=>r.params.id,permission:'administer'},response:z.union([success,errorEnvelopeSchema]),handle:async r=>{if(!r.params.engineId)throw new DomainError('validation_failed','Engine required.');const result=await service.update(ctx(r),EngineId(r.params.engineId),r.body);if(!result.ok)throw result.error;return {body:{ok:true as const}};}}),
 ...(['verify','custody'] as const).map(action=>defineRoute({method:'POST',path:`/api/v1/projects/:id/engines/:engineId/${action}`,params,request:z.strictObject({}),permission:{resource:'project',id:r=>r.params.id,permission:'administer'},response:z.union([success,errorEnvelopeSchema]),handle:async r=>{if(!r.params.engineId)throw new DomainError('validation_failed','Engine required.');const result=action==='verify'?await service.verify(ctx(r),EngineId(r.params.engineId)):await service.designate(ctx(r),EngineId(r.params.engineId));if(!result.ok)throw result.error;return {body:{ok:true as const}};}})),
 defineRoute({method:'PATCH',path:'/api/v1/projects/:id/sources/:sourceId/engine',params,request:EngineAssignment,permission:{resource:'project',id:r=>r.params.id,permission:'administer'},response:z.union([success,errorEnvelopeSchema]),handle:async r=>{if(!r.params.sourceId)throw new DomainError('validation_failed','Source required.');const result=await service.assign(ctx(r),SourceId(r.params.sourceId),r.body.engineId);if(!result.ok)throw result.error;return {body:{ok:true as const}};}}),
 ];}
