import {Timestamp} from '../settings/preferences.js';
import {useEngines} from '../engines/data.js';
import {EngineId} from '../../shared/kernel/value-objects.js';
import { z } from 'zod';
import { Link } from '@tanstack/react-router';
import { type FormEvent,type ReactNode } from 'react';
import { Button,EmptyState,ErrorState,LoadingState,ConsoleSelect,Mark,ExposureSpectrum } from '../../shared/ui/index.js';
import { CreateSourceBody } from '../../shared/api/source-schemas.js';
import { useProjects } from '../tenancy/data.js';
import { useConnectSource,useDemos,useSources,useTestSource,useRetrySource } from './data.js';
import { useSourceUi,useFilingExpansion,useSourceListUi } from './state.js';
import { SourceFilings,landingLabels } from '../filings/screens.js';

function Wizard({projectId,industryId}:{projectId:string;industryId:string}):ReactNode{
 const engines=useEngines(projectId);const ui=useSourceUi();const test=useTestSource(projectId);const connect=useConnectSource(projectId,industryId);const form=ui.form;
 async function submit(event:FormEvent){event.preventDefault();if(ui.step===1){const result=await test.mutateAsync({credentialRef:form.credentialRef,engineId:form.engineId}).catch(()=>null);if(result?.reachable)ui.next();}else{const parsed=CreateSourceBody.safeParse(form);if(!parsed.success)return;await connect.mutateAsync(parsed.data).then(()=>ui.close()).catch(()=>undefined);}}
 return <section className="card" aria-labelledby="connect-heading" style={{marginBottom:16}}><div className="card-h"><h2 id="connect-heading">Connect a source</h2><span className="meta">Step {ui.step} of 2</span></div><form className="sheetb" onSubmit={event=>{void submit(event);}}>
 <p className="note">PostgreSQL · Source contact goes through your Opintel Engine. Supply an operator-configured Secret reference, never a password or connection string.</p>
 {ui.step===1?<><div className="fld"><label htmlFor="source-engine">Verified engine</label><ConsoleSelect className="inp" id="source-engine" required value={form.engineId??''} onChange={e=>ui.edit({engineId:e.target.value?EngineId(e.target.value):undefined})}><option value="">Choose an engine</option>{engines.data?.filter(e=>e.verifiedAt&&e.contractVersion===2).map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</ConsoleSelect>{engines.isError?<p role="alert">{engines.error.message}</p>:null}</div><div className="fld"><label htmlFor="source-name">Source name</label><input id="source-name" required maxLength={80} value={form.name} onChange={e=>ui.edit({name:e.target.value})}/></div><div className="fld"><label htmlFor="source-ref">Secret reference</label><input id="source-ref" required pattern="secret://.+" placeholder="secret://sources/reporting" value={form.credentialRef} onChange={e=>{ui.edit({credentialRef:e.target.value});test.reset();}}/></div></>:<>
 <p className="note" role="status">Connection passed. Choose the schemas and how this source receives data.</p>
 <fieldset className="seg"><legend>Schemas</legend><p className="note">No selection means every readable schema, excluding system schemas.</p>{test.data?.schemas.length===0?<p>No readable objects were found. You can connect and introspect again when they exist.</p>:test.data?.schemas.map(schema=><label key={schema} style={{display:'block'}}><input type="checkbox" checked={form.includeSchemas.includes(schema)} onChange={e=>ui.edit({includeSchemas:e.target.checked?[...form.includeSchemas,schema]:form.includeSchemas.filter(s=>s!==schema)})}/> <span className="mono">{schema}</span></label>)}</fieldset>
 <div className="seg"><label><input type="checkbox" checked={form.samplingConsent} onChange={e=>ui.edit({samplingConsent:e.target.checked})}/> Allow value sampling</label><p className="note">Optional. Introspection reads structure only. Sampling permits top values to be read by the Opintel Engine.</p></div>
 <div className="seg"><label><input type="checkbox" checked={form.receivesLandings} onChange={e=>ui.edit({receivesLandings:e.target.checked,landingStrategy:null})}/> This source receives landed spreadsheets</label></div>
 {form.receivesLandings?<div className="fld"><label htmlFor="source-strategy">Landing strategy</label><span className="pick"><ConsoleSelect id="source-strategy" required value={form.landingStrategy??''} onChange={e=>{const value=e.target.value;if(value==='append_as_at'||value==='table_per_filing')ui.edit({landingStrategy:value});}}><option value="">Choose a strategy</option><option value="append_as_at">Append as at</option><option value="table_per_filing">Table per filing</option></ConsoleSelect></span><p className="hint">Append as at retains filings together with provenance. Table per filing creates a separate table for each filing. The first landing fixes the strategy.</p></div>:null}
 </>}
 {test.isError||connect.isError?<p className="note" role="alert">{connect.error?.message??test.error?.message}</p>:null}
 {test.data&&!test.data.reachable?<p className="note" role="alert">{test.data.reason??'The source could not be reached.'}</p>:null}
 <div className="filters"><Button variant="go" type="submit" disabled={test.isPending||connect.isPending}>{test.isPending?'Testing…':connect.isPending?'Connecting…':ui.step===1?'Test connection':'Connect and introspect'}</Button><Button variant="ghost" disabled={connect.isPending} onClick={ui.close}>Cancel</Button></div>
 </form></section>;
}
export function SourcesScreen({projectId}:{projectId:string}):ReactNode{
 const retry=useRetrySource(projectId),expansion=useFilingExpansion(),listUi=useSourceListUi(),engines=useEngines(projectId);
 const activeRun=z.uuid().safeParse(retry.error?.code==='conflict'?retry.error.details?.runId:undefined);
 const feedback=(sourceId:string)=>retry.variables===sourceId&&retry.isError?<p className="note" role="alert">{retry.error.message}{activeRun.success?<> <Link to="/projects/$projectId/introspections/$runId" params={{projectId,runId:activeRun.data}}>View active run</Link></>:null}</p>:retry.data?.id===sourceId&&retry.data.latestIntrospectionId?<p className="note" role="status">Introspection started. <Link to="/projects/$projectId/introspections/$runId" params={{projectId,runId:retry.data.latestIntrospectionId}}>View started run</Link></p>:null;
 const projects=useProjects(),sources=useSources(projectId),project=projects.data?.find(p=>p.id===projectId),industryId=project?.industry.id??'';
 const demos=useDemos(projectId,industryId),connect=useConnectSource(projectId,industryId),ui=useSourceUi(),open=ui.open&&ui.projectId===projectId,canConnect=project?.role==='admin';
 const pools=sources.data?.[0]?.decisionPools??[];const poolId=pools.find(p=>p.id===listUi.poolByProject[projectId])?.id??pools[0]?.id;
 const poolDecision=(source:NonNullable<typeof sources.data>[number])=>source.decisionPools?.find(p=>p.id===poolId);
 const needsAttention=(source:NonNullable<typeof sources.data>[number])=>(poolDecision(source)?.undecidedCount??0)>0||source.status!=='connected'||(source.quarantinedCount??0)>0;
 const shown=sources.data?.filter(s=>!listUi.attention||needsAttention(s))??[];
 return <section className="screen on" data-layout="sources"><h1>Data sources</h1><p className="sub">What Opintel sits in front of for this project. Agents never reach these directly.</p>
 <div className="filters" data-part="source-toolbar">{pools.length?<div className="pick"><label htmlFor="source-pool">Pool</label><ConsoleSelect id="source-pool" value={poolId} onChange={e=>listUi.choosePool(projectId,e.target.value)}>{pools.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</ConsoleSelect></div>:null}<div className="segbtns" aria-label="Source filter"><button type="button" aria-pressed={!listUi.attention} onClick={()=>listUi.filter(false)}>All {sources.data?.length??0}</button><button type="button" aria-pressed={listUi.attention} onClick={()=>listUi.filter(true)}>Needs attention {sources.data?.filter(needsAttention).length??0}</button></div>{canConnect&&!open?<Button variant="go" onClick={()=>ui.show(projectId)}>Connect a source</Button>:null}</div>
 {projects.isError?<ErrorState title="Project could not be loaded" description={projects.error.message} retry={()=>projects.refetch()}/>:null}
 {open?<><Wizard key={projectId} projectId={projectId} industryId={industryId}/> <section className="card"><div className="card-h"><h2>Demo data</h2><span className="meta">from this project's industry pack</span></div><div className="sheetb"><p className="note">Demo sources use the same connector and ingest path as customer sources. Preparing a pack connects nothing; connection happens only when you choose it.</p>
 {demos.isPending?<LoadingState/>:demos.isError?<ErrorState title="Demo pack could not be loaded" description={demos.error.message} retry={()=>demos.refetch()}/>:demos.data.length===0?<EmptyState title="No demo pack for this industry" description="Connect an operator-configured Postgres source to begin."/>:<div className="demopick" style={{gridTemplateColumns:'repeat(auto-fit, minmax(min(100%, 258px), 1fr))'}}>{demos.data.map(demo=><article className={demo.connected?'dcard done':'dcard'} key={demo.id}><b>{demo.name}</b><span className="d">{demo.narrative}</span><div className="act">{demo.connected?<span className="already">Already connected to this project</span>:!demo.prepared?<span className="already">Not provisioned for this project. Ask the deployment operator to prepare this pack.</span>:canConnect?<Button variant="go" disabled={connect.isPending} onClick={()=>connect.mutate({demoTemplateId:demo.id})}>{connect.isPending?'Connecting…':'Connect'}</Button>:<span className="already">Ask a project administrator to connect this pack.</span>}</div>{connect.isError&&'demoTemplateId' in connect.variables&&connect.variables.demoTemplateId===demo.id?<p className="note" role="alert">{connect.error.message}</p>:null}</article>)}</div>}

 </div></section></>:null}
 {sources.isPending?<LoadingState/>:sources.isError?<ErrorState title="Sources could not be loaded" description={sources.error.message} retry={()=>sources.refetch()}/>:sources.data.length===0?<EmptyState title="No sources connected" description={canConnect?'Connect a source to discover its structure. Every field remains unreadable until access is explicitly decided.':'Ask a project administrator to connect the first source.'}/>:shown.length===0?<EmptyState title="No sources need attention" description="All connected sources have decisions and no recorded quarantine."/>:shown.map(source=><section className="card" key={source.id} aria-label={source.name}>
 <div className="card-h" data-part="source-heading"><div><div data-part="source-title"><b data-part="source-name">{source.name}</b> {source.exposedAlias!==source.name?<span className="mono">{source.exposedAlias}</span>:null} {source.origin==='demo'?<span className="obadge demo">Demo data</span>:null}<span className={source.status==='connected'?'tr clear':'tr wait'}><Mark name={source.status==='connected'?'healthy':'needs-a-decision'} size={17}/>{source.status==='introspection_failed'&&source.latestIntrospectionId?<Link to="/projects/$projectId/introspections/$runId" params={{projectId,runId:source.latestIntrospectionId}}>introspection failed</Link>:source.status==='connected'?'Connected':source.status.replaceAll('_',' ')}</span></div><div className="meta">PostgreSQL{source.landingStrategy?<> · landing zone <b style={{whiteSpace:'nowrap',textAlign:'left'}}>{landingLabels[source.landingStrategy]}</b></>:null} · read by {engines.data?.find(e=>e.id===source.engineId)?.name??(source.engineId?'Engine name unavailable':'No engine assigned')} · last introspected <Link aria-label={`Introspection runs for ${source.name}`} to="/projects/$projectId/sources/$sourceId/introspections" params={{projectId,sourceId:source.id}}>{source.lastIntrospectedAt?<Timestamp value={source.lastIntrospectedAt}/>:'Never'}</Link></div></div><div className="filters"><Link className="toolchip" aria-label={`Explore schema for ${source.name}`} to="/projects/$projectId/$screen" params={{projectId,screen:'catalog'}} search={{sourceId:source.id}}>Explore schema</Link>{source.filingCount!==null?<button className="toolchip" type="button" aria-expanded={!!expansion.expanded[projectId+':'+source.id]} aria-controls={`filings-${source.id}`} onClick={()=>expansion.toggle(projectId,source.id)}>{source.filingCount} {source.filingCount===1?'filing':'filings'}</button>:null}{canConnect&&source.status!=='archived'?<Button variant="ghost" disabled={retry.isPending} onClick={()=>retry.start(source.id)}>{retry.isPending&&retry.variables===source.id?'Starting…':'Re-introspect'}</Button>:null}</div></div>
 {source.error?<p className="note" role="alert">{source.error}</p>:null}{feedback(source.id)}
 <div data-part="source-facts"><div data-part="source-fact"><div className="meta">Elements</div><div data-part="fact-value">{source.elementCount}</div><div className="meta">{source.objectCount??'Unknown'} objects · {source.unsupportedCount} unsupported</div></div><div data-part="source-fact" data-state={poolDecision(source)?.undecidedCount?'attention':undefined}><div className="meta">Awaiting decision</div><div data-part="fact-value">{poolDecision(source)?.undecidedCount??'—'}</div>{poolId?<Link to="/projects/$projectId/$screen" params={{projectId,screen:'entitlements'}} search={{sourceId:source.id,poolId,decision:'undecided'}}>Review decisions</Link>:<span className="meta">{source.decisionPools?'No pools yet':'Pool decisions unavailable'}</span>}</div><div data-part="source-fact"><div className="meta">Filings</div><div data-part="fact-value">{source.filingCount??'—'}</div><div className="meta">{source.filingCount===null?'No landing zone':`${source.filingCount} landed · ${source.quarantinedCount??'Unknown'} set aside`}</div></div><div data-part="source-fact"><div className="meta">Last landed</div><div data-part="last-landed">{source.lastLandedAt?<Timestamp value={source.lastLandedAt}/>:source.lastLandedAt===null&&source.filingCount===0?'Never':'Not recorded'}</div></div></div>
 {poolDecision(source)?<div data-part="source-exposure"><ExposureSpectrum decisions={poolDecision(source)!.decisions} compact/></div>:null}
 {source.filingCount!==null?<div id={`filings-${source.id}`} hidden={!expansion.expanded[projectId+':'+source.id]}>{expansion.expanded[projectId+':'+source.id]?<SourceFilings projectId={projectId} sourceId={source.id} strategy={source.landingStrategy}/>:null}</div>:null}
 </section>)}
 <p className="note">A source belongs to one project. Queries run in place; spreadsheet ingest lands files into your own landing database. Files never leave your environment.</p>
 </section>;
}
