import {useMutation,useQuery,useQueryClient} from '@tanstack/react-query';
import { readDeclarations,saveDeclarations,SchemaDeclarations,schemaDeclarationsPath,type ElementDeclarations,type DeclarationCommand } from '../../shared/api/declarations.js';
import {createApiClient,type AppError} from '../../shared/api/index.js';
import {elementKeys} from './data.js';
import {entitlementKeys} from '../entitlements/data.js';
import {projectKeys} from '../tenancy/data.js';
export function useDeclarations(project:string,element:string){return useQuery({queryKey:elementKeys.declaration(project,element),retry:false,queryFn:async()=>{const result=await readDeclarations(project,element);if(!result.ok)throw result.error;return result.value;}});}
export function useSchemaDeclarations(project:string,id:string){const split=id.indexOf(':'),source=id.slice(0,split),schema=id.slice(split+1);return useQuery({queryKey:elementKeys.schemaDeclaration(project,id),retry:false,queryFn:async()=>{const result=await createApiClient().request({path:schemaDeclarationsPath(project,source,schema),response:SchemaDeclarations});if(!result.ok)throw result.error;return result.value;}});}
export function useDeclarationSave(project:string,element:string){const cache=useQueryClient();return useMutation<ElementDeclarations,AppError,DeclarationCommand>({mutationFn:async body=>{const result=await saveDeclarations(project,element,body);if(!result.ok)throw result.error;return result.value;},onSuccess:async()=>{await Promise.all([elementKeys.lists(project),elementKeys.declarations(project),entitlementKeys.all(project),projectKeys.stats(project)].map(queryKey=>cache.invalidateQueries({queryKey})));}});}
export function useSchemaDeclarationSave(project:string,id:string){const cache=useQueryClient(),split=id.indexOf(':'),source=id.slice(0,split),schema=id.slice(split+1);return useMutation<unknown,AppError,{sourceTimezone:string|null;confirmation?:string}>({mutationFn:async body=>{const result=await createApiClient().request({path:schemaDeclarationsPath(project,source,schema),method:'PUT',body,response:SchemaDeclarations});if(!result.ok)throw result.error;return result.value;},onSuccess:async()=>{await Promise.all([elementKeys.lists(project),elementKeys.declarations(project),entitlementKeys.all(project),projectKeys.stats(project)].map(queryKey=>cache.invalidateQueries({queryKey})));}});}
