import {ProjectId,ElementId} from '../../shared/kernel/value-objects.js';
import {useMemo} from 'react';
import {useStore} from 'zustand';
import type {z} from 'zod';
import {DeclarationCommand,ElementDeclarations,SchemaDeclarations,type DeclarationValues} from '../../shared/api/declarations.js';
import {effectiveDeclarations,tokenBehaviour,standardCanonicaliser} from '../../shared/token-declarations.js';
import {Button,LoadingState,ErrorState,EmptyState} from '../../shared/ui/index.js';
import {useDeclarations,useDeclarationSave,useSchemaDeclarations,useSchemaDeclarationSave} from './declaration-data.js';
import {createDeclarationForm,createSchemaDeclarationForm} from './declaration-state.js';
import {useProjects} from '../tenancy/data.js';
import type {AppError} from '../../shared/api/index.js';
const integerTypes=['TINYINT','SMALLINT','INTEGER','BIGINT','HUGEINT'];
const display=(value:string|boolean|null)=>value===null?'Not declared':typeof value==='boolean'?value?'Enabled':'Disabled':value;
const domainDisplay=(stored:string|null,effective:string)=>stored===null?'Isolated — joins only this element':effective;
function DerivedDomain({domain,open,onToggle}:{domain:string;open:boolean;onToggle:(open:boolean)=>void}){return <details className="hint" open={open} onToggle={e=>onToggle(e.currentTarget.open)}><summary>Show derived domain</summary><p>Derived from element identity. For token diagnostics.</p><code className="mono" style={{display:'block',overflowWrap:'anywhere'}}>{domain}</code></details>;}
export function DeclarationPanel({projectId,elementId,onSchema}:{projectId:string;elementId:string;onSchema:(id:string)=>void}){
 const query=useDeclarations(projectId,elementId),projects=useProjects(),save=useDeclarationSave(projectId,elementId);
 if(query.isPending||projects.isPending)return <LoadingState/>;
 if(query.isError||projects.isError)return <ErrorState title="Declarations could not be loaded" description={(query.error as AppError|null)?.message??projects.error?.message??'Try again.'} retry={()=>Promise.all([query.refetch(),projects.refetch()])}/>;
 if(!query.data)return <EmptyState icon="⊟" title="No element selected" description="Select an element to inspect its declarations."/>;
 return <ElementForm key={JSON.stringify(query.data.stored)+query.data.schemaTimezone} projectId={projectId} data={query.data} save={save} admin={projects.data?.find(p=>p.id===projectId)?.role==='admin'} onSchema={onSchema}/>;
}
function ElementForm({projectId,data,admin,onSchema,save}:{projectId:string;save:ReturnType<typeof useDeclarationSave>;data:z.infer<typeof ElementDeclarations>;admin:boolean;onSchema:(id:string)=>void}){
 const store=useMemo(()=>createDeclarationForm(data.stored),[data.stored]),state=useStore(store);
 const identity={projectId:ProjectId(projectId),elementId:ElementId(data.elementId)};
 const values=state.values,effective=effectiveDeclarations(data.exposedType,values,data.schemaTimezone,identity),changed=JSON.stringify(values)!==JSON.stringify(data.stored);
 const breaking=data.tokenizedEntitlements>0&&tokenBehaviour(data.exposedType,values,data.schemaTimezone,identity)!==tokenBehaviour(data.exposedType,data.stored,data.schemaTimezone,identity);
 const text=data.exposedType==='VARCHAR'||data.exposedType==='UUID',epoch=integerTypes.includes(data.exposedType??''),disabled=!admin||save.isPending||data.exposedType===null;
 const requiredCanon=standardCanonicaliser(data.exposedType,values.epochUnit);
 const compatible=(id:string)=>id===requiredCanon||(text&&requiredCanon==='stdtext1'&&!['stdtext1','stdnum1','stddate1','stdtime1'].includes(id));
 const conflict=values.canonId!==null&&!compatible(values.canonId);
 function fieldError(field:keyof DeclarationValues|'confirmation'){if(state.errors[field])return <p className="hint" role="alert">{state.errors[field]}</p>;return save.error?.details?.fields instanceof Array&&save.error.details.fields.includes(field)?<p className="hint" role="alert">{save.error.message}</p>:null;}
 return <form className="card" aria-label="Element declarations" onSubmit={e=>{e.preventDefault();const parsed=DeclarationCommand.safeParse({...values,...(breaking?{confirmation:state.confirmation}:{})});if(!parsed.success){state.invalid(Object.fromEntries(parsed.error.issues.map(issue=>[String(issue.path[0]??'declarations'),issue.message])));return;}save.mutate(parsed.data);}}>
 <div className="card-h"><h2>Token declarations</h2><span className="meta" style={{whiteSpace:'normal',overflowWrap:'anywhere',minWidth:0}}>{data.qualifiedName}</span></div><div className="sheetb">
 <p className="mono" style={{overflowWrap:'anywhere'}}>Element: {data.qualifiedName} · Type: {data.exposedType??'Unsupported'}</p>
 {!admin?<p className="note">Read-only. A project administrator declares these properties.</p>:null}
 <p className="note">Stored declarations are decisions. Effective values below identify defaults and inheritance separately.</p>
 <div className="fld"><label htmlFor="declaration-domain">Token domain</label><input id="declaration-domain" value={values.tokenDomain??''} disabled={disabled} onChange={e=>state.edit({tokenDomain:e.target.value||null})}/><p className="hint" style={{overflowWrap:'anywhere'}}>Stored: {display(data.stored.tokenDomain)}. Effective: {domainDisplay(data.stored.tokenDomain,data.effective.tokenDomain)}{data.stored.tokenDomain!==null?' — declared':''}. Declaring a shared domain enables cross-element joins. Lowercase letters and digits; sentinel and opintelisolated domains are reserved.</p>{data.stored.tokenDomain===null?<DerivedDomain domain={data.effective.tokenDomain} open={state.derivedDomainOpen} onToggle={state.showDerivedDomain}/>:null}{fieldError('tokenDomain')}</div>
 <div className="fld"><label htmlFor="declaration-case">Case folding</label><select className="inp" id="declaration-case" value={values.caseInsensitive===null?'':String(values.caseInsensitive)} disabled={disabled||(!text&&values.caseInsensitive===null)} onChange={e=>state.edit({caseInsensitive:e.target.value===''?null:e.target.value==='true'})}><option value="">Not declared — use default</option><option value="true" disabled={!text}>Enabled</option><option value="false" disabled={!text}>Disabled</option></select><p className="hint">Stored: {display(data.stored.caseInsensitive)}. Effective: {display(data.effective.caseInsensitive)}{text?(data.stored.caseInsensitive===null?' — default':' — declared'):' — not text mode'}.</p>{fieldError('caseInsensitive')}</div>
 <div className="fld"><label htmlFor="declaration-zone">Element source timezone</label><input id="declaration-zone" value={values.sourceTimezone??''} disabled={disabled} onChange={e=>state.edit({sourceTimezone:e.target.value||null})}/><p className="hint">Stored on element: {display(data.stored.sourceTimezone)}. Schema declaration: {display(data.schemaTimezone)}. Effective: {data.effective.sourceTimezone??'Missing'}{data.stored.sourceTimezone!==null?' — element declaration':data.schemaTimezone!==null?' — inherited from schema':' — no host timezone is assumed'}. Used for tokenized timestamps without a zone; other modes do not use this timezone. An IANA name such as America/Toronto.</p>{fieldError('sourceTimezone')}<Button type="button" variant="ghost" onClick={()=>onSchema(`${data.sourceId}:${data.schemaName}`)}>Edit schema timezone</Button></div>
 <div className="fld"><label htmlFor="declaration-epoch">Epoch unit</label><select className="inp" id="declaration-epoch" value={values.epochUnit??''} disabled={disabled||(!epoch&&values.epochUnit===null)} onChange={e=>state.edit({epochUnit:e.target.value==='seconds'?'seconds':e.target.value==='milliseconds'?'milliseconds':null})}><option value="">Not declared</option><option value="seconds" disabled={!epoch}>Seconds</option><option value="milliseconds" disabled={!epoch}>Milliseconds</option></select><p className="hint">Stored: {display(data.stored.epochUnit)}. Effective mode: {data.effective.mode}. Integer columns only; never inferred from magnitude.</p>{fieldError('epochUnit')}</div>
 <div className="fld"><label htmlFor="declaration-canon">Canonicaliser</label><select className="inp" id="declaration-canon" value={values.canonId??''} disabled={disabled||data.discoveryError!==null} onChange={e=>state.edit({canonId:e.target.value||null})}><option value="">Not assigned — derive standard ({requiredCanon})</option>{[...new Set([...data.canonicalisers,...(values.canonId?[values.canonId]:[])])].map(id=><option key={id} value={id} disabled={!compatible(id)}>{id}{!compatible(id)?' — incompatible with proposed mode':''}</option>)}</select><p className="hint">Stored: {data.stored.canonId??'Not assigned'}. Effective: {data.effective.canonId}{data.stored.canonId===null?' — derived from mode':' — explicitly assigned'}. Choices are advertised by this source's Engine.</p>{fieldError('canonId')}{data.discoveryError?<p className="note">Canonicaliser discovery unavailable: {data.discoveryError}</p>:null}</div>
 {conflict?<p role="alert" className="note">The explicit canonicaliser {values.canonId} conflicts with the proposed mode, which requires {requiredCanon}. Keep the mode or deliberately choose a compatible canonicaliser in this save. Nothing is silently overridden.</p>:null}
 {changed?<div className="joinbox" style={{overflowWrap:'anywhere'}}><b>{data.stored.tokenDomain===null&&values.tokenDomain!==null?'Declare token domain':values.tokenDomain!==data.stored.tokenDomain?'Change token domain':'Change declarations'}</b><p>Proposed effective domain: {domainDisplay(values.tokenDomain,effective.tokenDomain)} · Mode: {effective.mode} · Canonicaliser: {effective.canonId} · Case folding: {display(effective.caseInsensitive)} · Timezone: {effective.sourceTimezone??'Missing'} · Epoch: {display(effective.epochUnit)}.</p>{values.tokenDomain===null&&data.stored.tokenDomain!==null?<DerivedDomain domain={effective.tokenDomain} open={state.derivedDomainOpen} onToggle={state.showDerivedDomain}/>:null}<p>{data.tokenizedEntitlements} tokenized entitlement{data.tokenizedEntitlements===1?'':'s'} across all pools. {breaking?'Subsequent tokens will differ. Previously issued tokens will no longer match them. Past evidence keeps the key version and declarations used for its answer.':'This does not change effective tokenization for any already-tokenized element.'}</p></div>:null}
 {breaking?<div className="fld"><label htmlFor="declaration-confirm">Type project name: {data.projectName}</label><input id="declaration-confirm" value={state.confirmation} disabled={disabled} onChange={e=>state.confirm(e.target.value)} autoComplete="off"/>{fieldError('confirmation')}</div>:null}
 {save.isError?<p role="alert" className="note">{save.error.message}</p>:null}{save.isSuccess?<p role="status" className="note">Declarations saved.</p>:null}
 <Button type="submit" disabled={disabled||!changed||conflict||(breaking&&state.confirmation!==data.projectName)}>{save.isPending?'Saving…':data.stored.tokenDomain===null&&values.tokenDomain!==null?'Declare token domain':'Save declarations'}</Button>
 </div></form>;
}
export function SchemaDeclarationPanel({projectId,schemaId}:{projectId:string;schemaId:string}){
 const query=useSchemaDeclarations(projectId,schemaId),projects=useProjects(),save=useSchemaDeclarationSave(projectId,schemaId);
 if(query.isPending||projects.isPending)return <LoadingState/>;
 if(query.isError||projects.isError)return <ErrorState title="Schema declaration could not be loaded" description={(query.error as AppError|null)?.message??projects.error?.message??'Try again.'} retry={()=>Promise.all([query.refetch(),projects.refetch()])}/>;
 if(!query.data)return <EmptyState icon="⊟" title="No schema selected" description="Select an element, then edit its schema timezone."/>;
 return <SchemaForm key={query.data.sourceTimezone} projectId={projectId} schemaId={schemaId} data={query.data} save={save} admin={projects.data?.find(p=>p.id===projectId)?.role==='admin'}/>;
}
function SchemaForm({data,admin,save}:{projectId:string;schemaId:string;save:ReturnType<typeof useSchemaDeclarationSave>;data:z.infer<typeof SchemaDeclarations>;admin:boolean}){
 const store=useMemo(()=>createSchemaDeclarationForm(data.sourceTimezone),[data.sourceTimezone]),state=useStore(store);
 const changed=(state.zone||null)!==data.sourceTimezone,breaking=changed&&data.tokenizedInheritors>0;
 return <form className="card" aria-label="Schema declarations" onSubmit={e=>{e.preventDefault();save.mutate({sourceTimezone:state.zone||null,...(breaking?{confirmation:state.confirmation}:{})});}}><div className="card-h"><h2>Schema timezone declaration</h2><span className="meta" style={{whiteSpace:'normal',overflowWrap:'anywhere',minWidth:0}}>{data.qualifiedName}</span></div><div className="sheetb"><div className="fld"><label htmlFor="schema-timezone">Schema source timezone</label><input id="schema-timezone" value={state.zone} disabled={!admin||save.isPending} onChange={e=>state.edit(e.target.value)}/><p className="hint">Stored: {display(data.sourceTimezone)}. Elements inherit this only when they have no explicit timezone. No host timezone is assumed.</p></div>{breaking?<><p className="note">This changes effective tokenization for {data.tokenizedInheritors} tokenized timestamp entitlement{data.tokenizedInheritors===1?'':'s'}. Previously issued tokens will no longer match subsequent tokens. Past evidence retains its original declarations.</p><div className="fld"><label htmlFor="schema-confirm">Type project name: {data.projectName}</label><input id="schema-confirm" value={state.confirmation} disabled={!admin||save.isPending} onChange={e=>state.confirm(e.target.value)}/></div></>:null}{!admin?<p className="note">Read-only. A project administrator changes this declaration.</p>:null}{save.isError?<p role="alert" className="note">{save.error.message}</p>:null}{save.isSuccess?<p role="status">Schema declaration saved.</p>:null}<Button type="submit" disabled={!admin||save.isPending||!changed||(breaking&&state.confirmation!==data.projectName)}>{save.isPending?'Saving…':'Save schema timezone'}</Button></div></form>;
}
