import { AsyncButton } from '../../shared/ui/index.js';
import {Timestamp as DisplayTimestamp} from '../settings/preferences.js';
import {Link} from '@tanstack/react-router';
import {EmptyState,ErrorState,LoadingState} from '../../shared/ui/index.js';
import type {DashboardFinding,Spectrum,PoolShield} from '../../shared/api/dashboard.js';
import {useDashboard,useDashboardFeed,useShields} from './data.js';
import {useTokenKey} from '../custody/data.js';
import {quarantineLabels,QuarantineResolutionSummary} from '../filings/screens.js';
import {useDashboardDisclosure} from './state.js';
const treatments=[['clear','In the clear','var(--green)'],['tokenized','Tokenized','var(--token)'],['masked','Masked','var(--mask)'],['aggregate_only','Aggregate only','var(--agg)'],['withheld','Withheld','var(--held)'],['undecided','Undecided','var(--yellow)']] as const;
const total=(s:Spectrum)=>Object.values(s).reduce((a,b)=>a+b,0);
const ratio=(n:number,d:number)=>d?`${Math.round(n/d*1000)/10}%`:'n/a';
function Ring({value,denominator,small=false}:{value:number;denominator:number;small?:boolean}){const size=small?54:176,center=size/2,r=small?22:72,circumference=2*Math.PI*r;return <svg aria-hidden="true" width={size} height={size} viewBox={`0 0 ${size} ${size}`}><circle cx={center} cy={center} r={r} fill="none" stroke="var(--surface-3)" strokeWidth={small?6:16}/>{denominator?<circle cx={center} cy={center} r={r} fill="none" stroke="var(--green)" strokeWidth={small?6:16} strokeDasharray={circumference} strokeDashoffset={circumference*(1-value/denominator)}/>:null}</svg>;}
function SpectrumBar({spectrum,small=false}:{spectrum:Spectrum;small?:boolean}){return <span className={small?'mb':'bar'} aria-hidden="true" style={small?undefined:{display:'flex'}}>{treatments.map(([key,,color])=>spectrum[key]?<i key={key} style={{display:'block',flex:spectrum[key],background:color}}/>:null)}</span>;}
function Setup({projectId}:{projectId:string}){return <div className="setup">{[['Connect a source','Opintel introspects it and builds a catalogue. Nothing is readable until you say so.','data-sources'],['Create a pool','Generate a key for your agents. Bind the pool to the sources it may reach.','pools'],['Decide what it sees','Set entitlements for the pool. Anything undecided stays out of reach.','entitlements']].map(([title,description,screen],i)=><div className={i===0?'stepcard now':'stepcard'} key={screen}><div className="num">{i+1}</div><b>{title}</b><p>{description}</p><Link className={i===0?'btn go':'btn ghost'} to="/projects/$projectId/$screen" params={{projectId,screen:screen!}}>{i===2?'Open entitlements':title}</Link></div>)}</div>;}
function Finding({finding:f,projectId}:{finding:DashboardFinding;projectId:string}){return <li><span className={f.kind==='source_failure'?'sev lo':'sev hi'} aria-hidden="true">{f.kind==='source_failure'?'·':'!'}</span><div className="fb">{f.kind==='undecided'?<><p className="t">{f.count} undecided decisions · {f.poolName} · {f.sourceName}</p><p className="d">These fields remain unreadable in this pool until an entitlement is set.</p><Link style={{color:'var(--ink)'}} to="/projects/$projectId/$screen" params={{projectId,screen:'entitlements'}} search={{poolId:f.poolId,sourceId:f.sourceId,undecided:true}}>Review decisions</Link></>:f.kind==='source_failure'?<><p className="t">{f.sourceName} · source introspection failed</p><p className="d">{f.message??'Introspection did not complete. Review this source and retry after correcting the cause.'}</p>{f.runId?<Link style={{color:'var(--ink)'}} to="/projects/$projectId/introspections/$runId" params={{projectId,runId:f.runId}}>Review failed run</Link>:<Link style={{color:'var(--ink)'}} to="/projects/$projectId/$screen" params={{projectId,screen:'data-sources'}}>Review source and retry</Link>}</>:<><p className="t">{quarantineLabels[f.category]}</p><p className="d">Category: <span className="mono">{f.category}</span></p><p className="d"><DisplayTimestamp value={f.receivedAt}/></p><QuarantineResolutionSummary zoneId={f.zoneId} filingId={f.filingId}/></>}</div></li>;}
function Shield({pool:p,projectId}:{pool:PoolShield;projectId:string}){const disclosure=useDashboardDisclosure(state=>state.expanded),toggle=useDashboardDisclosure(state=>state.toggle);return <article className="shield"><div className="sh"><div className="mini"><Ring value={p.spectrum.clear} denominator={total(p.spectrum)} small/><b>{ratio(p.spectrum.clear,total(p.spectrum))}</b></div><div><h3 style={{margin:0}}><Link style={{color:'var(--ink)'}} to="/projects/$projectId/pools/$poolId" params={{projectId,poolId:p.id}}>{p.name}</Link></h3><span className="agents">{p.agents} agents seen · {p.sources.length} sources · in the clear</span></div></div><div className="rows">{p.sources.map(source=>{const key=`counts-${p.id}-${source.id}`,expanded=disclosure[`${projectId}:${key}`]??false;return <div className="r" key={source.id}><span className="nmm">{source.name}</span><SpectrumBar spectrum={source.spectrum} small/><span className="mono">{ratio(source.spectrum.clear,total(source.spectrum))}</span><button type="button" className="toolchip" aria-label={`Treatment counts for ${p.name}, ${source.name}`} aria-expanded={expanded} aria-controls={key} onClick={()=>toggle(projectId,key)}>Counts</button><div id={key} hidden={!expanded}>{treatments.map(([kind,label])=><div key={kind}>{label}: <span className="mono">{source.spectrum[kind]}</span></div>)}</div></div>;})}</div></article>;}
export function DashboardScreen({projectId,name,admin}:{projectId:string;name:string;admin:boolean}){
 const stats=useDashboard(projectId),feed=useDashboardFeed(projectId),pools=useShields(projectId),custody=useTokenKey(projectId,admin);
 const findings=feed.data?.pages.flatMap(p=>p.items)??[],failures=admin?custody.data?.versions.filter(v=>v.lastRehearsal==='failed'||v.lastRehearsal==='mismatch')??[]:[];
 const s=stats.data;const refresh=()=>Promise.all([stats.refetch(),feed.refetch(),pools.refetch(),...(admin?[custody.refetch()]:[])]);
 return <section className="screen on"><h1>{name}</h1><p className="sub">Current access decisions and recorded activity in this project. Daily counts use UTC.</p><div className="filters"><AsyncButton variant="ghost" pendingLabel="Refreshing…" refusal={stats.error?.message??feed.error?.message??pools.error?.message??(admin?custody.error?.message:null)??null} run={refresh}>Refresh dashboard</AsyncButton></div>
 {stats.isPending?<LoadingState/>:stats.isError?<ErrorState title="Dashboard could not be loaded" description={stats.error.message} retry={refresh}/>:s?<>
 {!s.sources||!s.pools?<Setup projectId={projectId}/>:null}
 {!s.sources&&!s.pools?<EmptyState icon="◎" title="Nothing to watch yet" description="Connect a source and create a pool to start observing access decisions and agent requests."/>:<>
 <div className="hero"><div className="ringcard"><div className="ringwrap"><Ring value={total(s.spectrum)-s.spectrum.undecided} denominator={total(s.spectrum)}/><div className="ringmid"><span className="big">{ratio(total(s.spectrum)-s.spectrum.undecided,total(s.spectrum))}</span><span className="lab">Decided</span></div></div><p className="note">{total(s.spectrum)} decisions across {s.pools} pools</p>{s.spectrum.undecided?<div className="ringnote"><b>{s.spectrum.undecided} waiting</b><span>Unreadable in the relevant pool until an entitlement is set.</span></div>:null}</div>
 <div className="spec"><h2>What this project's agents can see</h2><p className="h3s">{total(s.spectrum)} decisions across {s.pools} pools, including undecided.</p><SpectrumBar spectrum={s.spectrum}/><div className="speclegend">{treatments.map(([key,label,color])=><div key={key}><i aria-hidden="true" style={{background:color}}/>{label} <span className="mono">{s.spectrum[key]}</span></div>)}</div><p className="foot"><span className="mono">{ratio(s.spectrum.clear,total(s.spectrum))}</span> in the clear. The same field can have a different decision in each pool.</p></div></div>
 <p className="note">Today: <span className="mono">{s.utcDay}</span> UTC · as of <time dateTime={s.asOf}>{s.asOf.slice(11,19)} UTC</time></p><div className="tiles">{[['Requests today (UTC)',s.requests,`${s.queries} queries · ${s.prompts} prompts`],['Refused today (UTC)',s.refused,'Recorded refusals'],['Incomplete today (UTC)',s.incomplete,'Headers without a completion'],['Agents connected',s.connectedAgents,`${s.staleAgents} stale · disconnected twins retained in Pools`]].map(([label,value,note])=><div className="tile" key={label}><div className="k">{label}</div><div className="v mono">{value}</div><div className="n">{note}</div></div>)}</div>
 </>}
 </>:null}
 {feed.isPending?<LoadingState/>:feed.isError?<ErrorState title="Dashboard findings could not be loaded" description={feed.error.message} retry={()=>feed.refetch()}/>:null}
 {admin&&custody.isPending?<LoadingState/>:admin&&custody.isError?<ErrorState title="Key custody findings could not be loaded" description={custody.error.message} retry={()=>custody.refetch()}/>:null}
 {findings.length||failures.length?<section className="card" aria-label="Needs a decision"><div className="card-h"><h2>Needs a decision</h2></div><ul className="feed">{findings.map(f=><Finding key={f.id} finding={f} projectId={projectId}/>)}{failures.map(v=><li key={'custody-'+v.version}><span className="sev lo" aria-hidden="true">·</span><div className="fb"><p className="t">Key version {v.version}: {v.lastRehearsal==='mismatch'?'escrow does not match the recorded key':'escrow could not be verified'}</p><p className="d">Check the independent backup and run a restore rehearsal. Rotation cannot recover an earlier key.</p><Link style={{color:'var(--ink)'}} to="/projects/$projectId/$screen" params={{projectId,screen:'token-key'}}>Review token key custody</Link></div></li>)}</ul>{feed.hasNextPage?<AsyncButton variant="ghost" disabled={feed.isFetchingNextPage} pendingLabel="Loading…" refusal={feed.isError?feed.error.message:null} run={()=>feed.fetchNextPage()}>Load more findings</AsyncButton>:null}</section>:null}
 {pools.isPending?<LoadingState/>:pools.isError?<ErrorState title="Pool shields could not be loaded" description={pools.error.message} retry={()=>pools.refetch()}/>:pools.data?.pages.some(p=>p.items.length)?<><div className="card-h" style={{border:0}}><h2>Pools in this project</h2><span className="meta">In the clear</span></div><div className="shields">{pools.data.pages.flatMap(p=>p.items).map(p=><Shield key={p.id} pool={p} projectId={projectId}/>)}</div>{pools.hasNextPage?<AsyncButton variant="ghost" disabled={pools.isFetchingNextPage} pendingLabel="Loading…" refusal={null} run={()=>pools.fetchNextPage()}>Load more pools</AsyncButton>:null}</>:null}
 </section>;
}
