import {Link} from '@tanstack/react-router';
import {AsyncButton,EmptyState,ErrorState,LoadingState,FindingCard,FindingGrid,Mark,ExposureSpectrum} from '../../shared/ui/index.js';
import type {Spectrum} from '../../shared/api/dashboard.js';
import type {ActivityFilters} from '../../shared/api/activity.js';
import {observationCopy} from '../../shared/observation-copy.js';
import {Timestamp} from '../settings/preferences.js';
import {requestLabel} from '../activity/presentation.js';
import {AnswerTreatments} from '../activity/detail.js';
import {useDashboardModel} from './data.js';
import type {DashboardModel} from './read-model.js';
const total=(s:Spectrum)=>Object.values(s).reduce((a,b)=>a+b,0);
function Setup({projectId}:{projectId:string}){return <div className="setup">{[['Connect a source','Opintel introspects it and builds a catalogue. Nothing is readable until you say so.','data-sources'],['Create a pool','Generate a key for your agents. Bind the pool to the sources it may reach.','pools'],['Decide what it sees','Set entitlements for the pool. Anything undecided stays out of reach.','entitlements']].map(([title,description,screen],i)=><div className={i===0?'stepcard now':'stepcard'} key={screen}><div className="num">{i+1}</div><b>{title}</b><p>{description}</p><Link className={i===0?'btn go':'btn ghost'} to="/projects/$projectId/$screen" params={{projectId,screen:screen!}}>{i===2?'Open entitlements':title}</Link></div>)}</div>;}
function Band({children}:{children:string}){return <h2 data-part="band-heading">{children}</h2>;}
function Count({value,label,kind}:{value:number;label:string;kind:'quarantined'|'needs-a-decision'}){return <div data-mark-row="true" data-row-kind="finding"><div className="interp"><span className="sev" title={kind==='quarantined'?'Quarantined':'Needs a decision'}><Mark name={kind} size={18}/></span><span data-part="finding-count" className="mono">{value}</span></div><p data-part="finding-label">{label}</p></div>;}
function Coverage({decided,pending}:{decided:number;pending:number}){const all=decided+pending,split=all?decided/all*100:0;return <svg role="img" aria-label={`${decided} decided, ${pending} undecided`} width="100%" height="8" viewBox="0 0 100 8" preserveAspectRatio="none"><rect width={split} height="8" fill="var(--surface-3)"/><rect x={split} width={100-split} height="8" fill="var(--yellow)"/></svg>;}
function Needs({m,projectId}:{m:DashboardModel;projectId:string}){
 const pending=m.pools.filter(p=>p.pending>0),filings=m.observations.filter(g=>g.kind==='filing'),other=m.observations.filter(g=>g.kind!=='filing'),filingCount=filings.reduce((n,g)=>n+g.count,0),oldest=filings.map(g=>g.oldestAt).sort()[0];
 if(!pending.length&&!filings.length&&!other.length&&!m.suggestions.length&&!m.failures.length)return null;
 return <section aria-label="Needs you"><Band>Needs you</Band><FindingGrid>
 {pending.map(p=><FindingCard key={p.pool.id} title={p.pool.name} needsDecision footer={<><span className="meta">{p.groups} name {p.groups===1?'group':'groups'}</span><Link className="btn go" to="/projects/$projectId/$screen" params={{projectId,screen:'entitlements'}} search={{poolId:p.pool.id,decision:'undecided',layout:'name'}}>Decide</Link></>}><Count value={p.pending} label="decisions need an entitlement" kind="needs-a-decision"/><Coverage decided={total(p.spectrum)-p.pending} pending={p.pending}/>{p.demand[0]?<p className="note" title="This records a refused join, not all requests for an element.">Join attempted · {p.demand[0].name}: {p.demand[0].queries} query · {p.demand[0].explains} explain</p>:null}</FindingCard>)}
 {filings.length?<FindingCard title="Filings" needsDecision footer={<><span className="meta">Oldest {oldest?<Timestamp value={oldest}/>:null}</span><Link className="btn go" to="/projects/$projectId/$screen" params={{projectId,screen:'observations'}} search={{observationKind:'filing',observationView:'open'}}>Prepare for the operator</Link></>}><Count value={filingCount} label="filings did not land" kind="quarantined"/><div className="interp">{filings.map(g=><span className="ichip" key={g.id} title={observationCopy(g).title}><span className="mono">{g.count}</span>{observationCopy(g).title}</span>)}</div></FindingCard>:null}
 {m.suggestions.length?<FindingCard title="Suggested relationships" needsDecision footer={<><span className="meta">Join attempted</span><Link className="btn go" to="/projects/$projectId/$screen" params={{projectId,screen:'relationship-suggestions'}}>Review</Link></>}><Count value={m.suggestions.length} label="joins need your judgement" kind="needs-a-decision"/><div className="interp"><span className="ichip mono" title={m.suggestions[0]!.left.name}>{m.suggestions[0]!.left.address.column??'Unnameable element'}</span><span aria-hidden="true">↔</span><span className="ichip mono" title={m.suggestions[0]!.right.name}>{m.suggestions[0]!.right.address.column??'Unnameable element'}</span></div><span className="note">{m.suggestions[0]!.queries} query · {m.suggestions[0]!.explains} explain attempts</span></FindingCard>:null}
 {other.map(g=><FindingCard key={g.id} title={g.kind==='custody'?'Key custody':'Type mapping'} needsDecision footer={<><span className="meta">{g.causeDetail||observationCopy(g).owner}</span><Link className="btn go" to="/projects/$projectId/$screen" params={{projectId,screen:'observations'}} search={{observationGroup:g.id,observationView:'open'}}>Review</Link></>}><Count value={g.count} label={g.kind==='custody'?'backup checks need review':'types cannot be exposed'} kind="needs-a-decision"/><span className="ichip">{observationCopy(g).title}</span></FindingCard>)}
 {m.failures.map(f=>f.kind==='source_failure'?<FindingCard key={f.id} title={f.sourceName} needsDecision footer={f.runId?<Link className="btn go" to="/projects/$projectId/introspections/$runId" params={{projectId,runId:f.runId}}>Review failed run</Link>:<Link className="btn go" to="/projects/$projectId/$screen" params={{projectId,screen:'data-sources'}}>Review source</Link>}><Count value={1} label="source check did not finish" kind="needs-a-decision"/><span className="ichip">Introspection failed</span></FindingCard>:null)}
 </FindingGrid></section>;
}
function Spark({days,metric}:{days:DashboardModel['days'];metric:'requests'|'refused'|'incomplete'}){
 const peak=Math.max(1,...days.map(d=>d[metric]));
 return <div className="spark" role="img" aria-label={`Last 7 days (UTC); ${days.map(d=>`${d.day}: ${d[metric]} ${metric}`).join('; ')}`}><svg width="100%" height="22" viewBox="0 0 140 22" preserveAspectRatio="none" aria-hidden="true" focusable="false">
  <path data-part="baseline" d="M0 21.5H140" stroke="var(--rule-2)"/>
  {days.map((d,i)=>{const height=21*d[metric]/peak;return <g key={d.day}><path data-part="day-position" data-day={d.day} d={`M${i*20+6} 21.5h8`} stroke="var(--ink-3)"/><rect data-day={d.day} data-count={d[metric]} x={i*20+8} y={21-height} width={4} height={height} rx={1} fill={i===6?'var(--plum)':'var(--ink-3)'}><title>{d.day}: {d[metric]}</title></rect></g>;})}
 </svg></div>;
}
function ActivityLink({projectId,filter,label='Open Activity',inline=false}:{projectId:string;filter:ActivityFilters;label?:string;inline?:boolean}){return <Link className={inline?undefined:'btn ghost'} to="/projects/$projectId/activity" params={{projectId}} search={filter}>{label}</Link>;}
function State({m,projectId}:{m:DashboardModel;projectId:string}){
 const today=m.days.at(-1)!,count=total(m.spectrum),seen=m.pools.reduce((n,p)=>n+p.agents.length,0),connected=m.pools.reduce((n,p)=>n+p.agents.filter(a=>['connecting','active','idle'].includes(a.state)).length,0);
 return <section aria-label="Where the project stands"><Band>Where the project stands</Band><div className="hero">
 <section className="spec" aria-label="Exposure"><h3>Exposure</h3><p className="h3s">{count} decisions across {m.pools.length} {m.pools.length===1?'pool':'pools'}</p><ExposureSpectrum decisions={Object.entries(m.spectrum).map(([value,count])=>({value,count}))} label="Exposure distribution" clearLabel="In the clear" monoCounts/><p className="foot">{count?`${Math.round(m.spectrum.clear/count*1000)/10}%`:'n/a'} in the clear. Decisions can differ by pool.</p><div data-part="pool-links"><span>{m.pools.map((p,i)=><span key={p.pool.id}>{i?' · ':null}<Link to="/projects/$projectId/$screen" params={{projectId,screen:'entitlements'}} search={{poolId:p.pool.id,decision:'all',layout:'name'}}>{p.pool.name}: {total(p.spectrum)} decisions</Link></span>)}</span></div></section>
 <div className="tiles" data-layout="metrics">{(['requests','refused','incomplete'] as const).map(metric=><article className="tile" key={metric} data-metric={metric}><div className="k">{metric==='requests'?'Requests today':metric==='refused'?'Refused today':'Incomplete today'}</div><div className="v mono">{today[metric]}</div><div className="n" data-part="metric-support">{metric==='requests'?<><ActivityLink inline projectId={projectId} filter={{...m.today,mode:'query'}} label={`${today.queries} queries`}/> · <ActivityLink inline projectId={projectId} filter={{...m.today,mode:'prompt'}} label={`${today.prompts} prompts`}/></>:metric==='incomplete'?'No answer was recorded':'Recorded refusals'}</div><div className="n" data-part="metric-links"><span><ActivityLink inline projectId={projectId} filter={{...m.today,...(metric==='requests'?{}:{outcome:metric})}}/></span></div><div className="n" data-part="chart-label">Last 7 days (UTC)</div><Spark days={m.days} metric={metric}/></article>)}
 <article className="tile" data-metric="agents"><div className="k">Agent connections</div><div className="v mono">{connected}</div><div className="n">{seen} seen · current presence</div><p className="note">Presence history is not recorded.</p><div data-part="pool-links"><span>{m.pools.map((p,i)=><span key={p.pool.id}>{i?' · ':null}<Link to="/projects/$projectId/pools/$poolId" params={{projectId,poolId:p.pool.id}}>{p.pool.name}: {p.agents.length} seen</Link></span>)}</span></div></article></div>
 </div></section>;
}
function Recent({m,projectId}:{m:DashboardModel;projectId:string}){return <section aria-label="Recently"><Band>Recently</Band>{m.recent.length?<div className="card"><ul className="feed" data-mark-list="uniform">{m.recent.map(r=><li key={r.id+'@'+r.startedAt} data-mark-row="true" data-row-kind="request">{r.status==='refused'||r.status==='incomplete'?<span className="sev"><Mark name={r.status==='refused'?'refused':'incomplete'} size={18}/></span>:null}<div className="fb"><p className="t">{r.status==='answered'||r.status==='reduced'?`${r.rowCount??'—'} rows · `:r.status==='refused'?'Refused · ':''}{requestLabel(r)}</p><p className="d">{r.agentId??'No agent ID'} · {r.metadata.objects?.map(o=>o.name).join(' · ')||'Object detail not recorded'}</p><AnswerTreatments counts={r.metadata.delivered}/><Timestamp value={r.startedAt} appearance="when"/></div><Link className="btn ghost" to="/projects/$projectId/runs/$runId" params={{projectId,runId:r.id}} search={{startedAt:r.startedAt}}>Record</Link></li>)}</ul></div>:<p className="note">No requests recorded yet.</p>}</section>;}
export function DashboardScreen({projectId,name,admin}:{projectId:string;name:string;admin:boolean}){
 const query=useDashboardModel(projectId,admin),m=query.data;
 return <section className="screen on" data-layout="dashboard"><h1>{name}</h1><p className="sub">What this project's agents can see, and what is waiting on you.{m?<> As of <Timestamp value={m.asOf}/></>:null}</p><div className="filters"><AsyncButton variant="ghost" pendingLabel="Refreshing…" refusal={null} run={()=>query.refetch()}>Refresh dashboard</AsyncButton></div>
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Dashboard could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:m?<>
 {!m.sources||!m.pools.length?<Setup projectId={projectId}/>:null}<Needs m={m} projectId={projectId}/><State m={m} projectId={projectId}/><Recent m={m} projectId={projectId}/>{!m.sources&&!m.pools.length?<EmptyState title="Nothing to watch yet" description="Connect a source and create a pool to start observing access decisions and agent requests."/>:null}
 </>:null}</section>;
}
