import {z} from 'zod';
import {createApiClient} from './client.js';
const count=z.number().int().nonnegative();
export const ActivityStatus=z.enum(['incomplete','answered','reduced','refused','clarify','failed']);
// Answer treated means a completed answer with a recorded tokenized, masked or
// aggregate-only delivery. Planned reads, omissions, refusals and incomplete
// requests are excluded; this is not a customer-sensitivity classification.
export const ActivityFilters=z.object({poolId:z.uuid().optional(),agentId:z.string().max(200).optional(),mode:z.enum(['query','prompt']).optional(),outcome:ActivityStatus.optional(),answerTreated:z.enum(['true']).optional(),search:z.string().trim().max(200).optional(),from:z.iso.datetime({offset:true}).optional(),to:z.iso.datetime({offset:true}).optional()});
export const ActivityQuery=ActivityFilters.extend({cursor:z.string().max(4096).optional(),limit:z.coerce.number().int().min(1).max(100).default(50)}).refine(v=>!v.from||!v.to||Date.parse(v.from)<Date.parse(v.to),'The end must be after the start.');
export const EvidenceLifecycle=z.object({
 recordKind:z.enum(['full','rollup']).default('full'),rolledUpAt:z.iso.datetime({offset:true}).nullable().default(null),
 treatmentCounts:z.record(z.string(),count).default({}),sourceTreatmentCounts:z.record(z.string(),count).default({}),
 capturePercent:z.number().gt(0).max(100).default(100),captureSelected:z.boolean().default(true),detailCaptured:z.boolean().nullable().default(true),
 redactions:z.array(z.object({at:z.iso.datetime({offset:true}),policy:z.object({redaction:z.enum(['aggressive','allowlist','none']),allowlistedFields:z.array(z.string())}),fields:z.array(z.string())})).default([]),
});
const address=z.object({catalog:z.string(),schema:z.string(),name:z.string()});
export const ActivityMetadata=z.object({objects:z.array(address).nullable().default(null),delivered:z.record(z.string(),count).default({}),omissions:z.record(z.string(),count).default({}),refusal:z.object({message:z.string(),stage:z.string().nullable(),candidate:z.object({id:z.uuid(),columns:z.tuple([z.object({elementId:z.uuid(),name:z.string()}),z.object({elementId:z.uuid(),name:z.string()})])}).nullable()}).nullable().default(null)});
export const ActivityCounts=z.object({all:count,refused:count,incomplete:count,answerTreated:count});
export const ActivitySummary=z.object({counts:ActivityCounts,days:z.array(z.object({day:z.iso.date(),counts:ActivityCounts,outcomes:z.record(ActivityStatus,count)}))});
export const ActivitySummaryQuery=ActivityFilters.refine(v=>!v.from||!v.to||Date.parse(v.from)<Date.parse(v.to),'The end must be after the start.');
export const ActivityEntry=z.object({...EvidenceLifecycle.shape,id:z.uuid(),projectId:z.uuid(),poolId:z.uuid(),agentId:z.string().nullable(),keyPrefix:z.string(),mode:z.enum(['query','prompt']),startedAt:z.iso.datetime({offset:true}),status:ActivityStatus,rowCount:count.nullable(),latencyMs:count.nullable(),synthetic:z.boolean().nullable(),request:z.string().nullable(),argumentVisibility:z.enum(['hidden','literal_stripped','raw']),metadata:ActivityMetadata.default({objects:null,delivered:{},omissions:{},refusal:null}),versions:z.object({policy:count,vocabulary:count,catalog:count,tokenKeyVersionSelected:count.positive().nullable()})});
export const ActivityPage=z.object({items:z.array(ActivityEntry),nextCursor:z.string().nullable()});
export const EvidenceTokenDeclarations=z.array(z.object({elementId:z.uuid(),qualifiedName:z.string(),domain:z.string(),domainVersion:z.number().int().positive().nullable().default(null),canonId:z.string(),mode:z.enum(['text','number','date','timestamp']),caseInsensitive:z.boolean(),sourceTimezone:z.string().optional(),epochUnit:z.enum(['seconds','milliseconds']).optional()}));
export const EvidenceDetail=ActivityEntry.extend({tokenDeclarations:EvidenceTokenDeclarations.nullable().default(null),completedAt:z.iso.datetime({offset:true}).nullable(),tokenKeyVersionUsed:count.positive().nullable(),truncated:z.boolean().nullable(),refusalCode:z.string().nullable(),generatedSql:z.string().nullable(),objects:z.array(z.object({catalog:z.string(),schema:z.string(),name:z.string(),columns:z.array(z.object({elementId:z.uuid().nullable(),exposedName:z.string().nullable()}))})).default([]),elements:z.array(z.object({elementId:z.uuid().nullable(),exposedName:z.string(),state:z.enum(['released','aggregated','withheld','undecided']),treatment:z.enum(['clear','tokenized','masked','aggregate_only']).nullable(),withheldReason:z.string().nullable()})),stages:z.array(z.object({stage:z.string(),result:z.string(),ms:count,code:z.string().nullable()})),sources:z.array(z.object({id:z.uuid(),origin:z.string(),freshnessMode:z.string(),landingStrategy:z.string().nullable(),lastIntrospectedAt:z.string().nullable()}))});
export type ActivityFilters=z.infer<typeof ActivityFilters>;
export type ActivityEntry=z.infer<typeof ActivityEntry>;
export type EvidenceDetail=z.infer<typeof EvidenceDetail>;
export type ActivitySummary=z.infer<typeof ActivitySummary>;
export const DetailQuery=z.object({projectId:z.uuid(),startedAt:z.iso.datetime({offset:true})});
export function activityList(project:string,filters:ActivityFilters,cursor:string|null,client=createApiClient()){
 const query=new URLSearchParams({...filters,...(cursor?{cursor}:{})});return client.request({path:`/api/v1/projects/${project}/runs?${query}`,response:ActivityPage});
}
export function activityDetail(project:string,run:string,startedAt:string,client=createApiClient()){return client.request({path:`/api/v1/runs/${run}?${new URLSearchParams({projectId:project,startedAt})}`,response:EvidenceDetail});}
export function activitySummary(project:string,filters:ActivityFilters,client=createApiClient()){return client.request({path:`/api/v1/projects/${project}/runs/summary?${new URLSearchParams({...filters})}`,response:ActivitySummary});}
export function activityOpenApiDocument(){return {openapi:'3.1.0',info:{title:'Activity',version:'1'},paths:{'/projects/{id}/runs/summary':{get:{'x-permission':'project#view',parameters:[{name:'id',in:'path',required:true,schema:{type:'string',format:'uuid'}},...Object.entries(ActivityFilters.shape).map(([name,schema])=>({name,in:'query',schema:z.toJSONSchema(schema)}))],responses:{200:{description:'Complete matching scope in UTC calendar days',content:{'application/json':{schema:z.toJSONSchema(ActivitySummary)}}}}}},'/projects/{id}/runs':{get:{'x-permission':'project#view',parameters:[{name:'id',in:'path',required:true,schema:{type:'string',format:'uuid'}},...Object.entries(ActivityQuery.shape).map(([name,schema])=>({name,in:'query',schema:z.toJSONSchema(schema)}))],responses:{200:{description:'Cursor page of historical runs',content:{'application/json':{schema:z.toJSONSchema(ActivityPage)}}}}}},'/runs/{id}':{get:{'x-permission':'project#view',parameters:[{name:'id',in:'path',required:true,schema:{type:'string',format:'uuid'}},...Object.entries(DetailQuery.shape).map(([name,schema])=>({name,in:'query',required:true,schema:z.toJSONSchema(schema)}))],responses:{200:{description:'Stored historical evidence; header-only runs are incomplete',content:{'application/json':{schema:z.toJSONSchema(EvidenceDetail)}}}}}}}};}
