import {Mark} from '../../shared/ui/index.js';
import { AsyncButton } from '../../shared/ui/index.js';
import {Timestamp as DisplayTimestamp} from '../settings/preferences.js';
import {useEffect,useMemo,useRef,type ReactNode} from 'react';
import {useStore} from 'zustand';
import {Link,useBlocker} from '@tanstack/react-router';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import {Button,LoadingState,ErrorState,EmptyState} from '../../shared/ui/index.js';
import {CreatePoolBody,type PoolKeyMetadata} from '../../shared/api/pool-keys.js';
import {useProjects} from '../tenancy/data.js';
import {usePoolList,usePool,useAgents,useTwin,useImpact,usePoolCommand} from './data.js';
import {createPoolUi} from './state.js';
const stamp=(value:string|null)=>value===null?'Never':<DisplayTimestamp value={value}/>;
const ratio=(clear:number,total:number)=>total===0?'n/a':`${Math.round(clear/total*100)}%`;
function Status({state}:{state:string}){return <span className="mono">{state==='stale'?<Mark name="stale"/>:null}{state}</span>;}
function Modal({title,children}:{title:string;children:ReactNode}){
 const ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const previous=document.activeElement;const el=ref.current;el?.focus();const main=document.querySelector('main.body');const siblings=[...(main?.parentElement?.children??[])].filter(e=>e!==main);const drawer=document.querySelector('.drawer');for(const e of [...siblings,...(drawer?[drawer]:[])])e.setAttribute('inert','');return()=>{for(const e of [...siblings,...(drawer?[drawer]:[])])e.removeAttribute('inert');if(previous instanceof HTMLElement)previous.focus();};},[]);
 return <div className="modal on"><div className="sheet" role="dialog" aria-modal="true" aria-label={title} tabIndex={-1} ref={ref} onKeyDown={e=>{if(e.key==='Escape')e.preventDefault();if(e.key==='Tab'){const all=[...e.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),a[href],textarea')];const first=all[0],last=all.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===ref.current)){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===ref.current)){e.preventDefault();first?.focus();}}}}><div className="sheeth"><b>{title}</b></div><div className="sheetb">{children}</div></div></div>;
}
function useUi(){const store=useMemo(createPoolUi,[]);const ui=useStore(store);useBlocker({shouldBlockFn:()=>Boolean(ui.issued?.keyShown||ui.action),enableBeforeUnload:Boolean(ui.issued?.keyShown||ui.action)});return ui;}
function Issued({ui}:{ui:ReturnType<typeof useUi>}){const r=ui.issued;if(!r)return null;return <Modal title={r.keyShown?'Copy your pool key':'Key already shown'}>{r.keyShown?<><p>This key is shown once. Copy it now, then dismiss this dialog deliberately. It cannot be retrieved later.</p><div className="fld mono"><label htmlFor="new-pool-key">New pool key</label><input id="new-pool-key" aria-label="New pool key" className="mono" readOnly value={r.key} style={{width:'100%',overflowWrap:'anywhere'}} onCopy={e=>{const input=e.currentTarget;if(input.selectionStart===0&&input.selectionEnd===r.key.length)ui.copy(true);}}/></div><div className="filters"><AsyncButton pendingLabel="Copying…" run={async()=>{try{await navigator.clipboard.writeText(r.key);ui.copy(true);}catch{ui.copy(false);}}}>Copy key</AsyncButton><Button variant="ghost" disabled={!ui.copied} onClick={ui.dismiss}>I copied the key — dismiss</Button></div>{ui.copied?<p role="status">Copied. Store the key securely before dismissing.</p>:null}{ui.copyError?<p role="alert">{ui.copyError}</p>:null}</>:<><p>This request already issued a key. A replay cannot show it again. If the original response was lost, rotate the key deliberately from the pool detail.</p><Button onClick={ui.dismiss}>Dismiss</Button></>}</Modal>;}
function CreateDialog({ui,command}:{ui:ReturnType<typeof useUi>;command:ReturnType<typeof usePoolCommand>}){const form=useForm({resolver:zodResolver(CreatePoolBody),defaultValues:{name:''}});return <Modal title="Create a pool"><form onSubmit={form.handleSubmit(v=>command.mutate({kind:'create',name:v.name,requestKey:ui.requestKey}))}><div className="fld"><label htmlFor="pool-name">Pool name</label><input id="pool-name" {...form.register('name')} disabled={command.isPending}/>{form.formState.errors.name?<p role="alert">{form.formState.errors.name.message}</p>:null}</div><p>The new key will be shown once. No source is bound until you configure access.</p>{command.isError?<p role="alert">{command.error.message}</p>:null}<div className="filters"><Button type="submit" disabled={command.isPending}>{command.isPending?'Creating…':'Create pool'}</Button><Button variant="ghost" disabled={command.isPending} onClick={ui.close}>Cancel</Button></div></form></Modal>;}
export function PoolsScreen({projectId}:{projectId:string}){
 const query=usePoolList(projectId),projects=useProjects(),ui=useUi(),command=usePoolCommand(projectId,'',ui.receive);const admin=projects.data?.find(p=>p.id===projectId)?.role==='admin';const rows=query.data?.pages.flatMap(p=>p.items)??[];
 const create=<Button variant="go" disabled={!admin} onClick={()=>{command.reset();ui.open('create');}}>Create a pool</Button>;
 return <section className="screen on"><h1>Pools</h1><p className="sub">A pool is a set of agents sharing a key. Each reaches only the sources bound to it, under the entitlements you set.</p>
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Pools could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:!rows.length?<EmptyState title="No pools yet" description="Create a pool, copy its key into your agents, and choose which sources it may reach.">{create}</EmptyState>:<div className="card"><div className="card-h"><h2>Pools in this project</h2>{create}</div><div role="region" aria-label="Pools" tabIndex={0} style={{overflowX:'auto'}}><table><thead><tr><th>Pool</th><th>Agents</th><th>Can ask by</th><th>Sources</th><th>In the clear</th><th>Key status</th></tr></thead><tbody>{rows.map(p=><tr key={p.id}><td><Link style={{color:'var(--ink)'}} to="/projects/$projectId/pools/$poolId" params={{projectId,poolId:p.id}}>{p.name}</Link></td><td className="num">{p.agents} seen · {p.activeAgents} active</td><td><div className="modechips"><span className={p.modeQuery?'mc on':'mc'}>Query {p.modeQuery?'on':'off'}</span><span className={p.modePrompt?'mc on p':'mc'}>Prompt {p.modePrompt?'on':'off'}</span></div></td><td className="num">{p.sourceIds.length}</td><td className="num">{ratio(p.clearElements,p.activeElements)}</td><td>{p.workingKeys?`${p.workingKeys} working`:'No working key'}</td></tr>)}</tbody></table></div>{query.hasNextPage?<AsyncButton variant="ghost" disabled={query.isFetchingNextPage} pendingLabel="Loading…" refusal={null} run={()=>query.fetchNextPage()}>Load more pools</AsyncButton>:null}</div>}
 <p className="note">In the clear includes every active element in the denominator, including undecided elements. Agent counts include disconnected twins.</p>
 {ui.action==='create'?<CreateDialog ui={ui} command={command}/>:null}<Issued ui={ui}/></section>;
}
function Agents({projectId,poolId}:{projectId:string;poolId:string}){const query=useAgents(projectId,poolId),rows=query.data?.pages.flatMap(p=>p.items)??[];return <div className="seg"><h2>Agents</h2>{query.isPending?<LoadingState/>:query.isError?<ErrorState title="Agents could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:!rows.length?<EmptyState title="No agents seen yet" description="Configure an agent with this pool’s key and supply X-Opintel-Agent-Id when connecting."/>:<div className="card"><div role="region" aria-label="Pool agents" tabIndex={0} style={{overflowX:'auto'}}><table><thead><tr><th>Agent</th><th>State</th><th>Client</th><th>First seen</th><th>Reconnects</th><th>Last seen</th></tr></thead><tbody>{rows.map(a=><tr key={a.agentId}><td><Link style={{color:'var(--ink)'}} to="/projects/$projectId/pools/$poolId/agents/$agentId" params={{projectId,poolId,agentId:a.agentId}}>{a.agentId}</Link></td><td><Status state={a.state}/></td><td>{a.client??'Not reported'}</td><td className="num">{stamp(a.firstSeen)}</td><td className="num">{a.reconnects}</td><td className="num">{stamp(a.lastSeen)}</td></tr>)}</tbody></table></div>{query.hasNextPage?<AsyncButton variant="ghost" disabled={query.isFetchingNextPage} pendingLabel="Loading…" refusal={null} run={()=>query.fetchNextPage()}>Load more agents</AsyncButton>:null}</div>}<p className="note">Identities are self-declared and unverified. The pool key authorizes access. Disconnected agents remain visible with when they were last seen.</p></div>;}
function Impact({data}:{data:NonNullable<ReturnType<typeof useImpact>['data']>}){return <><h3>{data.affectedAgentCount} affected agents</h3>{data.affectedAgents.length?<ul>{data.affectedAgents.map(a=><li className="mono" key={a}>{a}</li>)}</ul>:<p>No connected agents last authenticated with this key.</p>}<h3>Seen previously · disconnected</h3>{data.previouslySeenAgents.length?<ul>{data.previouslySeenAgents.map(a=><li className="mono" key={a}>{a}</li>)}</ul>:<p>None on this key.</p>}</>;}
const Confirmation=z.object({confirmation:z.string()});
function KeyAction({projectId,poolId,name,graceSeconds,ui,command}:{projectId:string;poolId:string;name:string;graceSeconds:number;ui:ReturnType<typeof useUi>;command:ReturnType<typeof usePoolCommand>}){
 const impact=useImpact(projectId,poolId,ui.version),form=useForm({resolver:zodResolver(Confirmation),defaultValues:{confirmation:''}});const revoking=ui.action==='revoke';
 return <Modal title={revoking?'Revoke pool key':'Rotate pool key'}><p className="note" style={{overflowWrap:'anywhere'}}>Key version {ui.version||'No current key'}</p>
 <p>{revoking?'This key stops working immediately. Agents still using it will be refused on their next request. Other key versions keep their existing validity.':`A new key will be shown once. The current key stays valid for ${graceSeconds/3600} hours, then stops working. Update agents during that grace window.`}</p>
 {ui.version&&impact.isPending?<LoadingState/>:ui.version&&impact.isError?<ErrorState title="Key impact could not be loaded" description={impact.error.message} retry={()=>impact.refetch()}/>:impact.data?<Impact data={impact.data}/>:<p>0 affected agents: this pool has no current key to retire.</p>}
 <form onSubmit={form.handleSubmit(v=>command.mutate(revoking?{kind:'revoke',keyVersion:ui.version,confirmation:v.confirmation,requestKey:ui.requestKey}:{kind:'rotate',requestKey:ui.requestKey}))}>
 {revoking?<div className="fld"><label htmlFor="pool-confirm">Type {name} to confirm</label><input id="pool-confirm" autoComplete="off" {...form.register('confirmation')} disabled={command.isPending}/></div>:null}
 {command.isError?<p role="alert">{command.error.message}</p>:null}<div className="filters"><Button type="submit" disabled={command.isPending||(Boolean(ui.version)&&!impact.data)||(revoking&&form.watch('confirmation')!==name)}>{command.isPending?'Working…':revoking?'Confirm revocation':'Confirm rotation'}</Button><Button variant="ghost" disabled={command.isPending} onClick={ui.close}>Cancel</Button></div></form></Modal>;
}
function ExpiredImpact({projectId,poolId,version,prefix}:{projectId:string;poolId:string;version:string;prefix:string}){
 const query=useImpact(projectId,poolId,version),data=query.data;
 return <div className="sheetb" data-part="expired-key-impact"><b title={version}>Expired key · {prefix}…</b>
 {query.isPending?<LoadingState/>:query.isError?<ErrorState title="Expiry impact unavailable" description={query.error.message} retry={()=>query.refetch()}/>:data?<>
 <p>{data.affectedAgentCount?`${data.affectedAgentCount} connected ${data.affectedAgentCount===1?'agent':'agents'} last authenticated with this key.`:'No connected agents last authenticated with this key.'}</p>
 {data.affectedAgents.length?<ul>{data.affectedAgents.map(a=><li className="mono" key={a}>{a}</li>)}</ul>:null}
 {data.previouslySeenAgents.length?<><p>{data.previouslySeenAgents.length} previously seen · disconnected</p><ul>{data.previouslySeenAgents.map(a=><li className="mono" key={a}>{a}</li>)}</ul></>:null}
 </>:null}</div>;
}
export function PoolDetailScreen({projectId,poolId}:{projectId:string;poolId:string}){
 const query=usePool(projectId,poolId),projects=useProjects(),ui=useUi(),command=usePoolCommand(projectId,poolId,ui.receive),p=query.data;const admin=projects.data?.find(p=>p.id===projectId)?.role==='admin';
 useEffect(()=>{if(command.isSuccess&&command.variables.kind==='revoke')ui.close();},[command.isSuccess,command.variables,ui.close]);
 return <section className="screen on"><h1>{p?.name??'Pool detail'}</h1><p className="sub">Key management and the agents observed using this pool.</p>{query.isPending?<LoadingState/>:query.isError&&'code' in query.error&&query.error.code==='not_found'?<EmptyState title="Pool not found" description="Choose an existing pool from Pools."/>:query.isError?<ErrorState title="Pool could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:!p?<EmptyState title="Pool unavailable" description="Choose a pool from Pools."/>:<><div className="card"><div className="card-h"><h2>Pool keys</h2>{admin?<Button disabled={command.isPending} onClick={()=>{command.reset();ui.open('rotate',p.keys.find(k=>k.state==='current')?.keyVersion);}}>Rotate key</Button>:null}</div><div className="sheetb"><p>{p.workingKeys?`${p.workingKeys} working key versions`:'No working key. Agents cannot authenticate.'}</p><p className="note">{p.sourceIds.length} bound sources · {ratio(p.clearElements,p.activeElements)} in the clear · Query {p.modeQuery?'on':'off'} · Prompt {p.modePrompt?'on':'off'}</p><Link style={{color:'var(--ink)'}} to="/projects/$projectId/$screen" params={{projectId,screen:'entitlements'}} search={{poolId}}>Review this pool’s entitlements</Link></div><div role="region" aria-label="Pool key versions" tabIndex={0} style={{overflowX:'auto'}}><table><thead><tr><th>Prefix</th><th>State</th><th>Created</th><th>Grace ends</th><th>Action</th></tr></thead><tbody>{p.keys.map(k=><tr key={k.keyVersion}><td className="num" title={k.keyVersion}>{k.prefix}…</td><td>{k.state}</td><td className="num">{stamp(k.createdAt)}</td><td className="num">{stamp(k.graceUntil)}</td><td>{admin&&(k.state==='current'||k.state==='retiring')?<Button variant="ghost" onClick={()=>{command.reset();ui.open('revoke',k.keyVersion);}}>Revoke {k.state} key</Button>:'—'}</td></tr>)}</tbody></table></div>{!p.keys.length?<p className="sheetb">No key versions. Rotate to issue a key.</p>:null}{admin?p.keys.filter(k=>k.state==='expired').map(k=><ExpiredImpact key={k.keyVersion} projectId={projectId} poolId={poolId} version={k.keyVersion} prefix={k.prefix}/>):null}</div>
 {command.isSuccess&&command.variables.kind==='revoke'?<p role="status">The selected key was revoked.</p>:null}
 <Agents projectId={projectId} poolId={poolId}/>
 {ui.action==='rotate'||ui.action==='revoke'?<KeyAction projectId={projectId} poolId={poolId} name={p.name} graceSeconds={p.graceSeconds} ui={ui} command={command}/>:null}</>}<Issued ui={ui}/></section>;
}
function KeyFacts({record}:{record:PoolKeyMetadata}){return <><p className="mono" style={{overflowWrap:'anywhere'}}>Last authenticated key: {record.keyVersion}</p><p>{record.prefix}… · {record.state}{record.graceUntil?` · Grace ends ${stamp(record.graceUntil)}`:''}</p>{record.state==='revoked'||record.state==='expired'?<p>This key no longer authorizes requests. The observed presence state remains a separate fact.</p>:null}</>;}
export function AgentTwinScreen({projectId,poolId,agentId}:{projectId:string;poolId:string;agentId:string}){const query=useTwin(projectId,poolId,agentId),r=query.data;return <section className="screen on"><h1>Agent twin</h1><p className="sub" style={{overflowWrap:'anywhere'}}>{agentId} · self-declared, unverified</p>{query.isPending?<LoadingState/>:query.isError&&'code' in query.error&&query.error.code==='not_found'?<EmptyState title="Agent not seen" description="Choose an observed agent from the pool detail. Disconnected agents remain here."/>:query.isError?<ErrorState title="Agent could not be loaded" description={query.error.message} retry={()=>query.refetch()}/>:!r?<EmptyState title="Agent not seen" description="Choose an observed agent from the pool detail."/>:<div className="card"><div className="card-h"><h2>Observed presence</h2><Status state={r.presence.state}/></div><div className="sheetb">{r.presence.state==='disconnected'?<p>Disconnected. This twin is retained; last seen <span className="mono">{stamp(r.presence.lastSeen)}</span>.</p>:null}<dl>{[['Client',r.presence.client??'Not reported'],['First seen',stamp(r.presence.firstSeen)],['Last seen',stamp(r.presence.lastSeen)],['Last request',stamp(r.presence.lastRequestAt)],['Last heartbeat',stamp(r.presence.lastHeartbeatAt)],['Reconnects',r.presence.reconnects]].map(([label,value])=><div className="frow" key={String(label)}><dt>{label}</dt><dd className="mono" style={{overflowWrap:'anywhere'}}>{value}</dd></div>)}</dl><KeyFacts record={r.keyMetadata}/><p className="note">The claimed agent ID is for observation only. Nothing is authorized on it; the pool key is the membership.</p><Link style={{color:'var(--ink)'}} to="/projects/$projectId/activity" params={{projectId}} search={{poolId,agentId}}>View this agent’s Activity</Link></div></div>}</section>;}
