import {createContext,useContext,type ReactNode} from 'react';
import {usePersonalSettings} from './data.js';
import {formatRelativeTime,useTimestampClock} from './timestamp-clock.js';
const Preferences=createContext({timezone:'UTC',dateFormat:'YYYY-MM-DD'});
export function DisplayPreferences({children}:{children:ReactNode}){const query=usePersonalSettings();const value=query.data??{timezone:'UTC',dateFormat:'YYYY-MM-DD',reducedMotion:false};return <Preferences.Provider value={value}>{value.reducedMotion?<style>{'#opintel-app *, #opintel-app *::before, #opintel-app *::after { animation: none !important; transition: none !important; scroll-behavior: auto !important; }'}</style>:null}{children}</Preferences.Provider>;}
const timestampFormatters=new Map<string,Intl.DateTimeFormat>();
function timestampFormatter(locale:string,timezone:string){const key=JSON.stringify([locale,timezone]);let formatter=timestampFormatters.get(key);if(!formatter){formatter=new Intl.DateTimeFormat(locale,{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23',timeZoneName:'short'});timestampFormatters.set(key,formatter);}return formatter;}
export function formatTimestamp(value:string,timezone:string,dateFormat:string){const parts=timestampFormatter('en-US',timezone).formatToParts(new Date(value));const get=(type:string)=>parts.find(p=>p.type===type)?.value??'';const date=dateFormat==='DD/MM/YYYY'?`${get('day')}/${get('month')}/${get('year')}`:dateFormat==='MM/DD/YYYY'?`${get('month')}/${get('day')}/${get('year')}`:`${get('year')}-${get('month')}-${get('day')}`;return `${date} ${get('hour')}:${get('minute')}:${get('second')} ${get('timeZoneName')}`;}
export function useTimestamp(){const p=useContext(Preferences);return (value:string|null)=>value===null?'Never':formatTimestamp(value,p.timezone,p.dateFormat);}
export function Timestamp({value,appearance='audw'}:{value:string;appearance?:'when'|'rwhen'|'audw'}){const format=useTimestamp();const now=useTimestampClock();return <time className={appearance} dateTime={value}><span className="audw">{format(value)}</span>{' · '}<span className="audw">{formatRelativeTime(value,now)}</span></time>;}
